PROGRAM MASTER

USE OMP_LIB

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8

TYPE FIELD_2D_VIEW
  REAL(KIND=JPRB), POINTER :: P(:) => NULL()
END TYPE FIELD_2D_VIEW

TYPE SURFACE_VIEW_GROUP_VARSF
  TYPE(FIELD_2D_VIEW), ALLOCATABLE, DIMENSION(:) :: PCHEMFLX   
END TYPE SURFACE_VIEW_GROUP_VARSF

TYPE MF_PHYS_SURF_TYPE
  TYPE(SURFACE_VIEW_GROUP_VARSF) :: GSD_VF
END TYPE MF_PHYS_SURF_TYPE

TYPE(MF_PHYS_SURF_TYPE) :: YLMF_PHYS_SURF

CHARACTER*8 :: CLARG

CLARG = '0'

IF (COMMAND_ARGUMENT_COUNT () > 0) THEN
  CALL GET_COMMAND_ARGUMENT (1, CLARG)
ENDIF

IF (CLARG (1:1) == '1') THEN
  ALLOCATE (YLMF_PHYS_SURF%GSD_VF%PCHEMFLX (1))
ENDIF

!$OMP PARALLEL FIRSTPRIVATE (YLMF_PHYS_SURF)

PRINT *, OMP_GET_THREAD_NUM (), LOC (YLMF_PHYS_SURF), ALLOCATED (YLMF_PHYS_SURF%GSD_VF%PCHEMFLX)

!$OMP END PARALLEL 

END PROGRAM

