SUBROUTINE LATTEX_DNT(KLON,KLEV,KFLSA,KFLEN,&
 & PMOY1,PMIXNL,&
 & PXSI,PXNLT9,PXT1,PXL0,PXL9,PXLF9,PCXNLT9,&
 & PSIDDHXT1,PSIDDHXT9,PSIDDHXL0,PXLF0,LDNESC,&
 & LDVD5,PDYT0,PDYT9)

IMPLICIT NONE

INTEGER(KIND=4)       :: KLON,KLEV,KFLSA,KFLEN
REAL(KIND=8)          :: PMOY1(KLON,KLEV)
REAL(KIND=8)          :: PMIXNL(KLON,KLEV)
REAL(KIND=8)          :: PXSI(KLON,KLEV)
REAL(KIND=8)          :: PXNLT9(KLON,KLEV)
REAL(KIND=8)          :: PXT1(KLON,KLEV)
REAL(KIND=8)          :: PXL0(KLON,KFLSA:KFLEN)
REAL(KIND=8)          :: PXL9(KLON,KFLSA:KFLEN)
REAL(KIND=8)          :: PXLF9(KLON,KFLSA:KFLEN)
REAL(KIND=8)          :: PCXNLT9(KLON,KLEV)
REAL(KIND=8)          :: PSIDDHXT1(KLON,KLEV)
REAL(KIND=8)          :: PSIDDHXT9(KLON,KLEV)
REAL(KIND=8)          :: PSIDDHXL0(KLON,KFLSA:KFLEN)
REAL(KIND=8)          :: PXLF0(KLON,KFLSA:KFLEN)
LOGICAL,OPTIONAL      :: LDNESC
LOGICAL,OPTIONAL      :: LDVD5
REAL(KIND=8),OPTIONAL :: PDYT0(KLON,KLEV)
REAL(KIND=8),OPTIONAL :: PDYT9(KLON,KLEV)

WRITE (0, *) "LATTEX_DNT"
STOP 1

END SUBROUTINE LATTEX_DNT


