SUBROUTINE SC2PRG (ZSLB1VDF9, ZT9CVWVNL, ZSLB1VD9_NL, ZT9NHY, CDARG)

REAL(KIND=8), POINTER :: ZSLB1VDF9(:)
REAL(KIND=8), POINTER :: ZT9CVWVNL(:,:)
REAL(KIND=8), POINTER :: ZSLB1VD9_NL(:)
REAL(KIND=8), POINTER :: ZT9NHY(:,:)
CHARACTER*1 :: CDARG

REAL(KIND=8), TARGET :: ZDUM1 (1), ZDUM2 (1,1)

IF (CDARG /= '0') THEN
ZSLB1VDF9   => ZDUM1
ZT9CVWVNL   => ZDUM2
ZSLB1VD9_NL => ZDUM1
ZT9NHY      => ZDUM2
ENDIF

END SUBROUTINE
