MODULE CONTROL_VECTORS_DATA_MIX

!   Purpose.
!   --------
!     Setup and store parameters from IFS not available in IFSAUX.
!
!   Author.
!   -------
!     Y. Tremolet
!
!   Modifications.
!   -------------- 
!     Original   25-Jul-2004
!     A. Deckmyn 01-Oct-2008 : LAM wavelet Jb
!     M. Fisher  15-Feb-2013 : Introduce structures (CTLVEC_STRUCT, etc.)
!     Y. Michel, MF, June 2018 Extension of the control variable for sqrt EnVar
!     S. Massart 19-Feb-2019 Parameter optimisation
! ------------------------------------------------------------------

USE PARKIND1  , ONLY : JPIM, JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE
SAVE
PRIVATE
PUBLIC CONTROL_VECTOR_DATA_STRUCT, &
     & CTLVEC_STRUCT, CTLVEC_STRUCT_ENS, &
     & SETUP_CTLVEC, &
     & DESTROY_CONTROL_VECTOR_DATA_STRUCT

TYPE CONTROL_VECTOR_DATA_STRUCT
  INTEGER(KIND=JPIM) :: NSMAX, NMSMAX, NENS, NSERR, NMODERR, &
           & MYTOVOFF, NCTL3, NCTL2, NCTL1, NPARAM, NPECV, NSCALES, &
           & NPROMA, N_REGIONS_NS, N_REGIONS_EW, &
           & MY_REGION_NS, MY_REGION_EW, MYPROC,&
           & NLENTOVSCV, NLENTOVSCVG, NVATOVV, NFLEVL, NFLEVG, NUMP,&
           & NOBNTV, NOBNTVG, NVE3D, NVE2D,MYSETW, NPRTRW, NPROC

  INTEGER(KIND=JPIM), ALLOCATABLE :: MYLEVS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NBLOCKSL(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NBLOCKSG(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NGPTOTL(:,:,:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NGPTOTG(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NGRB(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NLENTOVSCVP(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NVATOVOFF(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: N_REGIONS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NGRBE(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: MYMS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NALLMS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NPTRMS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NUMLL(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NPTRLL(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: NPSURF(:)

  LOGICAL :: LINITCV, LTOVSCV, LELAM, LWAVELETJB, LREPRO,LENSCV 

CONTAINS
   PROCEDURE :: DESTROY => DESTROY_CONTROL_VECTOR_DATA_STRUCT

END TYPE CONTROL_VECTOR_DATA_STRUCT

TYPE(CONTROL_VECTOR_DATA_STRUCT), POINTER :: CTLVEC_STRUCT => NULL()
TYPE(CONTROL_VECTOR_DATA_STRUCT), POINTER :: CTLVEC_STRUCT_ENS => NULL()

! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------

SUBROUTINE SETUP_CTLVEC(HANDLE,KCTL3,KCTL2,KCTL1,&
                      & KGRB,LDINIT,LDENS,KSMAX,KMSMAX,KENS, &
                      & KMERR,KVE3D,KVE2D,KSERR,KGRBE,KPARAM,KPECV,LDLAM, &
                      & LDWAVELET, LDTOVS,KLENTOVSCV,KLENTOVSCVG, &
                      & KLENTOVSCVP, KVATOVV,KVATOVOFF, &
                      & KPROMA,KFLEVL,KFLEVG,KMYLEVS, &
                      & KNUMP,KMYMS,KALLMS,KPTRMS,KNUMLL,KPTRLL,KPSURF,&
                      & KNSCALES,KBLOCKSL,KBLOCKSG,KGPTOTL,KGPTOTG, &
                      & K_REGIONS,K_REGIONS_NS,K_REGIONS_EW, &
                      & KSETA,KSETB,KPROC,KMYPROC, &
                      & KOBNTV,KOBNTVG,LDREPRO,KMYSETW,KPRTRW)

IMPLICIT NONE

TYPE(CONTROL_VECTOR_DATA_STRUCT), INTENT(IN), POINTER :: HANDLE
INTEGER(KIND=JPIM), INTENT(IN) :: KCTL3,KCTL2,KCTL1
INTEGER(KIND=JPIM), INTENT(IN) :: KGRB(KCTL3+KCTL2)
INTEGER(KIND=JPIM), INTENT(IN) :: KSMAX,KMSMAX,KMERR,KSERR,KPARAM,KPECV,KENS
INTEGER(KIND=JPIM), INTENT(IN) :: KVE3D,KVE2D
INTEGER(KIND=JPIM), INTENT(IN) :: KGRBE(KVE3D+KVE2D)
LOGICAL, INTENT(IN) :: LDINIT, LDENS, LDTOVS, LDWAVELET
INTEGER(KIND=JPIM), INTENT(IN) :: KLENTOVSCV, KLENTOVSCVG, KVATOVV
LOGICAL, INTENT(IN) :: LDLAM
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVL, KFLEVG, KNUMP, KNSCALES, KPROC, KMYPROC,  &
                                & KPROMA, K_REGIONS_NS, K_REGIONS_EW, KSETA, KSETB
INTEGER(KIND=JPIM), INTENT(IN) :: KALLMS(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KMYMS(:),KPTRMS(:),KNUMLL(:), KPTRLL(:), KPSURF(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KMYLEVS(KFLEVL), KBLOCKSL(KNSCALES), &
                                & KBLOCKSG(KNSCALES), KGPTOTG(KNSCALES), &
                                & KGPTOTL(KNSCALES,K_REGIONS_NS,K_REGIONS_EW)
INTEGER(KIND=JPIM), INTENT(IN) :: KLENTOVSCVP(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KVATOVOFF(:)
INTEGER(KIND=JPIM), INTENT(IN) :: K_REGIONS(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KPRTRW,KMYSETW
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KOBNTV, KOBNTVG
LOGICAL, INTENT(IN) :: LDREPRO

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_DATA_MIX:SETUP_CTLVEC',0,ZHOOK_HANDLE)
HANDLE%NCTL2=KCTL2
HANDLE%NCTL3=KCTL3
ALLOCATE(HANDLE%NGRB(HANDLE%NCTL3+HANDLE%NCTL2))
HANDLE%NGRB(:)=KGRB(:)
HANDLE%NCTL1=KCTL1
HANDLE%NSMAX=KSMAX
HANDLE%NMSMAX=KMSMAX
HANDLE%NMODERR=KMERR
HANDLE%NVE3D=KVE3D
HANDLE%NVE2D=KVE2D
ALLOCATE(HANDLE%NGRBE(HANDLE%NVE3D+HANDLE%NVE2D))
HANDLE%NGRBE(:)=KGRBE(:)
HANDLE%LINITCV=LDINIT
HANDLE%NSERR=KSERR
HANDLE%LTOVSCV=LDTOVS
HANDLE%NLENTOVSCV =KLENTOVSCV
HANDLE%NLENTOVSCVG=KLENTOVSCVG
HANDLE%NVATOVV=KVATOVV
HANDLE%NPROC=KPROC

HANDLE%LENSCV=LDENS
HANDLE%NENS=KENS

IF (HANDLE%LTOVSCV) THEN
  ALLOCATE(HANDLE%NLENTOVSCVP(KPROC))
  ALLOCATE(HANDLE%NVATOVOFF(KPROC))
  HANDLE%NLENTOVSCVP(:)=KLENTOVSCVP(:)
  HANDLE%NVATOVOFF(:)=KVATOVOFF(:)
  HANDLE%MYTOVOFF=KVATOVOFF(KMYPROC)
ENDIF
ALLOCATE(HANDLE%N_REGIONS(K_REGIONS_NS))
HANDLE%LELAM=LDLAM
HANDLE%NFLEVL=KFLEVL
HANDLE%NFLEVG=KFLEVG
HANDLE%NPROMA=KPROMA
HANDLE%N_REGIONS(1:K_REGIONS_NS)=K_REGIONS(1:K_REGIONS_NS)
HANDLE%N_REGIONS_NS=K_REGIONS_NS
HANDLE%N_REGIONS_EW=K_REGIONS_EW
HANDLE%MY_REGION_NS=KSETA
HANDLE%MY_REGION_EW=KSETB
HANDLE%MYPROC=KMYPROC
HANDLE%MYSETW=KMYSETW
HANDLE%NPRTRW=KPRTRW
HANDLE%NUMP=KNUMP

ALLOCATE(HANDLE%MYMS(SIZE(KMYMS)))
ALLOCATE(HANDLE%NALLMS(SIZE(KALLMS)))
ALLOCATE(HANDLE%MYLEVS(SIZE(KMYLEVS)))
ALLOCATE(HANDLE%NPTRMS(SIZE(KPTRMS)))
ALLOCATE(HANDLE%NUMLL(SIZE(KNUMLL)))
ALLOCATE(HANDLE%NPTRLL(SIZE(KPTRLL)))
ALLOCATE(HANDLE%NPSURF(SIZE(KPSURF)))
HANDLE%MYMS(:)=KMYMS(:)
HANDLE%NALLMS(:)=KALLMS(:)
HANDLE%MYLEVS(:)=KMYLEVS(:)
HANDLE%NPTRMS(:)=KPTRMS(:)
HANDLE%NUMLL(:)=KNUMLL(:)
HANDLE%NPTRLL(:)=KPTRLL(:)
HANDLE%NPSURF(:)=KPSURF(:)
HANDLE%NPARAM=KPARAM
HANDLE%NPECV=KPECV
HANDLE%LWAVELETJB=LDWAVELET
IF (LDWAVELET) THEN
  IF (HANDLE%LELAM) THEN
    ! nblocks and nblocksg used for basic LAM wavelets data distribution
    ALLOCATE(HANDLE%NBLOCKSL(2))
    HANDLE%NBLOCKSL(:)=KBLOCKSL(:)
    ALLOCATE(HANDLE%NBLOCKSG(2))
    HANDLE%NBLOCKSG(:)=KBLOCKSG(:)
  ELSE
    HANDLE%NSCALES=KNSCALES
    ALLOCATE (HANDLE%NBLOCKSL(KNSCALES))
    ALLOCATE (HANDLE%NBLOCKSG(KNSCALES))
    ALLOCATE (HANDLE%NGPTOTL(KNSCALES,K_REGIONS_NS,K_REGIONS_EW))
    ALLOCATE (HANDLE%NGPTOTG(KNSCALES))
    HANDLE%NBLOCKSL(:)=KBLOCKSL(:)
    HANDLE%NBLOCKSG(:)=KBLOCKSG(:)
    HANDLE%NGPTOTL(:,:,:)=KGPTOTL(:,:,:)
    HANDLE%NGPTOTG(:)=KGPTOTG(:)
  ENDIF
ENDIF

IF (PRESENT(KOBNTV)) HANDLE%NOBNTV=KOBNTV
IF (PRESENT(KOBNTVG)) HANDLE%NOBNTVG=KOBNTVG
HANDLE%LREPRO=LDREPRO

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_DATA_MIX:SETUP_CTLVEC',1,ZHOOK_HANDLE)
END SUBROUTINE SETUP_CTLVEC

! ------------------------------------------------------------------

SUBROUTINE DESTROY_CONTROL_VECTOR_DATA_STRUCT(HANDLE)

IMPLICIT NONE
CLASS(CONTROL_VECTOR_DATA_STRUCT), INTENT(INOUT) :: HANDLE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_DATA_MIX:DESTROY_CONTROL_VECTOR_DATA_STRUCT',0,ZHOOK_HANDLE)

DEALLOCATE(HANDLE%MYLEVS)
DEALLOCATE(HANDLE%NGRB)
DEALLOCATE(HANDLE%NGRBE)
DEALLOCATE(HANDLE%N_REGIONS)

IF (HANDLE%LTOVSCV) THEN
  DEALLOCATE(HANDLE%NLENTOVSCVP)
  DEALLOCATE(HANDLE%NVATOVOFF)
ENDIF

IF (HANDLE%LWAVELETJB) THEN
  DEALLOCATE(HANDLE%NBLOCKSL)
  DEALLOCATE(HANDLE%NBLOCKSG)
  IF (.NOT.HANDLE%LELAM) THEN
    DEALLOCATE (HANDLE%NGPTOTL)
    DEALLOCATE (HANDLE%NGPTOTG)
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('CONTROL_VECTORS_DATA_MIX:DESTROY_CONTROL_VECTOR_DATA_STRUCT',1,ZHOOK_HANDLE)
END SUBROUTINE DESTROY_CONTROL_VECTOR_DATA_STRUCT

! ------------------------------------------------------------------

END MODULE CONTROL_VECTORS_DATA_MIX
