
! Modifications
!   R. El Khatib 08-Aug-2023 Fix a memory error on XPNUDG
! End Modifications

MODULE CPG_OPTS_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMCLI, ONLY : TCLI
USE SURFACE_FIELDS_MIX , ONLY : TYPE_SURF_GEN

IMPLICIT NONE

TYPE CPG_DIM_VAR_TYPE
  INTEGER(KIND=JPIM) :: ILEVT1I
  INTEGER(KIND=JPIM) :: ILEVT1F
END TYPE


TYPE CPG_DIMS_VARS_TYPE
  TYPE (CPG_DIM_VAR_TYPE) :: U
  TYPE (CPG_DIM_VAR_TYPE) :: V
  TYPE (CPG_DIM_VAR_TYPE) :: T
  TYPE (CPG_DIM_VAR_TYPE) :: SVD
  TYPE (CPG_DIM_VAR_TYPE) :: Q
  TYPE (CPG_DIM_VAR_TYPE) :: I
  TYPE (CPG_DIM_VAR_TYPE) :: L
  TYPE (CPG_DIM_VAR_TYPE) :: IMF
  TYPE (CPG_DIM_VAR_TYPE) :: LMF
  TYPE (CPG_DIM_VAR_TYPE) :: LCONV
  TYPE (CPG_DIM_VAR_TYPE) :: ICONV
  TYPE (CPG_DIM_VAR_TYPE) :: RCONV
  TYPE (CPG_DIM_VAR_TYPE) :: SCONV
  TYPE (CPG_DIM_VAR_TYPE) :: IRAD
  TYPE (CPG_DIM_VAR_TYPE) :: LRAD
  TYPE (CPG_DIM_VAR_TYPE) :: S
  TYPE (CPG_DIM_VAR_TYPE) :: R
  TYPE (CPG_DIM_VAR_TYPE) :: G
  TYPE (CPG_DIM_VAR_TYPE) :: H
  TYPE (CPG_DIM_VAR_TYPE) :: TKE
  TYPE (CPG_DIM_VAR_TYPE) :: TTE
  TYPE (CPG_DIM_VAR_TYPE) :: EFB1
  TYPE (CPG_DIM_VAR_TYPE) :: EFB2
  TYPE (CPG_DIM_VAR_TYPE) :: EFB3
  TYPE (CPG_DIM_VAR_TYPE) :: A
  TYPE (CPG_DIM_VAR_TYPE) :: AMF
  TYPE (CPG_DIM_VAR_TYPE) :: O3
  TYPE (CPG_DIM_VAR_TYPE) :: SRC
  TYPE (CPG_DIM_VAR_TYPE) :: MXL
  TYPE (CPG_DIM_VAR_TYPE) :: SHTUR
  TYPE (CPG_DIM_VAR_TYPE) :: FQTUR
  TYPE (CPG_DIM_VAR_TYPE) :: FSTUR
  TYPE (CPG_DIM_VAR_TYPE) :: CPF
  TYPE (CPG_DIM_VAR_TYPE) :: SPF
  TYPE (CPG_DIM_VAR_TYPE) :: CVGQ
  TYPE (CPG_DIM_VAR_TYPE) :: QVA
  TYPE (CPG_DIM_VAR_TYPE) :: LRCH4
  TYPE (CPG_DIM_VAR_TYPE) :: PHYCTY
  TYPE (CPG_DIM_VAR_TYPE) :: RSPEC
  TYPE (CPG_DIM_VAR_TYPE) :: SDSAT
  TYPE (CPG_DIM_VAR_TYPE) :: CVV
  TYPE (CPG_DIM_VAR_TYPE) :: RKTH
  TYPE (CPG_DIM_VAR_TYPE) :: RKTQV
  TYPE (CPG_DIM_VAR_TYPE) :: RKTQC
  TYPE (CPG_DIM_VAR_TYPE) :: UOM
  TYPE (CPG_DIM_VAR_TYPE) :: UAL
  TYPE (CPG_DIM_VAR_TYPE) :: DOM
  TYPE (CPG_DIM_VAR_TYPE) :: DAL
  TYPE (CPG_DIM_VAR_TYPE) :: UEN
  TYPE (CPG_DIM_VAR_TYPE) :: UNEBH
  TYPE (CPG_DIM_VAR_TYPE) :: FSD
CONTAINS 
  PROCEDURE :: INIT => CPG_DIMS_VARS_TYPE_INIT
END TYPE CPG_DIMS_VARS_TYPE

TYPE CPG_DIMS_SURF_TYPE
  TYPE (TYPE_SURF_GEN) :: YSP_SBD
  TYPE (TYPE_SURF_GEN) :: YSP_SGD
  TYPE (TYPE_SURF_GEN) :: YSP_SLD
  TYPE (TYPE_SURF_GEN) :: YSP_RRD
  TYPE (TYPE_SURF_GEN) :: YSP_CLD
  TYPE (TYPE_SURF_GEN) :: YSP_OMD
  TYPE (TYPE_SURF_GEN) :: YSP_EPD
  TYPE (TYPE_SURF_GEN) :: YSP_X2D
  TYPE (TYPE_SURF_GEN) :: YSP_CID
  TYPE (TYPE_SURF_GEN) :: YSD_VFD
  TYPE (TYPE_SURF_GEN) :: YSD_VHD
  TYPE (TYPE_SURF_GEN) :: YSD_VKD
  TYPE (TYPE_SURF_GEN) :: YSD_VPD
  TYPE (TYPE_SURF_GEN) :: YSD_VVD
  TYPE (TYPE_SURF_GEN) :: YSD_VAD
  TYPE (TYPE_SURF_GEN) :: YSD_VND
  TYPE (TYPE_SURF_GEN) :: YSD_V2D
  TYPE (TYPE_SURF_GEN) :: YSD_V3D
  TYPE (TYPE_SURF_GEN) :: YSD_VDD
  TYPE (TYPE_SURF_GEN) :: YSD_SMD
  TYPE (TYPE_SURF_GEN) :: YSD_WSD
  TYPE (TYPE_SURF_GEN) :: YSD_WWD
  TYPE (TYPE_SURF_GEN) :: YSD_PFD
  TYPE (TYPE_SURF_GEN) :: YSD_XAD
  TYPE (TYPE_SURF_GEN) :: YSD_DID
  TYPE (TYPE_SURF_GEN) :: YSD_XPD
  TYPE (TYPE_SURF_GEN) :: YSD_XP2D
  TYPE (TYPE_SURF_GEN) :: YSD_X2D
  TYPE (TYPE_SURF_GEN) :: YSD_SFOD
  TYPE (TYPE_SURF_GEN) :: YSD_SFLD
  TYPE (TYPE_SURF_GEN) :: YSD_VCD
CONTAINS
  PROCEDURE :: INIT => CPG_DIMS_SURF_TYPE_INIT
END TYPE

TYPE CPG_BNDS_TYPE
  INTEGER(KIND=JPIM) :: KIDIA 
  INTEGER(KIND=JPIM) :: KFDIA 
  INTEGER(KIND=JPIM) :: KFDIE 
  INTEGER(KIND=JPIM) :: KIDIE
  INTEGER(KIND=JPIM) :: KBL 
  INTEGER(KIND=JPIM) :: KSTGLO 

  INTEGER(KIND=JPIM) :: KLON 
  INTEGER(KIND=JPIM) :: KGPTOT 
  INTEGER(KIND=JPIM) :: KGPCOMP 

CONTAINS
  GENERIC :: INIT => CPG_BNDS_TYPE_INIT_OPTS, CPG_BNDS_TYPE_INIT
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT_OPTS 
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT
  PROCEDURE :: UPDATE => CPG_BNDS_TYPE_UPDATE
END TYPE CPG_BNDS_TYPE

TYPE CPG_SURF_SB_TP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SB_QP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SB_TLP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SBP_OPTS_TYPE
  TYPE (CPG_SURF_SB_TP_OPTS_TYPE) :: YT
  TYPE (CPG_SURF_SB_QP_OPTS_TYPE) :: YQ
  TYPE (CPG_SURF_SB_TLP_OPTS_TYPE) :: YTL
END TYPE

TYPE CPG_SURF_SG_FP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SG_AP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SG_RP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SG_TP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SG_WP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SGP_OPTS_TYPE
  TYPE (CPG_SURF_SG_FP_OPTS_TYPE) :: YF
  TYPE (CPG_SURF_SG_AP_OPTS_TYPE) :: YA
  TYPE (CPG_SURF_SG_RP_OPTS_TYPE) :: YR
  TYPE (CPG_SURF_SG_TP_OPTS_TYPE) :: YT
  TYPE (CPG_SURF_SG_WP_OPTS_TYPE) :: YW
END TYPE

TYPE CPG_SURF_SL_LICTP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LMLTP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LTLTP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LBLTP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LSHFP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LICDP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SL_LMLDP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SLP_OPTS_TYPE
  TYPE (CPG_SURF_SL_LICTP_OPTS_TYPE) :: YLICT
  TYPE (CPG_SURF_SL_LMLTP_OPTS_TYPE) :: YLMLT
  TYPE (CPG_SURF_SL_LTLTP_OPTS_TYPE) :: YLTLT
  TYPE (CPG_SURF_SL_LBLTP_OPTS_TYPE) :: YLBLT
  TYPE (CPG_SURF_SL_LSHFP_OPTS_TYPE) :: YLSHF
  TYPE (CPG_SURF_SL_LICDP_OPTS_TYPE) :: YLICD
  TYPE (CPG_SURF_SL_LMLDP_OPTS_TYPE) :: YLMLD
END TYPE

TYPE CPG_SURF_RR_TP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_RR_WP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_RR_FCP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_RR_ICP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_RR_FP1P_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_RRP_OPTS_TYPE
  TYPE (CPG_SURF_RR_TP_OPTS_TYPE) :: YT
  TYPE (CPG_SURF_RR_WP_OPTS_TYPE) :: YW
  TYPE (CPG_SURF_RR_FCP_OPTS_TYPE) :: YFC
  TYPE (CPG_SURF_RR_ICP_OPTS_TYPE) :: YIC
  TYPE (CPG_SURF_RR_FP1P_OPTS_TYPE) :: YFP1
END TYPE

TYPE CPG_SURF_CL_TCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CL_HUCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CL_UCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CL_VCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CL_NUCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CL_NVCLSP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_CLP_OPTS_TYPE
  TYPE (CPG_SURF_CL_TCLSP_OPTS_TYPE) :: YTCLS
  TYPE (CPG_SURF_CL_HUCLSP_OPTS_TYPE) :: YHUCLS
  TYPE (CPG_SURF_CL_UCLSP_OPTS_TYPE) :: YUCLS
  TYPE (CPG_SURF_CL_VCLSP_OPTS_TYPE) :: YVCLS
  TYPE (CPG_SURF_CL_NUCLSP_OPTS_TYPE) :: YNUCLS
  TYPE (CPG_SURF_CL_NVCLSP_OPTS_TYPE) :: YNVCLS
END TYPE

TYPE CPG_SURF_OM_TOP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_OM_SOP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_OM_UOP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_OM_VOP_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_OMP_OPTS_TYPE
  TYPE (CPG_SURF_OM_TOP_OPTS_TYPE) :: YTO
  TYPE (CPG_SURF_OM_SOP_OPTS_TYPE) :: YSO
  TYPE (CPG_SURF_OM_UOP_OPTS_TYPE) :: YUO
  TYPE (CPG_SURF_OM_VOP_OPTS_TYPE) :: YVO
END TYPE

TYPE CPG_SURF_EPP_OPTS_TYPE
END TYPE

TYPE CPG_SURF_X2P_OPTS_TYPE
END TYPE

TYPE CPG_SURF_CIP_OPTS_TYPE
END TYPE

TYPE CPG_SURF_VF_Z0FD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALBFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_EMISFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_GETRLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_LSMD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_VEGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_VRLAND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_VRLDID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SIGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALBSFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_LAND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SSTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_LZ0HD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CVLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CO2TYPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CVHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CURD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_TVLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_TVHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_LAILD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_LAIHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_FWETD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SOTYD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CLKD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_DLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_UCURD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_VCURD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_Z0RLFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CGPPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_CRECD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SDFORD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALUVPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALUVDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALNIPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_ALNIDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_FP1D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_SO2DDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_DMSOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_URBFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_FCA1D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_FCA2D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_AERDEPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_AERLTSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_AERSCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VF_DSFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE





TYPE CPG_SURF_VF_NUDMD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE



TYPE CPG_SURF_VFD_OPTS_TYPE
  TYPE (CPG_SURF_VF_Z0FD_OPTS_TYPE) :: YZ0F 
  TYPE (CPG_SURF_VF_ALBFD_OPTS_TYPE) :: YALBF 
  TYPE (CPG_SURF_VF_EMISFD_OPTS_TYPE) :: YEMISF 
  TYPE (CPG_SURF_VF_GETRLD_OPTS_TYPE) :: YGETRL 
  TYPE (CPG_SURF_VF_LSMD_OPTS_TYPE) :: YLSM 
  TYPE (CPG_SURF_VF_VEGD_OPTS_TYPE) :: YVEG 
  TYPE (CPG_SURF_VF_VRLAND_OPTS_TYPE) :: YVRLAN 
  TYPE (CPG_SURF_VF_VRLDID_OPTS_TYPE) :: YVRLDI 
  TYPE (CPG_SURF_VF_SIGD_OPTS_TYPE) :: YSIG 
  TYPE (CPG_SURF_VF_ALBSFD_OPTS_TYPE) :: YALBSF 
  TYPE (CPG_SURF_VF_LAND_OPTS_TYPE) :: YLAN 
  TYPE (CPG_SURF_VF_SSTD_OPTS_TYPE) :: YSST 
  TYPE (CPG_SURF_VF_SSSD_OPTS_TYPE) :: YSSS 
  TYPE (CPG_SURF_VF_LZ0HD_OPTS_TYPE) :: YLZ0H 
  TYPE (CPG_SURF_VF_CVLD_OPTS_TYPE) :: YCVL 
  TYPE (CPG_SURF_VF_CO2TYPD_OPTS_TYPE) :: YCO2TYP 
  TYPE (CPG_SURF_VF_CVHD_OPTS_TYPE) :: YCVH 
  TYPE (CPG_SURF_VF_CURD_OPTS_TYPE) :: YCUR 
  TYPE (CPG_SURF_VF_TVLD_OPTS_TYPE) :: YTVL 
  TYPE (CPG_SURF_VF_TVHD_OPTS_TYPE) :: YTVH 
  TYPE (CPG_SURF_VF_LAILD_OPTS_TYPE) :: YLAIL 
  TYPE (CPG_SURF_VF_LAIHD_OPTS_TYPE) :: YLAIH 
  TYPE (CPG_SURF_VF_FWETD_OPTS_TYPE) :: YFWET 
  TYPE (CPG_SURF_VF_SOTYD_OPTS_TYPE) :: YSOTY 
  TYPE (CPG_SURF_VF_CLKD_OPTS_TYPE) :: YCLK 
  TYPE (CPG_SURF_VF_DLD_OPTS_TYPE) :: YDL 
  TYPE (CPG_SURF_VF_CID_OPTS_TYPE) :: YCI 
  TYPE (CPG_SURF_VF_UCURD_OPTS_TYPE) :: YUCUR 
  TYPE (CPG_SURF_VF_VCURD_OPTS_TYPE) :: YVCUR 
  TYPE (CPG_SURF_VF_Z0RLFD_OPTS_TYPE) :: YZ0RLF 
  TYPE (CPG_SURF_VF_CGPPD_OPTS_TYPE) :: YCGPP 
  TYPE (CPG_SURF_VF_CRECD_OPTS_TYPE) :: YCREC 
  TYPE (CPG_SURF_VF_SDFORD_OPTS_TYPE) :: YSDFOR 
  TYPE (CPG_SURF_VF_ALUVPD_OPTS_TYPE) :: YALUVP 
  TYPE (CPG_SURF_VF_ALUVDD_OPTS_TYPE) :: YALUVD 
  TYPE (CPG_SURF_VF_ALNIPD_OPTS_TYPE) :: YALNIP 
  TYPE (CPG_SURF_VF_ALNIDD_OPTS_TYPE) :: YALNID 
  TYPE (CPG_SURF_VF_FP1D_OPTS_TYPE) :: YFP1 
  TYPE (CPG_SURF_VF_SO2DDD_OPTS_TYPE) :: YSO2DD 
  TYPE (CPG_SURF_VF_DMSOD_OPTS_TYPE) :: YDMSO 
  TYPE (CPG_SURF_VF_URBFD_OPTS_TYPE) :: YURBF 
  TYPE (CPG_SURF_VF_FCA1D_OPTS_TYPE) :: YFCA1 
  TYPE (CPG_SURF_VF_FCA2D_OPTS_TYPE) :: YFCA2 
  TYPE (CPG_SURF_VF_AERDEPD_OPTS_TYPE) :: YAERDEP 
  TYPE (CPG_SURF_VF_AERLTSD_OPTS_TYPE) :: YAERLTS 
  TYPE (CPG_SURF_VF_AERSCCD_OPTS_TYPE) :: YAERSCC 
  TYPE (CPG_SURF_VF_DSFD_OPTS_TYPE) :: YDSF 
  TYPE (CPG_SURF_VF_NUDMD_OPTS_TYPE) :: YNUDM 
END TYPE

TYPE CPG_SURF_VH_TCCHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_SCCHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_BCCHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_PBLHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_SPSHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_QSHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_PCLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_PSLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_PCND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_PSND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VH_EVAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VHD_OPTS_TYPE
  TYPE (CPG_SURF_VH_TCCHD_OPTS_TYPE) :: YTCCH 
  TYPE (CPG_SURF_VH_SCCHD_OPTS_TYPE) :: YSCCH 
  TYPE (CPG_SURF_VH_BCCHD_OPTS_TYPE) :: YBCCH 
  TYPE (CPG_SURF_VH_PBLHD_OPTS_TYPE) :: YPBLH 
  TYPE (CPG_SURF_VH_SPSHD_OPTS_TYPE) :: YSPSH 
  TYPE (CPG_SURF_VH_QSHD_OPTS_TYPE) :: YQSH 
  TYPE (CPG_SURF_VH_PCLD_OPTS_TYPE) :: YPCL 
  TYPE (CPG_SURF_VH_PSLD_OPTS_TYPE) :: YPSL 
  TYPE (CPG_SURF_VH_PCND_OPTS_TYPE) :: YPCN 
  TYPE (CPG_SURF_VH_PSND_OPTS_TYPE) :: YPSN 
  TYPE (CPG_SURF_VH_EVAD_OPTS_TYPE) :: YEVA 
END TYPE

TYPE CPG_SURF_VK_UDGROD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VKD_OPTS_TYPE
  TYPE (CPG_SURF_VK_UDGROD_OPTS_TYPE) :: YUDGRO 
END TYPE

TYPE CPG_SURF_VP_TPCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VP_WPCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VPD_OPTS_TYPE
  TYPE (CPG_SURF_VP_TPCD_OPTS_TYPE) :: YTPC 
  TYPE (CPG_SURF_VP_WPCD_OPTS_TYPE) :: YWPC 
END TYPE

TYPE CPG_SURF_VV_ARGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_SABD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_D2D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_IVEGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_RSMIND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_LAID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_HVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_Z0HD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_ALSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VV_ALVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VVD_OPTS_TYPE
  TYPE (CPG_SURF_VV_ARGD_OPTS_TYPE) :: YARG 
  TYPE (CPG_SURF_VV_SABD_OPTS_TYPE) :: YSAB 
  TYPE (CPG_SURF_VV_D2D_OPTS_TYPE) :: YD2 
  TYPE (CPG_SURF_VV_IVEGD_OPTS_TYPE) :: YIVEG 
  TYPE (CPG_SURF_VV_RSMIND_OPTS_TYPE) :: YRSMIN 
  TYPE (CPG_SURF_VV_LAID_OPTS_TYPE) :: YLAI 
  TYPE (CPG_SURF_VV_HVD_OPTS_TYPE) :: YHV 
  TYPE (CPG_SURF_VV_Z0HD_OPTS_TYPE) :: YZ0H 
  TYPE (CPG_SURF_VV_ALSD_OPTS_TYPE) :: YALS 
  TYPE (CPG_SURF_VV_ALVD_OPTS_TYPE) :: YALV 
END TYPE

TYPE CPG_SURF_VA_SEAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VA_LAND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VA_SOOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VA_DESD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VA_SULD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VA_VOLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VAD_OPTS_TYPE
  TYPE (CPG_SURF_VA_SEAD_OPTS_TYPE) :: YSEA 
  TYPE (CPG_SURF_VA_LAND_OPTS_TYPE) :: YLAN 
  TYPE (CPG_SURF_VA_SOOD_OPTS_TYPE) :: YSOO 
  TYPE (CPG_SURF_VA_DESD_OPTS_TYPE) :: YDES 
  TYPE (CPG_SURF_VA_SULD_OPTS_TYPE) :: YSUL 
  TYPE (CPG_SURF_VA_VOLD_OPTS_TYPE) :: YVOL 
END TYPE

TYPE CPG_SURF_VN_TOPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VN_BASD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VN_ACPRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VN_ACCPRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VN_ACCPR5D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VND_OPTS_TYPE
  TYPE (CPG_SURF_VN_TOPD_OPTS_TYPE) :: YTOP 
  TYPE (CPG_SURF_VN_BASD_OPTS_TYPE) :: YBAS 
  TYPE (CPG_SURF_VN_ACPRD_OPTS_TYPE) :: YACPR 
  TYPE (CPG_SURF_VN_ACCPRD_OPTS_TYPE) :: YACCPR 
  TYPE (CPG_SURF_VN_ACCPR5D_OPTS_TYPE) :: YACCPR5 
END TYPE

TYPE CPG_SURF_V2_OCDEPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V2_USTRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V2_VSTRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V2D_OPTS_TYPE
  TYPE (CPG_SURF_V2_OCDEPD_OPTS_TYPE) :: YOCDEP 
  TYPE (CPG_SURF_V2_USTRCD_OPTS_TYPE) :: YUSTRC 
  TYPE (CPG_SURF_V2_VSTRCD_OPTS_TYPE) :: YVSTRC 
END TYPE

TYPE CPG_SURF_V3_DIFMD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_DIFTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_DIFSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_ADVTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_ADVSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_TRI0D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_TRI1D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_SWDKD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_ZOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_HOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_DOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_HO_INVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_UOCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_VOCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3_OTKED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_V3D_OPTS_TYPE
  TYPE (CPG_SURF_V3_DIFMD_OPTS_TYPE) :: YDIFM 
  TYPE (CPG_SURF_V3_DIFTD_OPTS_TYPE) :: YDIFT 
  TYPE (CPG_SURF_V3_DIFSD_OPTS_TYPE) :: YDIFS 
  TYPE (CPG_SURF_V3_ADVTD_OPTS_TYPE) :: YADVT 
  TYPE (CPG_SURF_V3_ADVSD_OPTS_TYPE) :: YADVS 
  TYPE (CPG_SURF_V3_TRI0D_OPTS_TYPE) :: YTRI0 
  TYPE (CPG_SURF_V3_TRI1D_OPTS_TYPE) :: YTRI1 
  TYPE (CPG_SURF_V3_SWDKD_OPTS_TYPE) :: YSWDK 
  TYPE (CPG_SURF_V3_ZOD_OPTS_TYPE) :: YZO 
  TYPE (CPG_SURF_V3_HOD_OPTS_TYPE) :: YHO 
  TYPE (CPG_SURF_V3_DOD_OPTS_TYPE) :: YDO 
  TYPE (CPG_SURF_V3_HO_INVD_OPTS_TYPE) :: YHO_INV 
  TYPE (CPG_SURF_V3_UOCD_OPTS_TYPE) :: YUOC 
  TYPE (CPG_SURF_V3_VOCD_OPTS_TYPE) :: YVOC 
  TYPE (CPG_SURF_V3_OTKED_OPTS_TYPE) :: YOTKE 
END TYPE

TYPE CPG_SURF_VD_LSPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_FZRAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_BLDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSHFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SLHFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_NEED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_GPPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_RECD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MSLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_10UD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_10VD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_2TD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_2DD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_2SHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_STRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TSRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TTRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_EWSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_NSSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_PEVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_HCCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LGWSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MGWSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_GWDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MX2TD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MN2TD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE



TYPE CPG_SURF_VD_ROD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SROD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSROD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ALBD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_IEWSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_INSSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ISSHFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_IED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_INEED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_IGPPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_IRECD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ICH4D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CSFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LSSFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MXTPRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MNTPRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE



TYPE CPG_SURF_VD_TPRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LSRRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CRRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LSSFRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CSFRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_PTYPED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ILSPFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_Z0FD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LZ0HD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_VIWVED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_VIWVND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCWVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCLWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCIWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCRWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCSWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCSLWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSRDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_STRDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSRDCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_STRDCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_BLHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SUNDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SPARD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SUVBD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SFDIRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SCDIRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SDSRPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CAPED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MUCAPED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MLCAPE50D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MLCAPE100D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_PDEPLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CAPESD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE



TYPE CPG_SURF_VD_TROPOTPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TSRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TTRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SSRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_STRCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ESD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SMLTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_10FGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE


TYPE CPG_SURF_VD_10FGCVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_I10FGD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LSPFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TCO3D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_VIMDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_SPARCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_STINCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CBASED_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_0DEGLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_M10DEGLD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_VISIHD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CIND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MLCIN50D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_MLCIN100D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_KINDEXD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TTINDEXD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CBASEAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_CTOPCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ZTWETB0D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ZTWETB1D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE





TYPE CPG_SURF_VD_100UD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_100VD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_200UD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_200VD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ZUSTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_10NUD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_10NVD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_DNDZND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_DNDZAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_DCTBD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TPLBD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_TPLTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODSSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODDUD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODOMD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODBCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODSUD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODNID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODAMD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODSOAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODVFAD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODVSUD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_ODTOACCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_AEPM1D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_AEPM25D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_AEPM10D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_UVBEDD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_UVBEDCSD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LITOTID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VD_LICGID_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE




TYPE CPG_SURF_VDD_OPTS_TYPE
  TYPE (CPG_SURF_VD_LSPD_OPTS_TYPE) :: YLSP 
  TYPE (CPG_SURF_VD_CPD_OPTS_TYPE) :: YCP 
  TYPE (CPG_SURF_VD_SFD_OPTS_TYPE) :: YSF 
  TYPE (CPG_SURF_VD_FZRAD_OPTS_TYPE) :: YFZRA 
  TYPE (CPG_SURF_VD_BLDD_OPTS_TYPE) :: YBLD 
  TYPE (CPG_SURF_VD_SSHFD_OPTS_TYPE) :: YSSHF 
  TYPE (CPG_SURF_VD_SLHFD_OPTS_TYPE) :: YSLHF 
  TYPE (CPG_SURF_VD_NEED_OPTS_TYPE) :: YNEE 
  TYPE (CPG_SURF_VD_GPPD_OPTS_TYPE) :: YGPP 
  TYPE (CPG_SURF_VD_RECD_OPTS_TYPE) :: YREC 
  TYPE (CPG_SURF_VD_MSLD_OPTS_TYPE) :: YMSL 
  TYPE (CPG_SURF_VD_SPD_OPTS_TYPE) :: YSP 
  TYPE (CPG_SURF_VD_TCCD_OPTS_TYPE) :: YTCC 
  TYPE (CPG_SURF_VD_10UD_OPTS_TYPE) :: Y10U 
  TYPE (CPG_SURF_VD_10VD_OPTS_TYPE) :: Y10V 
  TYPE (CPG_SURF_VD_2TD_OPTS_TYPE) :: Y2T 
  TYPE (CPG_SURF_VD_2DD_OPTS_TYPE) :: Y2D 
  TYPE (CPG_SURF_VD_2SHD_OPTS_TYPE) :: Y2SH 
  TYPE (CPG_SURF_VD_SSRD_OPTS_TYPE) :: YSSR 
  TYPE (CPG_SURF_VD_STRD_OPTS_TYPE) :: YSTR 
  TYPE (CPG_SURF_VD_TSRD_OPTS_TYPE) :: YTSR 
  TYPE (CPG_SURF_VD_TTRD_OPTS_TYPE) :: YTTR 
  TYPE (CPG_SURF_VD_EWSSD_OPTS_TYPE) :: YEWSS 
  TYPE (CPG_SURF_VD_NSSSD_OPTS_TYPE) :: YNSSS 
  TYPE (CPG_SURF_VD_ED_OPTS_TYPE) :: YE 
  TYPE (CPG_SURF_VD_PEVD_OPTS_TYPE) :: YPEV 
  TYPE (CPG_SURF_VD_CCCD_OPTS_TYPE) :: YCCC 
  TYPE (CPG_SURF_VD_LCCD_OPTS_TYPE) :: YLCC 
  TYPE (CPG_SURF_VD_MCCD_OPTS_TYPE) :: YMCC 
  TYPE (CPG_SURF_VD_HCCD_OPTS_TYPE) :: YHCC 
  TYPE (CPG_SURF_VD_LGWSD_OPTS_TYPE) :: YLGWS 
  TYPE (CPG_SURF_VD_MGWSD_OPTS_TYPE) :: YMGWS 
  TYPE (CPG_SURF_VD_GWDD_OPTS_TYPE) :: YGWD 
  TYPE (CPG_SURF_VD_MX2TD_OPTS_TYPE) :: YMX2T 
  TYPE (CPG_SURF_VD_MN2TD_OPTS_TYPE) :: YMN2T 
  TYPE (CPG_SURF_VD_ROD_OPTS_TYPE) :: YRO 
  TYPE (CPG_SURF_VD_SROD_OPTS_TYPE) :: YSRO 
  TYPE (CPG_SURF_VD_SSROD_OPTS_TYPE) :: YSSRO 
  TYPE (CPG_SURF_VD_ALBD_OPTS_TYPE) :: YALB 
  TYPE (CPG_SURF_VD_IEWSSD_OPTS_TYPE) :: YIEWSS 
  TYPE (CPG_SURF_VD_INSSSD_OPTS_TYPE) :: YINSSS 
  TYPE (CPG_SURF_VD_ISSHFD_OPTS_TYPE) :: YISSHF 
  TYPE (CPG_SURF_VD_IED_OPTS_TYPE) :: YIE 
  TYPE (CPG_SURF_VD_INEED_OPTS_TYPE) :: YINEE 
  TYPE (CPG_SURF_VD_IGPPD_OPTS_TYPE) :: YIGPP 
  TYPE (CPG_SURF_VD_IRECD_OPTS_TYPE) :: YIREC 
  TYPE (CPG_SURF_VD_ICH4D_OPTS_TYPE) :: YICH4 
  TYPE (CPG_SURF_VD_CSFD_OPTS_TYPE) :: YCSF 
  TYPE (CPG_SURF_VD_LSSFD_OPTS_TYPE) :: YLSSF 
  TYPE (CPG_SURF_VD_MXTPRD_OPTS_TYPE) :: YMXTPR 
  TYPE (CPG_SURF_VD_MNTPRD_OPTS_TYPE) :: YMNTPR 
  TYPE (CPG_SURF_VD_TPRD_OPTS_TYPE) :: YTPR 
  TYPE (CPG_SURF_VD_LSRRD_OPTS_TYPE) :: YLSRR 
  TYPE (CPG_SURF_VD_CRRD_OPTS_TYPE) :: YCRR 
  TYPE (CPG_SURF_VD_LSSFRD_OPTS_TYPE) :: YLSSFR 
  TYPE (CPG_SURF_VD_CSFRD_OPTS_TYPE) :: YCSFR 
  TYPE (CPG_SURF_VD_PTYPED_OPTS_TYPE) :: YPTYPE 
  TYPE (CPG_SURF_VD_ILSPFD_OPTS_TYPE) :: YILSPF 
  TYPE (CPG_SURF_VD_Z0FD_OPTS_TYPE) :: YZ0F 
  TYPE (CPG_SURF_VD_LZ0HD_OPTS_TYPE) :: YLZ0H 
  TYPE (CPG_SURF_VD_VIWVED_OPTS_TYPE) :: YVIWVE 
  TYPE (CPG_SURF_VD_VIWVND_OPTS_TYPE) :: YVIWVN 
  TYPE (CPG_SURF_VD_TCWD_OPTS_TYPE) :: YTCW 
  TYPE (CPG_SURF_VD_TCWVD_OPTS_TYPE) :: YTCWV 
  TYPE (CPG_SURF_VD_TCLWD_OPTS_TYPE) :: YTCLW 
  TYPE (CPG_SURF_VD_TCIWD_OPTS_TYPE) :: YTCIW 
  TYPE (CPG_SURF_VD_TCRWD_OPTS_TYPE) :: YTCRW 
  TYPE (CPG_SURF_VD_TCSWD_OPTS_TYPE) :: YTCSW 
  TYPE (CPG_SURF_VD_TCSLWD_OPTS_TYPE) :: YTCSLW 
  TYPE (CPG_SURF_VD_SSRDD_OPTS_TYPE) :: YSSRD 
  TYPE (CPG_SURF_VD_STRDD_OPTS_TYPE) :: YSTRD 
  TYPE (CPG_SURF_VD_SSRDCD_OPTS_TYPE) :: YSSRDC 
  TYPE (CPG_SURF_VD_STRDCD_OPTS_TYPE) :: YSTRDC 
  TYPE (CPG_SURF_VD_BLHD_OPTS_TYPE) :: YBLH 
  TYPE (CPG_SURF_VD_SUNDD_OPTS_TYPE) :: YSUND 
  TYPE (CPG_SURF_VD_SPARD_OPTS_TYPE) :: YSPAR 
  TYPE (CPG_SURF_VD_SUVBD_OPTS_TYPE) :: YSUVB 
  TYPE (CPG_SURF_VD_SFDIRD_OPTS_TYPE) :: YSFDIR 
  TYPE (CPG_SURF_VD_SCDIRD_OPTS_TYPE) :: YSCDIR 
  TYPE (CPG_SURF_VD_SDSRPD_OPTS_TYPE) :: YSDSRP 
  TYPE (CPG_SURF_VD_CAPED_OPTS_TYPE) :: YCAPE 
  TYPE (CPG_SURF_VD_MUCAPED_OPTS_TYPE) :: YMUCAPE 
  TYPE (CPG_SURF_VD_MLCAPE50D_OPTS_TYPE) :: YMLCAPE50 
  TYPE (CPG_SURF_VD_MLCAPE100D_OPTS_TYPE) :: YMLCAPE100 
  TYPE (CPG_SURF_VD_PDEPLD_OPTS_TYPE) :: YPDEPL 
  TYPE (CPG_SURF_VD_CAPESD_OPTS_TYPE) :: YCAPES 
  TYPE (CPG_SURF_VD_TROPOTPD_OPTS_TYPE) :: YTROPOTP 
  TYPE (CPG_SURF_VD_TSRCD_OPTS_TYPE) :: YTSRC 
  TYPE (CPG_SURF_VD_TTRCD_OPTS_TYPE) :: YTTRC 
  TYPE (CPG_SURF_VD_SSRCD_OPTS_TYPE) :: YSSRC 
  TYPE (CPG_SURF_VD_STRCD_OPTS_TYPE) :: YSTRC 
  TYPE (CPG_SURF_VD_ESD_OPTS_TYPE) :: YES 
  TYPE (CPG_SURF_VD_SMLTD_OPTS_TYPE) :: YSMLT 
  TYPE (CPG_SURF_VD_10FGD_OPTS_TYPE) :: Y10FG 
  TYPE (CPG_SURF_VD_10FGCVD_OPTS_TYPE) :: Y10FGCV 
  TYPE (CPG_SURF_VD_I10FGD_OPTS_TYPE) :: YI10FG 
  TYPE (CPG_SURF_VD_LSPFD_OPTS_TYPE) :: YLSPF 
  TYPE (CPG_SURF_VD_TCO3D_OPTS_TYPE) :: YTCO3 
  TYPE (CPG_SURF_VD_VIMDD_OPTS_TYPE) :: YVIMD 
  TYPE (CPG_SURF_VD_SPARCD_OPTS_TYPE) :: YSPARC 
  TYPE (CPG_SURF_VD_STINCD_OPTS_TYPE) :: YSTINC 
  TYPE (CPG_SURF_VD_CBASED_OPTS_TYPE) :: YCBASE 
  TYPE (CPG_SURF_VD_0DEGLD_OPTS_TYPE) :: Y0DEGL 
  TYPE (CPG_SURF_VD_M10DEGLD_OPTS_TYPE) :: YM10DEGL 
  TYPE (CPG_SURF_VD_VISIHD_OPTS_TYPE) :: YVISIH 
  TYPE (CPG_SURF_VD_CIND_OPTS_TYPE) :: YCIN 
  TYPE (CPG_SURF_VD_MLCIN50D_OPTS_TYPE) :: YMLCIN50 
  TYPE (CPG_SURF_VD_MLCIN100D_OPTS_TYPE) :: YMLCIN100 
  TYPE (CPG_SURF_VD_KINDEXD_OPTS_TYPE) :: YKINDEX 
  TYPE (CPG_SURF_VD_TTINDEXD_OPTS_TYPE) :: YTTINDEX 
  TYPE (CPG_SURF_VD_CBASEAD_OPTS_TYPE) :: YCBASEA 
  TYPE (CPG_SURF_VD_CTOPCD_OPTS_TYPE) :: YCTOPC 
  TYPE (CPG_SURF_VD_ZTWETB0D_OPTS_TYPE) :: YZTWETB0 
  TYPE (CPG_SURF_VD_ZTWETB1D_OPTS_TYPE) :: YZTWETB1 
  TYPE (CPG_SURF_VD_100UD_OPTS_TYPE) :: Y100U 
  TYPE (CPG_SURF_VD_100VD_OPTS_TYPE) :: Y100V 
  TYPE (CPG_SURF_VD_200UD_OPTS_TYPE) :: Y200U 
  TYPE (CPG_SURF_VD_200VD_OPTS_TYPE) :: Y200V 
  TYPE (CPG_SURF_VD_ZUSTD_OPTS_TYPE) :: YZUST 
  TYPE (CPG_SURF_VD_10NUD_OPTS_TYPE) :: Y10NU 
  TYPE (CPG_SURF_VD_10NVD_OPTS_TYPE) :: Y10NV 
  TYPE (CPG_SURF_VD_DNDZND_OPTS_TYPE) :: YDNDZN 
  TYPE (CPG_SURF_VD_DNDZAD_OPTS_TYPE) :: YDNDZA 
  TYPE (CPG_SURF_VD_DCTBD_OPTS_TYPE) :: YDCTB 
  TYPE (CPG_SURF_VD_TPLBD_OPTS_TYPE) :: YTPLB 
  TYPE (CPG_SURF_VD_TPLTD_OPTS_TYPE) :: YTPLT 
  TYPE (CPG_SURF_VD_ODSSD_OPTS_TYPE) :: YODSS 
  TYPE (CPG_SURF_VD_ODDUD_OPTS_TYPE) :: YODDU 
  TYPE (CPG_SURF_VD_ODOMD_OPTS_TYPE) :: YODOM 
  TYPE (CPG_SURF_VD_ODBCD_OPTS_TYPE) :: YODBC 
  TYPE (CPG_SURF_VD_ODSUD_OPTS_TYPE) :: YODSU 
  TYPE (CPG_SURF_VD_ODNID_OPTS_TYPE) :: YODNI 
  TYPE (CPG_SURF_VD_ODAMD_OPTS_TYPE) :: YODAM 
  TYPE (CPG_SURF_VD_ODSOAD_OPTS_TYPE) :: YODSOA 
  TYPE (CPG_SURF_VD_ODVFAD_OPTS_TYPE) :: YODVFA 
  TYPE (CPG_SURF_VD_ODVSUD_OPTS_TYPE) :: YODVSU 
  TYPE (CPG_SURF_VD_ODTOACCD_OPTS_TYPE) :: YODTOACC 
  TYPE (CPG_SURF_VD_AEPM1D_OPTS_TYPE) :: YAEPM1 
  TYPE (CPG_SURF_VD_AEPM25D_OPTS_TYPE) :: YAEPM25 
  TYPE (CPG_SURF_VD_AEPM10D_OPTS_TYPE) :: YAEPM10 
  TYPE (CPG_SURF_VD_UVBEDD_OPTS_TYPE) :: YUVBED 
  TYPE (CPG_SURF_VD_UVBEDCSD_OPTS_TYPE) :: YUVBEDCS 
  TYPE (CPG_SURF_VD_LITOTID_OPTS_TYPE) :: YLITOTI 
  TYPE (CPG_SURF_VD_LICGID_OPTS_TYPE) :: YLICGI 
END TYPE

TYPE CPG_SURF_SM_CLBTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SM_CSBTD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_SMD_OPTS_TYPE
  TYPE (CPG_SURF_SM_CLBTD_OPTS_TYPE) :: YCLBT 
  TYPE (CPG_SURF_SM_CSBTD_OPTS_TYPE) :: YCSBT 
END TYPE

TYPE CPG_SURF_WS_CHARD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_CHARHQD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_USTOKESD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_VSTOKESD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_TAUOCXD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_TAUOCYD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_PHIOCD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_WSEMEAND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WS_WSFMEAND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WSD_OPTS_TYPE
  TYPE (CPG_SURF_WS_CHARD_OPTS_TYPE) :: YCHAR 
  TYPE (CPG_SURF_WS_CHARHQD_OPTS_TYPE) :: YCHARHQ 
  TYPE (CPG_SURF_WS_USTOKESD_OPTS_TYPE) :: YUSTOKES 
  TYPE (CPG_SURF_WS_VSTOKESD_OPTS_TYPE) :: YVSTOKES 
  TYPE (CPG_SURF_WS_TAUOCXD_OPTS_TYPE) :: YTAUOCX 
  TYPE (CPG_SURF_WS_TAUOCYD_OPTS_TYPE) :: YTAUOCY 
  TYPE (CPG_SURF_WS_PHIOCD_OPTS_TYPE) :: YPHIOC 
  TYPE (CPG_SURF_WS_WSEMEAND_OPTS_TYPE) :: YWSEMEAN 
  TYPE (CPG_SURF_WS_WSFMEAND_OPTS_TYPE) :: YWSFMEAN 
END TYPE

TYPE CPG_SURF_WW_U10ND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_V10ND_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_RHOD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_ZILD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_CIFD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_CLKD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_UCURWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WW_VCURWD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_WWD_OPTS_TYPE
  TYPE (CPG_SURF_WW_U10ND_OPTS_TYPE) :: YU10N 
  TYPE (CPG_SURF_WW_V10ND_OPTS_TYPE) :: YV10N 
  TYPE (CPG_SURF_WW_RHOD_OPTS_TYPE) :: YRHO 
  TYPE (CPG_SURF_WW_ZILD_OPTS_TYPE) :: YZIL 
  TYPE (CPG_SURF_WW_CIFD_OPTS_TYPE) :: YCIF 
  TYPE (CPG_SURF_WW_CLKD_OPTS_TYPE) :: YCLK 
  TYPE (CPG_SURF_WW_UCURWD_OPTS_TYPE) :: YUCURW 
  TYPE (CPG_SURF_WW_VCURWD_OPTS_TYPE) :: YVCURW 
END TYPE

TYPE CPG_SURF_PFD_OPTS_TYPE
END TYPE

TYPE CPG_SURF_XAD_OPTS_TYPE
END TYPE

TYPE CPG_SURF_DI_XEDRD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_DID_OPTS_TYPE
  TYPE (CPG_SURF_DI_XEDRD_OPTS_TYPE) :: YXEDR 
END TYPE

TYPE CPG_SURF_XP_PRECIPD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_XPD_OPTS_TYPE
  TYPE (CPG_SURF_XP_PRECIPD_OPTS_TYPE) :: YPRECIP 
END TYPE

TYPE CPG_SURF_XP2_PRECIP2D_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_XP2D_OPTS_TYPE
  TYPE (CPG_SURF_XP2_PRECIP2D_OPTS_TYPE) :: YPRECIP2 
END TYPE

TYPE CPG_SURF_X2D_OPTS_TYPE
END TYPE

TYPE CPG_SURF_SFOD_OPTS_TYPE
END TYPE

TYPE CPG_SURF_SFLD_OPTS_TYPE
END TYPE

TYPE CPG_SURF_VC_AD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VC_BD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VC_CD_OPTS_TYPE
  LOGICAL :: LSET = .FALSE.
END TYPE

TYPE CPG_SURF_VCD_OPTS_TYPE
  TYPE (CPG_SURF_VC_AD_OPTS_TYPE) :: YA 
  TYPE (CPG_SURF_VC_BD_OPTS_TYPE) :: YB 
  TYPE (CPG_SURF_VC_CD_OPTS_TYPE) :: YC 
END TYPE


TYPE CPG_OPTS_SURF_TYPE

  TYPE (CPG_SURF_SBP_OPTS_TYPE) :: YSP_SB
  TYPE (CPG_SURF_SGP_OPTS_TYPE) :: YSP_SG
  TYPE (CPG_SURF_SLP_OPTS_TYPE) :: YSP_SL
  TYPE (CPG_SURF_RRP_OPTS_TYPE) :: YSP_RR
  TYPE (CPG_SURF_CLP_OPTS_TYPE) :: YSP_CL
  TYPE (CPG_SURF_OMP_OPTS_TYPE) :: YSP_OM
  TYPE (CPG_SURF_EPP_OPTS_TYPE) :: YSP_EP
  TYPE (CPG_SURF_X2P_OPTS_TYPE) :: YSP_X2
  TYPE (CPG_SURF_CIP_OPTS_TYPE) :: YSP_CI
  TYPE (CPG_SURF_VFD_OPTS_TYPE) :: YSD_VF
  TYPE (CPG_SURF_VHD_OPTS_TYPE) :: YSD_VH
  TYPE (CPG_SURF_VKD_OPTS_TYPE) :: YSD_VK
  TYPE (CPG_SURF_VPD_OPTS_TYPE) :: YSD_VP
  TYPE (CPG_SURF_VVD_OPTS_TYPE) :: YSD_VV
  TYPE (CPG_SURF_VAD_OPTS_TYPE) :: YSD_VA
  TYPE (CPG_SURF_VND_OPTS_TYPE) :: YSD_VN
  TYPE (CPG_SURF_V2D_OPTS_TYPE) :: YSD_V2
  TYPE (CPG_SURF_V3D_OPTS_TYPE) :: YSD_V3
  TYPE (CPG_SURF_VDD_OPTS_TYPE) :: YSD_VD
  TYPE (CPG_SURF_SMD_OPTS_TYPE) :: YSD_SM
  TYPE (CPG_SURF_WSD_OPTS_TYPE) :: YSD_WS
  TYPE (CPG_SURF_WWD_OPTS_TYPE) :: YSD_WW
  TYPE (CPG_SURF_PFD_OPTS_TYPE) :: YSD_PF
  TYPE (CPG_SURF_XAD_OPTS_TYPE) :: YSD_XA
  TYPE (CPG_SURF_DID_OPTS_TYPE) :: YSD_DI
  TYPE (CPG_SURF_XPD_OPTS_TYPE) :: YSD_XP
  TYPE (CPG_SURF_XP2D_OPTS_TYPE) :: YSD_XP2
  TYPE (CPG_SURF_X2D_OPTS_TYPE) :: YSD_X2
  TYPE (CPG_SURF_SFOD_OPTS_TYPE) :: YSD_SFO
  TYPE (CPG_SURF_SFLD_OPTS_TYPE) :: YSD_SFL
  TYPE (CPG_SURF_VCD_OPTS_TYPE) :: YSD_VC
CONTAINS
  PROCEDURE :: INIT => CPG_OPTS_SURF_TYPE_INIT
END TYPE

TYPE CPG_OPTS_TYPE

  INTEGER(KIND=JPIM) :: KLON 
  INTEGER(KIND=JPIM) :: KFLEVG 
  INTEGER(KIND=JPIM) :: KGPTOT 
  INTEGER(KIND=JPIM) :: KGPBLKS
  INTEGER(KIND=JPIM) :: KGPCOMP 
  INTEGER(KIND=JPIM) :: KGPTOTB

  INTEGER(KIND=JPIM) :: JBLKMIN
  INTEGER(KIND=JPIM) :: JBLKMAX

  INTEGER(KIND=JPIM) :: KGL1
  INTEGER(KIND=JPIM) :: KGL2
  INTEGER(KIND=JPIM) :: NSTEP
  INTEGER(KIND=JPIM) :: KTDIA
  INTEGER(KIND=JPIM) :: KVCLIS
  INTEGER(KIND=JPIM) :: NDTPREC
  INTEGER(KIND=JPIM) :: NDTPREC2
  INTEGER(KIND=JPIM) :: NDTPRECCUR
  INTEGER(KIND=JPIM) :: NDTPRECCUR2
  INTEGER(KIND=JPIM) :: KTSSG
  INTEGER(KIND=JPIM) :: KGRADIENTS
  INTEGER(KIND=JPIM) :: KMAXDRAFT
  INTEGER(KIND=JPIM) :: KSW

  INTEGER(KIND=JPIM) :: NPROC
  INTEGER(KIND=JPIM) :: NCONF
  INTEGER(KIND=JPIM) :: N2DINI

  TYPE (CPG_OPTS_SURF_TYPE) :: YRSURF_OPTS
  TYPE (CPG_DIMS_SURF_TYPE) :: YRSURF_DIMS
  TYPE (CPG_DIMS_VARS_TYPE) :: YRVARS_DIMS

  LOGICAL :: LCONFX, L_DFISTEP, LFSTEP, LDIAB, LSLPHY, LUSEPB1
  REAL(KIND=JPRB) :: ZDT, ZDTPHY, ZTE, ZBETADT

  TYPE (TCLI) :: YRCLI
  
  INTEGER (KIND=JPIM) :: NSSSSS
  INTEGER (KIND=JPIM) :: NFNUDG
  INTEGER (KIND=JPIM) :: NINDAT
  LOGICAL :: LAROME 
  LOGICAL :: LCALLSFX 
  LOGICAL :: LCORWAT
  LOGICAL :: LECMWF
  LOGICAL :: LINITER
  LOGICAL :: LELAM
  LOGICAL :: LFLASH
  LOGICAL :: LWSNOW
  LOGICAL :: LNUDG
  LOGICAL :: LRPLANE
  LOGICAL :: LSFORC
  LOGICAL :: LSFORCS  
  LOGICAL :: LSOMEGA_FRC
  LOGICAL :: LSPS_FRC
  LOGICAL :: LSW_FRC
  LOGICAL :: LXCLP
  LOGICAL :: LXCLPMF
  LOGICAL :: LXVMAXTH
  LOGICAL :: LXTGST
  LOGICAL :: LXXGST
  REAL (KIND=JPRB) :: RPLDARE 
  REAL (KIND=JPRB) :: RPLRG
  REAL (KIND=JPRB) :: TOPPRES
  REAL (KIND=JPRB) :: RPSTRA
  REAL (KIND=JPRB) :: RPTROP
  REAL (KIND=JPRB) :: RTSUR
  REAL (KIND=JPRB), ALLOCATABLE :: XPNUDG (:)


CONTAINS
  PROCEDURE :: INIT => CPG_OPTS_TYPE_INIT
  PROCEDURE :: UPDATE => CPG_OPTS_TYPE_UPDATE
END TYPE CPG_OPTS_TYPE

CONTAINS

  SUBROUTINE CPG_OPTS_TYPE_INIT (SELF, YDGEOMETRY, YDMODEL, YDFIELDS, CDCONF, LD_DFISTEP, KBLKMIN, KBLKMAX)
USE FIELDS_MOD, ONLY : FIELDS
USE TYPE_MODEL, ONLY : MODEL
USE YOMCT0,     ONLY : LAROME, LCORWAT, LELAM, LSFORCS, LCALLSFX, LSFORC, LRPLANE, LECMWF, NCONF, N2DINI
USE YOMCT3,     ONLY : NSTEP
USE YOMSTA,     ONLY : RPSTRA, RPTROP, RTSUR
USE YOMVERT,    ONLY : TOPPRES
USE YOMDYNCORE, ONLY : RPLDARE, RPLRG
USE YOMLSFORC,  ONLY : LSPS_FRC, LSW_FRC, LSOMEGA_FRC
USE YOMLUN,     ONLY : NULOUT
USE YOMNUD,     ONLY : NFNUDG, LNUDG
USE YOMRIP0,    ONLY : NINDAT
USE YOMSNU,     ONLY : XPNUDG
USE YOMRIP0,    ONLY : NSSSSS
USE YOMINI,     ONLY : LINITER
USE YOMCLI,     ONLY : YRCLI
USE YOMMP0,     ONLY : NPROC
CLASS(CPG_OPTS_TYPE) :: SELF
TYPE(MODEL)   , INTENT(IN) :: YDMODEL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS),   INTENT(IN) :: YDFIELDS
CHARACTER*1,    INTENT(IN) :: CDCONF
LOGICAL,        INTENT(IN) :: LD_DFISTEP
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KBLKMIN, KBLKMAX










































































END SUBROUTINE CPG_OPTS_TYPE_INIT

  SUBROUTINE CPG_OPTS_TYPE_UPDATE (SELF, KBLKMIN, KBLKMAX)
CLASS (CPG_OPTS_TYPE) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KBLKMIN
INTEGER (KIND=JPIM), INTENT (IN) :: KBLKMAX








END SUBROUTINE

  SUBROUTINE CPG_OPTS_SURF_TYPE_INIT (SELF, YDGEOMETRY, YDMODEL, YDFIELDS)
USE TYPE_MODEL, ONLY : MODEL
USE FIELDS_MOD, ONLY : FIELDS
CLASS(CPG_OPTS_SURF_TYPE) :: SELF
TYPE(MODEL)   , INTENT(IN) :: YDMODEL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS),   INTENT(IN) :: YDFIELDS












































































































































































































































































































END SUBROUTINE CPG_OPTS_SURF_TYPE_INIT

  SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS (SELF, YDCPG_OPTS)
CLASS(CPG_BNDS_TYPE) :: SELF
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS








END SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS

  SUBROUTINE CPG_BNDS_TYPE_INIT (SELF, KLON, KGPTOT)
CLASS(CPG_BNDS_TYPE) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KLON
INTEGER (KIND=JPIM), INTENT (IN) :: KGPTOT








END SUBROUTINE CPG_BNDS_TYPE_INIT

  SUBROUTINE CPG_DIMS_SURF_TYPE_INIT (SELF, YDGEOMETRY, YDMODEL, YDFIELDS)
USE TYPE_MODEL, ONLY : MODEL
USE FIELDS_MOD, ONLY : FIELDS
CLASS(CPG_DIMS_SURF_TYPE) :: SELF
TYPE(MODEL)   , INTENT(IN) :: YDMODEL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS),   INTENT(IN) :: YDFIELDS































END SUBROUTINE CPG_DIMS_SURF_TYPE_INIT

  SUBROUTINE CPG_BNDS_TYPE_UPDATE(SELF, IBL)
CLASS(CPG_BNDS_TYPE) :: SELF
INTEGER(KIND=JPIM), INTENT(IN) :: IBL




END SUBROUTINE CPG_BNDS_TYPE_UPDATE

  SUBROUTINE CPG_DIMS_VARS_TYPE_INIT (SELF, YDGEOMETRY, YDMODEL, YDVARS)
USE TYPE_MODEL, ONLY : MODEL
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
CLASS(CPG_DIMS_VARS_TYPE) :: SELF
TYPE(MODEL)   , INTENT(IN) :: YDMODEL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELD_VARIABLES),   INTENT(IN) :: YDVARS

END SUBROUTINE 

END MODULE CPG_OPTS_TYPE_MOD
