
MODULE DEV_ALLOC_MODULE


USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

USE ISO_C_BINDING
#ifdef _OPENACC
USE OPENACC
#endif

IMPLICIT NONE

INTERFACE DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5RM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5IM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_1LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_2LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_3LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_4LM_DEV_ALLOCATE_HST
  MODULE PROCEDURE FIELD_5LM_DEV_ALLOCATE_HST
END INTERFACE

INTERFACE DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5RM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5RD_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5IM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_1LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_2LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_3LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_4LM_DEV_ALLOCATE_DIM
  MODULE PROCEDURE FIELD_5LM_DEV_ALLOCATE_DIM
END INTERFACE

INTERFACE DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5RM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5RD_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5IM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_1LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_2LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_3LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_4LM_DEV_DEALLOCATE
  MODULE PROCEDURE FIELD_5LM_DEV_DEALLOCATE
END INTERFACE

INTERFACE
  SUBROUTINE DEV_MALLOC (SIZ, PTR) BIND (C, NAME='dev_malloc')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE
  SUBROUTINE DEV_FREE (PTR) BIND (C, NAME='dev_free')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE
END INTERFACE


CONTAINS




SUBROUTINE FIELD_1RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:)
REAL(KIND=JPRM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_1RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)


LOGICAL, INTENT(IN) :: MAP_DEVPTR










END SUBROUTINE FIELD_1RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_1RM_DEV_DEALLOCATE




SUBROUTINE FIELD_2RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_2RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)


LOGICAL, INTENT(IN) :: MAP_DEVPTR











END SUBROUTINE FIELD_2RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_2RM_DEV_DEALLOCATE




SUBROUTINE FIELD_3RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_3RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)


LOGICAL, INTENT(IN) :: MAP_DEVPTR












END SUBROUTINE FIELD_3RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_3RM_DEV_DEALLOCATE




SUBROUTINE FIELD_4RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_4RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)


LOGICAL, INTENT(IN) :: MAP_DEVPTR













END SUBROUTINE FIELD_4RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_4RM_DEV_DEALLOCATE




SUBROUTINE FIELD_5RM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_5RM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)


LOGICAL, INTENT(IN) :: MAP_DEVPTR














END SUBROUTINE FIELD_5RM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_5RM_DEV_DEALLOCATE




SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:)
REAL(KIND=JPRD), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)


LOGICAL, INTENT(IN) :: MAP_DEVPTR










END SUBROUTINE FIELD_1RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_1RD_DEV_DEALLOCATE




SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)


LOGICAL, INTENT(IN) :: MAP_DEVPTR











END SUBROUTINE FIELD_2RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_2RD_DEV_DEALLOCATE




SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)


LOGICAL, INTENT(IN) :: MAP_DEVPTR












END SUBROUTINE FIELD_3RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_3RD_DEV_DEALLOCATE




SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)


LOGICAL, INTENT(IN) :: MAP_DEVPTR













END SUBROUTINE FIELD_4RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_4RD_DEV_DEALLOCATE




SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
REAL(KIND=JPRD), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)


LOGICAL, INTENT(IN) :: MAP_DEVPTR














END SUBROUTINE FIELD_5RD_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5RD_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
REAL(KIND=JPRD), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_5RD_DEV_DEALLOCATE




SUBROUTINE FIELD_1IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:)
INTEGER(KIND=JPIM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_1IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)


LOGICAL, INTENT(IN) :: MAP_DEVPTR










END SUBROUTINE FIELD_1IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_1IM_DEV_DEALLOCATE




SUBROUTINE FIELD_2IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_2IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)


LOGICAL, INTENT(IN) :: MAP_DEVPTR











END SUBROUTINE FIELD_2IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_2IM_DEV_DEALLOCATE




SUBROUTINE FIELD_3IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_3IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)


LOGICAL, INTENT(IN) :: MAP_DEVPTR












END SUBROUTINE FIELD_3IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_3IM_DEV_DEALLOCATE




SUBROUTINE FIELD_4IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_4IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)


LOGICAL, INTENT(IN) :: MAP_DEVPTR













END SUBROUTINE FIELD_4IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_4IM_DEV_DEALLOCATE




SUBROUTINE FIELD_5IM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
INTEGER(KIND=JPIM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_5IM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5IM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)


LOGICAL, INTENT(IN) :: MAP_DEVPTR














END SUBROUTINE FIELD_5IM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5IM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
INTEGER(KIND=JPIM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_5IM_DEV_DEALLOCATE




SUBROUTINE FIELD_1LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:)
LOGICAL(KIND=JPLM), POINTER :: HST(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_1LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_1LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)


LOGICAL, INTENT(IN) :: MAP_DEVPTR










END SUBROUTINE FIELD_1LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_1LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_1LM_DEV_DEALLOCATE




SUBROUTINE FIELD_2LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_2LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_2LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)


LOGICAL, INTENT(IN) :: MAP_DEVPTR











END SUBROUTINE FIELD_2LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_2LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_2LM_DEV_DEALLOCATE




SUBROUTINE FIELD_3LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_3LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_3LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (3)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)


LOGICAL, INTENT(IN) :: MAP_DEVPTR












END SUBROUTINE FIELD_3LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_3LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_3LM_DEV_DEALLOCATE




SUBROUTINE FIELD_4LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_4LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_4LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (4)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)


LOGICAL, INTENT(IN) :: MAP_DEVPTR













END SUBROUTINE FIELD_4LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_4LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_4LM_DEV_DEALLOCATE




SUBROUTINE FIELD_5LM_DEV_ALLOCATE_HST (DEV, HST, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
LOGICAL(KIND=JPLM), POINTER :: HST(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR





END SUBROUTINE FIELD_5LM_DEV_ALLOCATE_HST

SUBROUTINE FIELD_5LM_DEV_ALLOCATE_DIM (DEV, UBOUNDS, LBOUNDS, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (5)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)


LOGICAL, INTENT(IN) :: MAP_DEVPTR














END SUBROUTINE FIELD_5LM_DEV_ALLOCATE_DIM

SUBROUTINE FIELD_5LM_DEV_DEALLOCATE (DEV, MAP_DEVPTR)
LOGICAL(KIND=JPLM), POINTER :: DEV(:,:,:,:,:)
LOGICAL, INTENT(IN) :: MAP_DEVPTR


END SUBROUTINE FIELD_5LM_DEV_DEALLOCATE



END MODULE DEV_ALLOC_MODULE
