MODULE EC_PARKIND
IMPLICIT NONE
SAVE
!
INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
INTEGER, PARAMETER :: JPIB = SELECTED_INT_KIND(12)

!
INTEGER, PARAMETER :: JPRM = SELECTED_REAL_KIND(6,37)
INTEGER, PARAMETER :: JPRD = SELECTED_REAL_KIND(13,300)


END MODULE EC_PARKIND
