
MODULE FIELD_3IM_ACCESS_MODULE


USE FIELD_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_3IM
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_3IM
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_3IM
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_3IM
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


INTEGER(KIND=JPIM), TARGET, SAVE :: DUMMY_FIELD_3IM (1, 1, 1)
!$acc declare create (DUMMY_FIELD_3IM)


CONTAINS


  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_3IM (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)

END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_3IM



  FUNCTION GET_HOST_DATA_RDONLY_FIELD_3IM (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)

END FUNCTION GET_HOST_DATA_RDONLY_FIELD_3IM



  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_3IM (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)

END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_3IM



  FUNCTION GET_HOST_DATA_RDWR_FIELD_3IM (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3IM), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:)

END FUNCTION GET_HOST_DATA_RDWR_FIELD_3IM



END MODULE FIELD_3IM_ACCESS_MODULE
