MODULE FIELD_ABORT_MODULE

IMPLICIT NONE

ABSTRACT INTERFACE
SUBROUTINE FIELD_ABORT_INTF (CDMESS)
CHARACTER (LEN=*), INTENT (IN) :: CDMESS
END SUBROUTINE
END INTERFACE

PROCEDURE (FIELD_ABORT_INTF), POINTER :: FIELD_ABORT_FUNC => NULL ()

PRIVATE

PUBLIC :: FIELD_ABORT, FIELD_ABORT_FUNC

CONTAINS

SUBROUTINE FIELD_ABORT (CDMESS)
CHARACTER (LEN=*), INTENT (IN) :: CDMESS


END SUBROUTINE

END MODULE
