
MODULE FIELD_4RD_FACTORY_MODULE


USE FIELD_MODULE
USE FIELD_GANG_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTERFACE FIELD_NEW
  MODULE PROCEDURE FIELD_4RD_NEW_OWNER
  MODULE PROCEDURE FIELD_4RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4RD_NEW_GANG_WRAPPER
  MODULE PROCEDURE FIELD_4RD_NEW_GANG_OWNER
END INTERFACE

PUBLIC :: FIELD_NEW

INTERFACE FIELD_DELETE
  MODULE PROCEDURE FIELD_4RD_DELETE
END INTERFACE FIELD_DELETE

PUBLIC :: FIELD_DELETE

INTERFACE FIELD_RESIZE
  MODULE PROCEDURE FIELD_4RD_RESIZE
END INTERFACE FIELD_RESIZE

PUBLIC :: FIELD_RESIZE

CONTAINS

SUBROUTINE FIELD_4RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR

INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR



END SUBROUTINE

SUBROUTINE FIELD_4RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA, MAP_DEVPTR, SYNC_ON_FINAL)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:)

INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL



END SUBROUTINE

SUBROUTINE FIELD_4RD_NEW_GANG_WRAPPER (FIELD_PTR, CHILDREN, LBOUNDS, PERSISTENT, DATA, SYNC_ON_FINAL)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR
TYPE(FIELD_3RD_PTR), ALLOCATABLE :: CHILDREN (:)
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL







END SUBROUTINE

SUBROUTINE FIELD_4RD_NEW_GANG_OWNER (FIELD_PTR, CHILDREN, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR
TYPE(FIELD_3RD_PTR), ALLOCATABLE :: CHILDREN (:)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE







END SUBROUTINE


SUBROUTINE FIELD_4RD_DELETE (FIELD_PTR)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR



END SUBROUTINE

SUBROUTINE FIELD_4RD_RESIZE (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT)
CLASS(FIELD_4RD), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_4RD_RESIZE


END MODULE
