
MODULE FIELD_4IM_MODULE


USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE DEV_ALLOC_MODULE
USE HOST_ALLOC_MODULE
USE FIELD_BASIC_MODULE
USE FIELD_CONSTANTS_MODULE
USE FIELD_DEFAULTS_MODULE
#ifdef _OPENACC
USE OPENACC
#endif
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

USE FIELD_4IM_DATA_MODULE, ONLY : FIELD_4IM_COPY_INTF

IMPLICIT NONE

PRIVATE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4IM
  INTEGER(KIND=JPIM), POINTER :: PTR(:,:,:,:) => NULL()
  INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: DEVPTR(:,:,:,:) => NULL()
  PROCEDURE (FIELD_4IM_COPY_INTF), POINTER, NOPASS :: COPY_FUNC => NULL ()
CONTAINS

  PROCEDURE :: FINAL => FIELD_4IM_FINAL
  PROCEDURE :: FIELD_4IM_FINAL
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4IM_DELETE_DEVICE_DATA
  PROCEDURE :: GET_VIEW => FIELD_4IM_GET_VIEW
  PROCEDURE :: GET_DEVICE_DATA_RDONLY => FIELD_4IM_GET_DEVICE_DATA_RDONLY
  PROCEDURE :: GET_DEVICE_DATA_RDWR => FIELD_4IM_GET_DEVICE_DATA_RDWR
  PROCEDURE :: GET_HOST_DATA_RDONLY => FIELD_4IM_GET_HOST_DATA_RDONLY
  PROCEDURE :: GET_HOST_DATA_RDWR => FIELD_4IM_GET_HOST_DATA_RDWR
  PROCEDURE :: SYNC_HOST_RDWR => FIELD_4IM_SYNC_HOST_RDWR
  PROCEDURE :: SYNC_HOST_RDONLY => FIELD_4IM_SYNC_HOST_RDONLY
  PROCEDURE :: SYNC_DEVICE_RDWR => FIELD_4IM_SYNC_DEVICE_RDWR
  PROCEDURE :: SYNC_DEVICE_RDONLY => FIELD_4IM_SYNC_DEVICE_RDONLY
  PROCEDURE :: COPY_OBJECT => FIELD_4IM_COPY_OBJECT
  PROCEDURE :: WIPE_OBJECT => FIELD_4IM_WIPE_OBJECT
  PROCEDURE(GET_DIMS), DEFERRED :: GET_DIMS
  PROCEDURE(RESIZE), DEFERRED :: RESIZE

  PROCEDURE :: GET_DEVICE_DATA => FIELD_4IM_GET_DEVICE_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_4IM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_4IM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_4IM_GET_DEVICE_DATA
  PROCEDURE, PRIVATE :: COPY_DATA =>  FIELD_4IM_COPY_DATA
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4IM_CREATE_DEVICE_DATA
#ifdef __PGI
  PROCEDURE :: SET_STATUS => FIELD_4IM_SET_STATUS
#endif
END TYPE FIELD_4IM

ABSTRACT INTERFACE
  SUBROUTINE GET_DIMS(SELF, LBOUNDS, UBOUNDS)
    USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_4IM
    CLASS(FIELD_4IM),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(4)
  END SUBROUTINE GET_DIMS
  SUBROUTINE RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_4IM
    CLASS(FIELD_4IM),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: UBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE RESIZE
END INTERFACE

PUBLIC :: FIELD_4IM

TYPE, EXTENDS(FIELD_4IM) :: FIELD_4IM_WRAPPER
  LOGICAL :: SYNC_ON_FINAL = .TRUE.
CONTAINS
  PROCEDURE :: INIT => FIELD_4IM_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_4IM_WRAPPER_FINAL
  PROCEDURE :: GET_DIMS => FIELD_4IM_WRAPPER_GET_DIMS
  PROCEDURE :: RESIZE => FIELD_4IM_WRAPPER_RESIZE
END TYPE FIELD_4IM_WRAPPER

PUBLIC :: FIELD_4IM_WRAPPER

TYPE, EXTENDS(FIELD_4IM) :: FIELD_4IM_OWNER
  INTEGER(KIND=JPIM) :: LBOUNDS(4), UBOUNDS(4)
  LOGICAL :: HAS_INIT_VALUE = .FALSE.
  LOGICAL :: PINNED = .FALSE.
  INTEGER(KIND=JPIM) :: INIT_VALUE
CONTAINS
  PROCEDURE :: INIT => FIELD_4IM_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_4IM_OWNER_FINAL
  PROCEDURE, PRIVATE :: CREATE_HOST_DATA => FIELD_4IM_CREATE_HOST_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_4IM_OWNER_GET_HOST_DATA
  PROCEDURE :: GET_DEVICE_DATA => FIELD_4IM_OWNER_GET_DEVICE_DATA
  PROCEDURE :: GET_DIMS => FIELD_4IM_OWNER_GET_DIMS
  PROCEDURE :: RESIZE => FIELD_4IM_OWNER_RESIZE
END TYPE FIELD_4IM_OWNER

PUBLIC :: FIELD_4IM_OWNER

TYPE FIELD_4IM_PTR
  CLASS(FIELD_4IM), POINTER :: PTR => NULL()
END TYPE FIELD_4IM_PTR

PUBLIC :: FIELD_4IM_PTR

TYPE FIELD_4IM_VIEW
  INTEGER(KIND=JPIM), POINTER :: P(:,:,:) => NULL()
END TYPE FIELD_4IM_VIEW

PUBLIC :: FIELD_4IM_VIEW


CONTAINS

  SUBROUTINE FIELD_4IM_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL)
USE FIELD_ABORT_MODULE
USE FIELD_DEFAULTS_MODULE
USE FIELD_4IM_DATA_MODULE, ONLY : FIELD_4IM_COPY_FUNC

CLASS(FIELD_4IM_WRAPPER) :: SELF
INTEGER(KIND=JPIM), TARGET, INTENT(IN) :: DATA(:,:,:,:)
LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL














END SUBROUTINE FIELD_4IM_WRAPPER_INIT

  SUBROUTINE FIELD_4IM_OWNER_INIT (SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR)
USE FIELD_ABORT_MODULE
USE FIELD_4IM_DATA_MODULE, ONLY : FIELD_4IM_COPY_FUNC
CLASS(FIELD_4IM_OWNER) :: SELF
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, OPTIONAL,  INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: INIT_VALUE


















END SUBROUTINE FIELD_4IM_OWNER_INIT

  SUBROUTINE FIELD_4IM_CREATE_HOST_DATA (SELF)

CLASS(FIELD_4IM_OWNER) :: SELF


END SUBROUTINE FIELD_4IM_CREATE_HOST_DATA

  FUNCTION FIELD_4IM_GET_VIEW(SELF, BLOCK_INDEX, ZERO) RESULT(VIEW_PTR)
USE FIELD_ABORT_MODULE
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), POINTER :: VIEW_PTR(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
LOGICAL, OPTIONAL,  INTENT(IN) :: ZERO









END FUNCTION FIELD_4IM_GET_VIEW

  SUBROUTINE FIELD_4IM_DELETE_DEVICE_DATA(SELF)

CLASS(FIELD_4IM) :: SELF

END SUBROUTINE FIELD_4IM_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4IM_FINAL(SELF)

CLASS(FIELD_4IM) :: SELF


END SUBROUTINE FIELD_4IM_FINAL

  SUBROUTINE FIELD_4IM_WRAPPER_FINAL(SELF)

CLASS(FIELD_4IM_WRAPPER) :: SELF



END SUBROUTINE FIELD_4IM_WRAPPER_FINAL

  SUBROUTINE FIELD_4IM_OWNER_FINAL(SELF)

CLASS(FIELD_4IM_OWNER) :: SELF


END SUBROUTINE FIELD_4IM_OWNER_FINAL

  SUBROUTINE FIELD_4IM_COPY_OBJECT (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS(FIELD_4IM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED





END SUBROUTINE FIELD_4IM_COPY_OBJECT

  SUBROUTINE FIELD_4IM_WIPE_OBJECT (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS(FIELD_4IM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED





END SUBROUTINE FIELD_4IM_WIPE_OBJECT

  SUBROUTINE FIELD_4IM_COPY_DATA (SELF, KDIR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN) :: QUEUE





END SUBROUTINE FIELD_4IM_COPY_DATA

  SUBROUTINE FIELD_4IM_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
INTEGER(KIND=JPIM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE





END SUBROUTINE FIELD_4IM_GET_HOST_DATA

  SUBROUTINE FIELD_4IM_OWNER_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_4IM_OWNER) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
INTEGER(KIND=JPIM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_OWNER_GET_HOST_DATA

  SUBROUTINE FIELD_4IM_GET_HOST_DATA_RDONLY (SELF, PPTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

END SUBROUTINE FIELD_4IM_GET_HOST_DATA_RDONLY

  SUBROUTINE FIELD_4IM_SYNC_HOST_RDONLY (SELF, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_SYNC_HOST_RDONLY

  SUBROUTINE FIELD_4IM_GET_HOST_DATA_RDWR (SELF, PPTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

END SUBROUTINE FIELD_4IM_GET_HOST_DATA_RDWR

  SUBROUTINE FIELD_4IM_SYNC_HOST_RDWR (SELF, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_SYNC_HOST_RDWR

  SUBROUTINE FIELD_4IM_CREATE_DEVICE_DATA (SELF)
CLASS(FIELD_4IM) :: SELF

END SUBROUTINE

  SUBROUTINE FIELD_4IM_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
INTEGER(KIND=JPIM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE






END SUBROUTINE FIELD_4IM_GET_DEVICE_DATA

  SUBROUTINE FIELD_4IM_OWNER_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_4IM_OWNER) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
INTEGER(KIND=JPIM), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_OWNER_GET_DEVICE_DATA

  SUBROUTINE FIELD_4IM_GET_DEVICE_DATA_RDONLY (SELF, PPTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

END SUBROUTINE FIELD_4IM_GET_DEVICE_DATA_RDONLY

  SUBROUTINE FIELD_4IM_SYNC_DEVICE_RDONLY (SELF, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_SYNC_DEVICE_RDONLY

  SUBROUTINE FIELD_4IM_GET_DEVICE_DATA_RDWR (SELF, PPTR, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

END SUBROUTINE FIELD_4IM_GET_DEVICE_DATA_RDWR

  SUBROUTINE FIELD_4IM_SYNC_DEVICE_RDWR (SELF, QUEUE)
CLASS(FIELD_4IM) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE


END SUBROUTINE FIELD_4IM_SYNC_DEVICE_RDWR

  SUBROUTINE FIELD_4IM_WRAPPER_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
CLASS(FIELD_4IM_WRAPPER),       INTENT(IN) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(4)


END SUBROUTINE FIELD_4IM_WRAPPER_GET_DIMS

  SUBROUTINE FIELD_4IM_OWNER_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
CLASS(FIELD_4IM_OWNER),         INTENT(IN) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(4)


END SUBROUTINE FIELD_4IM_OWNER_GET_DIMS

  SUBROUTINE FIELD_4IM_WRAPPER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
USE FIELD_ABORT_MODULE
CLASS(FIELD_4IM_WRAPPER),       INTENT(IN) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: UBOUNDS(4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_4IM_WRAPPER_RESIZE

  SUBROUTINE FIELD_4IM_OWNER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
CLASS(FIELD_4IM_OWNER),         INTENT(IN) :: SELF
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: UBOUNDS(4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT






END SUBROUTINE FIELD_4IM_OWNER_RESIZE

#ifdef __PGI
  SUBROUTINE FIELD_4IM_SET_STATUS (SELF, KSTATUS)
CLASS (FIELD_4IM) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

END SUBROUTINE FIELD_4IM_SET_STATUS
#endif


END MODULE FIELD_4IM_MODULE
