
MODULE FIELD_GATHSCAT_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_GATHSCAT_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

USE FIELD_1RM_GATHER_MODULE
USE FIELD_2RM_GATHER_MODULE
USE FIELD_3RM_GATHER_MODULE
USE FIELD_4RM_GATHER_MODULE
USE FIELD_5RM_GATHER_MODULE
USE FIELD_1RB_GATHER_MODULE
USE FIELD_2RB_GATHER_MODULE
USE FIELD_3RB_GATHER_MODULE
USE FIELD_4RB_GATHER_MODULE
USE FIELD_5RB_GATHER_MODULE
USE FIELD_1RD_GATHER_MODULE
USE FIELD_2RD_GATHER_MODULE
USE FIELD_3RD_GATHER_MODULE
USE FIELD_4RD_GATHER_MODULE
USE FIELD_5RD_GATHER_MODULE
USE FIELD_1IM_GATHER_MODULE
USE FIELD_2IM_GATHER_MODULE
USE FIELD_3IM_GATHER_MODULE
USE FIELD_4IM_GATHER_MODULE
USE FIELD_5IM_GATHER_MODULE
USE FIELD_1LM_GATHER_MODULE
USE FIELD_2LM_GATHER_MODULE
USE FIELD_3LM_GATHER_MODULE
USE FIELD_4LM_GATHER_MODULE
USE FIELD_5LM_GATHER_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_GATHSCAT


PUBLIC :: GATHER_DEVICE_DATA_RDONLY


PUBLIC :: GATHER_DEVICE_DATA_RDWR


PUBLIC :: GATHER_HOST_DATA_RDONLY


PUBLIC :: GATHER_HOST_DATA_RDWR


END MODULE FIELD_GATHSCAT_MODULE
