
MODULE FIELD_MODULE


USE DEV_ALLOC_MODULE

USE FIELD_1RM_MODULE
USE FIELD_2RM_MODULE
USE FIELD_3RM_MODULE
USE FIELD_4RM_MODULE
USE FIELD_5RM_MODULE
USE FIELD_1RB_MODULE
USE FIELD_2RB_MODULE
USE FIELD_3RB_MODULE
USE FIELD_4RB_MODULE
USE FIELD_5RB_MODULE
USE FIELD_1RD_MODULE
USE FIELD_2RD_MODULE
USE FIELD_3RD_MODULE
USE FIELD_4RD_MODULE
USE FIELD_5RD_MODULE
USE FIELD_1IM_MODULE
USE FIELD_2IM_MODULE
USE FIELD_3IM_MODULE
USE FIELD_4IM_MODULE
USE FIELD_5IM_MODULE
USE FIELD_1LM_MODULE
USE FIELD_2LM_MODULE
USE FIELD_3LM_MODULE
USE FIELD_4LM_MODULE
USE FIELD_5LM_MODULE

USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_1RM
PUBLIC :: FIELD_1RM_OWNER
PUBLIC :: FIELD_1RM_WRAPPER
PUBLIC :: FIELD_1RM_PTR
PUBLIC :: FIELD_2RM
PUBLIC :: FIELD_2RM_OWNER
PUBLIC :: FIELD_2RM_WRAPPER
PUBLIC :: FIELD_2RM_PTR
PUBLIC :: FIELD_2RM_VIEW
PUBLIC :: FIELD_3RM
PUBLIC :: FIELD_3RM_OWNER
PUBLIC :: FIELD_3RM_WRAPPER
PUBLIC :: FIELD_3RM_PTR
PUBLIC :: FIELD_3RM_VIEW
PUBLIC :: FIELD_4RM
PUBLIC :: FIELD_4RM_OWNER
PUBLIC :: FIELD_4RM_WRAPPER
PUBLIC :: FIELD_4RM_PTR
PUBLIC :: FIELD_4RM_VIEW
PUBLIC :: FIELD_5RM
PUBLIC :: FIELD_5RM_OWNER
PUBLIC :: FIELD_5RM_WRAPPER
PUBLIC :: FIELD_5RM_PTR
PUBLIC :: FIELD_5RM_VIEW
PUBLIC :: FIELD_1RB
PUBLIC :: FIELD_1RB_OWNER
PUBLIC :: FIELD_1RB_WRAPPER
PUBLIC :: FIELD_1RB_PTR
PUBLIC :: FIELD_2RB
PUBLIC :: FIELD_2RB_OWNER
PUBLIC :: FIELD_2RB_WRAPPER
PUBLIC :: FIELD_2RB_PTR
PUBLIC :: FIELD_2RB_VIEW
PUBLIC :: FIELD_3RB
PUBLIC :: FIELD_3RB_OWNER
PUBLIC :: FIELD_3RB_WRAPPER
PUBLIC :: FIELD_3RB_PTR
PUBLIC :: FIELD_3RB_VIEW
PUBLIC :: FIELD_4RB
PUBLIC :: FIELD_4RB_OWNER
PUBLIC :: FIELD_4RB_WRAPPER
PUBLIC :: FIELD_4RB_PTR
PUBLIC :: FIELD_4RB_VIEW
PUBLIC :: FIELD_5RB
PUBLIC :: FIELD_5RB_OWNER
PUBLIC :: FIELD_5RB_WRAPPER
PUBLIC :: FIELD_5RB_PTR
PUBLIC :: FIELD_5RB_VIEW
PUBLIC :: FIELD_1RD
PUBLIC :: FIELD_1RD_OWNER
PUBLIC :: FIELD_1RD_WRAPPER
PUBLIC :: FIELD_1RD_PTR
PUBLIC :: FIELD_2RD
PUBLIC :: FIELD_2RD_OWNER
PUBLIC :: FIELD_2RD_WRAPPER
PUBLIC :: FIELD_2RD_PTR
PUBLIC :: FIELD_2RD_VIEW
PUBLIC :: FIELD_3RD
PUBLIC :: FIELD_3RD_OWNER
PUBLIC :: FIELD_3RD_WRAPPER
PUBLIC :: FIELD_3RD_PTR
PUBLIC :: FIELD_3RD_VIEW
PUBLIC :: FIELD_4RD
PUBLIC :: FIELD_4RD_OWNER
PUBLIC :: FIELD_4RD_WRAPPER
PUBLIC :: FIELD_4RD_PTR
PUBLIC :: FIELD_4RD_VIEW
PUBLIC :: FIELD_5RD
PUBLIC :: FIELD_5RD_OWNER
PUBLIC :: FIELD_5RD_WRAPPER
PUBLIC :: FIELD_5RD_PTR
PUBLIC :: FIELD_5RD_VIEW
PUBLIC :: FIELD_1IM
PUBLIC :: FIELD_1IM_OWNER
PUBLIC :: FIELD_1IM_WRAPPER
PUBLIC :: FIELD_1IM_PTR
PUBLIC :: FIELD_2IM
PUBLIC :: FIELD_2IM_OWNER
PUBLIC :: FIELD_2IM_WRAPPER
PUBLIC :: FIELD_2IM_PTR
PUBLIC :: FIELD_2IM_VIEW
PUBLIC :: FIELD_3IM
PUBLIC :: FIELD_3IM_OWNER
PUBLIC :: FIELD_3IM_WRAPPER
PUBLIC :: FIELD_3IM_PTR
PUBLIC :: FIELD_3IM_VIEW
PUBLIC :: FIELD_4IM
PUBLIC :: FIELD_4IM_OWNER
PUBLIC :: FIELD_4IM_WRAPPER
PUBLIC :: FIELD_4IM_PTR
PUBLIC :: FIELD_4IM_VIEW
PUBLIC :: FIELD_5IM
PUBLIC :: FIELD_5IM_OWNER
PUBLIC :: FIELD_5IM_WRAPPER
PUBLIC :: FIELD_5IM_PTR
PUBLIC :: FIELD_5IM_VIEW
PUBLIC :: FIELD_1LM
PUBLIC :: FIELD_1LM_OWNER
PUBLIC :: FIELD_1LM_WRAPPER
PUBLIC :: FIELD_1LM_PTR
PUBLIC :: FIELD_2LM
PUBLIC :: FIELD_2LM_OWNER
PUBLIC :: FIELD_2LM_WRAPPER
PUBLIC :: FIELD_2LM_PTR
PUBLIC :: FIELD_2LM_VIEW
PUBLIC :: FIELD_3LM
PUBLIC :: FIELD_3LM_OWNER
PUBLIC :: FIELD_3LM_WRAPPER
PUBLIC :: FIELD_3LM_PTR
PUBLIC :: FIELD_3LM_VIEW
PUBLIC :: FIELD_4LM
PUBLIC :: FIELD_4LM_OWNER
PUBLIC :: FIELD_4LM_WRAPPER
PUBLIC :: FIELD_4LM_PTR
PUBLIC :: FIELD_4LM_VIEW
PUBLIC :: FIELD_5LM
PUBLIC :: FIELD_5LM_OWNER
PUBLIC :: FIELD_5LM_WRAPPER
PUBLIC :: FIELD_5LM_PTR
PUBLIC :: FIELD_5LM_VIEW

PUBLIC :: WAIT_FOR_ASYNC_QUEUE

CONTAINS

  SUBROUTINE WAIT_FOR_ASYNC_QUEUE(QUEUE)
INTEGER(KIND=JPIM), INTENT(IN) :: QUEUE


END SUBROUTINE WAIT_FOR_ASYNC_QUEUE

END MODULE FIELD_MODULE
