MODULE FIELD_CONTAINER_OPER_MOD
USE PARKIND1,            ONLY : JPRB, JPIM
USE YOMLUN             , ONLY : NULOUT
USE FIELD_CONTAINER_GP_MOD, ONLY : FIELD_CONTAINER_GP
USE FIELD_CONTAINER_SP_MOD, ONLY : FIELD_CONTAINER_SP,TYPE_ITERATOR
USE GEOMETRY_MOD,        ONLY : GEOMETRY
USE FIELD_DEFINITIONS  , ONLY : FID,MAIN_FIELD_METADATA,FIELD_ACCESS
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0,   ONLY : MYSETV
USE YOM_GRID_BICONSERV , ONLY : RGPPRS_HR,RGPPRS_LR
IMPLICIT NONE
CONTAINS

SUBROUTINE FIELD_CONTAINER_INTERP(YDGEOM_IN,YDGEOM_OUT,FIELD_IN,FIELD_OUT,&
 &                                KFIDS,KFIDS_SPEC,PSPSP,PGPSPGLO,&
 &                                KINTERPSURF)
IMPLICIT NONE
TYPE(GEOMETRY) , INTENT(IN)    :: YDGEOM_IN
TYPE(GEOMETRY) , INTENT(IN)    :: YDGEOM_OUT
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT)    :: FIELD_IN
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT) :: FIELD_OUT
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFIDS(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFIDS_SPEC(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KINTERPSURF
REAL(KIND=JPRB),OPTIONAL,   INTENT(IN) :: PSPSP(:)
REAL(KIND=JPRB),OPTIONAL,   INTENT(IN) :: PGPSPGLO(:,:)

REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:),ZFIELD3(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP3_IN(:,:,:),ZGP3_OUT(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP4_IN(:,:,:,:),ZGP4_OUT(:,:,:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IACTIVE(:),IFIDS_INTERP(:)
INTEGER(KIND=JPIM) :: INFIELDS,JFLD,IST,IEND,ID,IKGLO,JBLK,JF,INLEVS,INUM2D,JLEV,IN3D
INTEGER(KIND=JPIM) :: IPARAMID,INTERPSURF
CHARACTER(LEN=3)   :: CLLEVTYPE
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE


IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_INTERP',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_INTERP',1,ZHOOK_HANDLE)
END SUBROUTINE FIELD_CONTAINER_INTERP
!===============================================================================
SUBROUTINE SINTERP(KID,YDGEOM_IN,YDGEOM_OUT,PGPIN,PGPOUT,KPARAMID,CDLEVTYPE,KINTERPSURF)
USE YOMMP0   , ONLY : MYPROC,NPROC
USE YOM_GRID_BICONSERV, ONLY : RGPPRS_HR
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(IN)          :: KID
TYPE(GEOMETRY) , INTENT(IN)             :: YDGEOM_IN
TYPE(GEOMETRY) , INTENT(IN)             :: YDGEOM_OUT
REAL(KIND=JPRB),INTENT(IN)              :: PGPIN(:,:,:)
REAL(KIND=JPRB),INTENT(OUT)             :: PGPOUT(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN)           :: KPARAMID
CHARACTER(LEN=3),INTENT(IN)             :: CDLEVTYPE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KINTERPSURF

LOGICAL :: LLINTERPSURF
REAL(KIND=JPRB),ALLOCATABLE :: ZGRIDG_IN(:,:),ZGRIDG_OUT(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: ITO(:),ILEVS(:)
INTEGER(KIND=JPIM) :: IFLDSG,IFLDS,INTERP_TYPE,IDUM,JF,IL
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:SINTERP',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:SINTERP',1,ZHOOK_HANDLE)
END SUBROUTINE SINTERP
!===============================================================================
SUBROUTINE FIELD_CONTAINER_AXPY_SPEC(YDGEOM_X,YDGEOM_Y,FIELD_X,PZ,FIELD_Y,KFIDS)
USE YOMDIM     , ONLY : TDIM
USE YOMLAP     , ONLY : TLAP
TYPE(GEOMETRY), TARGET,   INTENT(IN)    :: YDGEOM_X
TYPE(GEOMETRY), TARGET,   INTENT(IN)    :: YDGEOM_Y
TYPE(FIELD_CONTAINER_GP), INTENT(INOUT) :: FIELD_X
REAL(KIND=JPRB),          INTENT(IN)    :: PZ
TYPE(FIELD_CONTAINER_GP), INTENT(INOUT) :: FIELD_Y
INTEGER(KIND=JPIM),       INTENT(IN)    :: KFIDS(:)

TYPE(TYPE_ITERATOR) :: YLIT
INTEGER(KIND=JPIM) :: IFIDS(SIZE(KFIDS)),J,ID,JF,JM,IM,ILEN,JS1,JS2,NSMAX_MIN
REAL(KIND=JPRB), POINTER :: ZSPEC_X_2D(:,:)
REAL(KIND=JPRB), POINTER :: ZSPEC_X_1D(:)
REAL(KIND=JPRB), POINTER :: ZSPEC_Y_2D(:,:)
REAL(KIND=JPRB), POINTER :: ZSPEC_Y_1D(:)
TYPE(FIELD_CONTAINER_SP) :: YLSPEC_X,YLSPEC_Y
TYPE(TDIM),      POINTER :: YDDIM_MIN
TYPE(TLAP),      POINTER :: YDLAP_MIN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_AXPY_SPEC',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_AXPY_SPEC',1,ZHOOK_HANDLE)
END SUBROUTINE FIELD_CONTAINER_AXPY_SPEC

!===============================================================================
SUBROUTINE FIELD_CONTAINER_COPY_SPEC(YDGEOM_IN,YDGEOM_OUT,FIELD_IN,FIELD_OUT,KFIDS)
TYPE(GEOMETRY) , INTENT(IN)    :: YDGEOM_IN
TYPE(GEOMETRY) , INTENT(IN)    :: YDGEOM_OUT
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT) :: FIELD_IN
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT) :: FIELD_OUT
INTEGER(KIND=JPIM),        INTENT(IN)    :: KFIDS(:)

TYPE(TYPE_ITERATOR) :: YLIT
INTEGER(KIND=JPIM) :: IFIDS(SIZE(KFIDS)),J,ID,JF,JM,IM,ILEN,JS1,JS2
REAL(KIND=JPRB), POINTER :: ZSPEC_IN_2D(:,:)
REAL(KIND=JPRB), POINTER :: ZSPEC_IN_1D(:)
REAL(KIND=JPRB), POINTER :: ZSPEC_OUT_2D(:,:)
REAL(KIND=JPRB), POINTER :: ZSPEC_OUT_1D(:)
TYPE(FIELD_CONTAINER_SP) :: YLSPEC_IN,YLSPEC_OUT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_COPY_SPEC',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_COPY_SPEC',1,ZHOOK_HANDLE)
END SUBROUTINE FIELD_CONTAINER_COPY_SPEC
!===============================================================================

SUBROUTINE FIELD_CONTAINER_WRITE_RESTART(YDGEOM,FIELD,CDFNAME)
USE YOMMP0   , ONLY : MYPROC,NPROC
USE IOSTREAM_MIX       , ONLY : SETUP_IOSTREAM, SETUP_IOREQUEST, IO_PUT,&
 &                              CLOSE_IOSTREAM, TYPE_IOSTREAM , TYPE_IOREQUEST,CLOSE_IOREQUEST
IMPLICIT NONE
TYPE(GEOMETRY) , INTENT(IN)               :: YDGEOM
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT)  :: FIELD
CHARACTER (LEN=*),         INTENT(IN)     :: CDFNAME


REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:),ZFIELD3(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP3(:,:,:),ZGP4(:,:,:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IACTIVE(:),IFIDSWRITE_RESTART(:)
INTEGER(KIND=JPIM) :: INFIELDS,JFLD,IST,IEND,ID,IKGLO,JBLK,JF,INLEVS,INUM2D,IBUF(1),IN3D,JLEV
CHARACTER (LEN = 256) ::  CLFN
CHARACTER (LEN = 5)   ::  CLMYPROC
TYPE(TYPE_IOSTREAM)   :: YL_IOSTREAM
TYPE(TYPE_IOREQUEST)  :: YL_IOREQUEST
REAL(KIND=JPHOOK)     :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_WRITE_RESTART',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_WRITE_RESTART',1,ZHOOK_HANDLE)
END SUBROUTINE FIELD_CONTAINER_WRITE_RESTART
!===============================================================================

SUBROUTINE FIELD_CONTAINER_READ_RESTART(YDGEOM,FIELD,CDFNAME)
USE YOMMP0   , ONLY : MYPROC,NPROC
USE IOSTREAM_MIX       , ONLY : SETUP_IOSTREAM, SETUP_IOREQUEST, IO_GET,&
 &                              CLOSE_IOSTREAM, TYPE_IOSTREAM , TYPE_IOREQUEST,CLOSE_IOREQUEST
IMPLICIT NONE
TYPE(GEOMETRY) , INTENT(IN)               :: YDGEOM
TYPE(FIELD_CONTAINER_GP) , INTENT(INOUT)  :: FIELD
CHARACTER (LEN=*),         INTENT(IN)     :: CDFNAME


REAL(KIND=JPRB),POINTER :: ZFIELD1(:),ZFIELD2(:,:),ZFIELD3(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZGP3(:,:,:),ZGP4(:,:,:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IACTIVE(:)
INTEGER(KIND=JPIM) :: INFIELDS,JFLD,IST,IEND,ID,IKGLO,JBLK,JF,INLEVS,INUM2D,IBUF(1),JLEV,IN3D
CHARACTER (LEN = 256) ::  CLFN
CHARACTER (LEN = 5)   ::  CLMYPROC
TYPE(TYPE_IOSTREAM)   :: YL_IOSTREAM
TYPE(TYPE_IOREQUEST)  :: YL_IOREQUEST
REAL(KIND=JPHOOK)     :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_READ_RESTART',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOM%YRDIM,YDDIMV=>YDGEOM%YRDIMV,YDGEM=>YDGEOM%YRGEM)

ASSOCIATE(NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, &
 & NGPTOT=>YDGEM%NGPTOT,NFLEVG=>YDDIMV%NFLEVG,NGPTOTG=>YDGEM%NGPTOTG)

!!$IF(PRESENT(KFIDS)) THEN
!!$  ALLOCATE(IACTIVE(SIZE(KFIDS)))
!!$  IACTIVE(:) = KFIDS(:)
!!$ELSE
  CALL FIELD%GET_ACTIVE_FIELDS(IACTIVE)
!!$ENDIF
INFIELDS = SIZE(IACTIVE)

WRITE(CLMYPROC,'(A1,I4.4)')'.',MYPROC
CLFN=TRIM(CDFNAME)//CLMYPROC

WRITE(UNIT=NULOUT,FMT='('' READ RESTART FILE '',A)') CLFN

CALL SETUP_IOSTREAM(YL_IOSTREAM,'CIO',TRIM(CLFN),CDMODE='r')
CALL SETUP_IOREQUEST(YL_IOREQUEST,'RAW')

CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
IF(IBUF(1) /= NGPTOT) CALL ABOR1('FIELD_CONTAINER_READ_RESTART: WRONG NGPTOT')
CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
IF(IBUF(1) /= INFIELDS) CALL ABOR1('FIELD_CONTAINER_READ_RESTART: WRONG NUMBER OF FIELDS')

DO JFLD=1,INFIELDS
  ID = IACTIVE(JFLD)

  IF(FIELD%METADATA(ID)%NDIMS == 1) THEN
    ALLOCATE(ZGP3(NPROMA,1,NGPBLKS))
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1) /= ID) CALL ABOR1('FIELD_CONTAINER_READ_RESTART: WRONG 2D FIELD ID')
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,PR3=ZGP3)
    DO JBLK=1,NGPBLKS
      IKGLO = 1+(JBLK-1)*NPROMA
      IST = 1
      IEND = MIN(NPROMA,NGPTOT-IKGLO+1)
      CALL FIELD%FIELD_OPEN_ONE(ID,JBLK,ZFIELD1)
      ZFIELD1(IST:IEND) = ZGP3(IST:IEND,1,JBLK)
      CALL FIELD%FIELD_CLOSE_ONE(ID,JBLK,ZFIELD1)
    ENDDO
    DEALLOCATE(ZGP3)
  ELSEIF(FIELD%METADATA(ID)%NDIMS == 2) THEN
    INLEVS = FIELD%NLEVELS(FIELD%METADATA(ID)%D2TYPE)
    ALLOCATE(ZGP3(NPROMA,INLEVS,NGPBLKS))
    IBUF(1)=ID
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1) /= ID) CALL ABOR1('FIELD_CONTAINER_READ_RESTART: WRONG 3D FIELD ID')
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,PR3=ZGP3)
    DO JBLK=1,NGPBLKS
      IKGLO = 1+(JBLK-1)*NPROMA
      IST = 1
      IEND = MIN(NPROMA,NGPTOT-IKGLO+1)
      CALL FIELD%FIELD_OPEN_ONE(ID,JBLK,ZFIELD2)
      DO JF=1,INLEVS
        ZFIELD2(IST:IEND,JF) = ZGP3(IST:IEND,JF,JBLK)
      ENDDO
      CALL FIELD%FIELD_CLOSE_ONE(ID,JBLK,ZFIELD2)
    ENDDO
    DEALLOCATE(ZGP3)
  ELSE
    INLEVS = FIELD%NLEVELS(FIELD%METADATA(ID)%D2TYPE)
    IN3D   = FIELD%NDIM3S(FIELD%METADATA(ID)%D3TYPE)
    ALLOCATE(ZGP4(NPROMA,INLEVS,IN3D,NGPBLKS))
    IBUF(1)=ID
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1) /= ID) CALL ABOR1('FIELD_CONTAINER_READ_RESTART: WRONG 3D FIELD ID')
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,PR4=ZGP4)
    DO JBLK=1,NGPBLKS
      IKGLO = 1+(JBLK-1)*NPROMA
      IST = 1
      IEND = MIN(NPROMA,NGPTOT-IKGLO+1)
      CALL FIELD%FIELD_OPEN_ONE(ID,JBLK,ZFIELD3)
      DO JF=1,IN3D
        DO JLEV=1,INLEVS
          ZFIELD3(IST:IEND,JLEV,JF) = ZGP4(IST:IEND,JLEV,JF,JBLK)
        ENDDO
      ENDDO
      CALL FIELD%FIELD_CLOSE_ONE(ID,JBLK,ZFIELD3)
    ENDDO
    DEALLOCATE(ZGP4)
  ENDIF
ENDDO

CALL CLOSE_IOREQUEST(YL_IOREQUEST)
CALL CLOSE_IOSTREAM(YL_IOSTREAM)

DEALLOCATE(IACTIVE)
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FIELD_CONTAINER_OPER_MOD:FIELD_CONTAINER_READ_RESTART',1,ZHOOK_HANDLE)
END SUBROUTINE FIELD_CONTAINER_READ_RESTART

END MODULE FIELD_CONTAINER_OPER_MOD
