
MODULE FIELD_5LM_UTIL_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_5LM
  MODULE PROCEDURE LOAD_FIELD_5LM_PTR
  MODULE PROCEDURE LOAD_FIELD_5LM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_5LM
  MODULE PROCEDURE SAVE_FIELD_5LM_PTR
  MODULE PROCEDURE SAVE_FIELD_5LM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_5LM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_5LM
  MODULE PROCEDURE COPY_FIELD_5LM_PTR
  MODULE PROCEDURE COPY_FIELD_5LM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_5LM
  MODULE PROCEDURE WIPE_FIELD_5LM_PTR
  MODULE PROCEDURE WIPE_FIELD_5LM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_5LM
  MODULE PROCEDURE HOST_FIELD_5LM_PTR
  MODULE PROCEDURE HOST_FIELD_5LM_VIEW
END INTERFACE

INTERFACE CRC64
  MODULE PROCEDURE CRC64_FIELD_5LM
END INTERFACE


CONTAINS

INTEGER*8 FUNCTION CRC64_FIELD_5LM (YD)
CLASS (FIELD_5LM), POINTER :: YD






END FUNCTION

SUBROUTINE LOAD_FIELD_5LM (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_5LM (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_5LM (CDMESS, YD, YO)
USE FIELD_ABORT_MODULE
CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_5LM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_5LM (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_5LM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_5LM (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_5LM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_5LM (SELF)
CLASS (FIELD_5LM), POINTER :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_5LM_VIEW (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM_VIEW) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_5LM_VIEW (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM_VIEW) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_5LM_VIEW (SELF, LDCREATED)
CLASS (FIELD_5LM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_5LM_VIEW (SELF, LDDELETED)
CLASS (FIELD_5LM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_5LM_VIEW (SELF)
CLASS (FIELD_5LM_VIEW) :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_5LM_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_5LM_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_5LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_5LM_PTR (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_5LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_5LM_PTR (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_5LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_5LM_PTR (SELF)
CLASS (FIELD_5LM_PTR) :: SELF

END SUBROUTINE 


END MODULE
