
MODULE FIELD_3RD_GATHER_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_SHUFFLE_TYPE_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

USE FIELD_3RD_SHUFFLE_MODULE


IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_SHUFFLE

INTERFACE GATHER_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: FIELD_3RD_GATHER_DEVICE_DATA_RDONLY
END INTERFACE

PUBLIC :: GATHER_DEVICE_DATA_RDONLY

INTERFACE GATHER_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: FIELD_3RD_GATHER_DEVICE_DATA_RDWR
END INTERFACE

PUBLIC :: GATHER_DEVICE_DATA_RDWR

INTERFACE GATHER_HOST_DATA_RDONLY
  MODULE PROCEDURE :: FIELD_3RD_GATHER_HOST_DATA_RDONLY
END INTERFACE

PUBLIC :: GATHER_HOST_DATA_RDONLY

INTERFACE GATHER_HOST_DATA_RDWR
  MODULE PROCEDURE :: FIELD_3RD_GATHER_HOST_DATA_RDWR
END INTERFACE

PUBLIC :: GATHER_HOST_DATA_RDWR


CONTAINS

FUNCTION FIELD_3RD_GATHER_DEVICE_DATA_RDONLY (SELF, YLF) RESULT (PTR)
CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_3RD),   POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:)

END FUNCTION FIELD_3RD_GATHER_DEVICE_DATA_RDONLY

FUNCTION FIELD_3RD_GATHER_DEVICE_DATA_RDWR (SELF, YLF) RESULT (PTR)
CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_3RD),   POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:)

END FUNCTION FIELD_3RD_GATHER_DEVICE_DATA_RDWR

FUNCTION FIELD_3RD_GATHER_HOST_DATA_RDONLY (SELF, YLF) RESULT (PTR)
CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_3RD),   POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:)

END FUNCTION FIELD_3RD_GATHER_HOST_DATA_RDONLY

FUNCTION FIELD_3RD_GATHER_HOST_DATA_RDWR (SELF, YLF) RESULT (PTR)
CLASS (FIELD_SHUFFLE)                      :: SELF
CLASS (FIELD_3RD),   POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:)

END FUNCTION FIELD_3RD_GATHER_HOST_DATA_RDWR


END MODULE FIELD_3RD_GATHER_MODULE
