
MODULE FIELD_3RB_ACCESS_MODULE


USE FIELD_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_3RB
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_3RB
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_3RB
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_3RB
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


REAL(KIND=JPRB), TARGET, SAVE :: DUMMY_FIELD_3RB (1, 1, 1)
!$acc declare create (DUMMY_FIELD_3RB)


CONTAINS


  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_3RB (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), POINTER :: PTR(:,:,:)

END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_3RB



  FUNCTION GET_HOST_DATA_RDONLY_FIELD_3RB (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), POINTER :: PTR(:,:,:)

END FUNCTION GET_HOST_DATA_RDONLY_FIELD_3RB



  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_3RB (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), POINTER :: PTR(:,:,:)

END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_3RB



  FUNCTION GET_HOST_DATA_RDWR_FIELD_3RB (FIELD_PTR) RESULT (PTR)
CLASS (FIELD_3RB), POINTER :: FIELD_PTR
REAL(KIND=JPRB), POINTER :: PTR(:,:,:)

END FUNCTION GET_HOST_DATA_RDWR_FIELD_3RB



END MODULE FIELD_3RB_ACCESS_MODULE
