
MODULE FIELD_5LM_DATA_MODULE


USE FIELD_CONSTANTS_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


PUBLIC :: FIELD_5LM_COPY
PUBLIC :: FIELD_5LM_COPY_FUNC
PUBLIC :: FIELD_5LM_COPY_INTF

ABSTRACT INTERFACE
  SUBROUTINE FIELD_5LM_COPY_INTF (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
    IMPORT :: JPIM, JPLM
    LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
  END SUBROUTINE
END INTERFACE

CONTAINS


  FUNCTION FIELD_5LM_COPY_FUNC (HST, DEV) RESULT (FUNC)
USE FIELD_ABORT_MODULE
PROCEDURE (FIELD_5LM_COPY_INTF), POINTER :: FUNC
LOGICAL(KIND=JPLM), POINTER, OPTIONAL :: HST (:,:,:,:,:), DEV (:,:,:,:,:)




END FUNCTION

  SUBROUTINE FIELD_5LM_COPY (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE



END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM0_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM1_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM2_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM3_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM4_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_5LM_COPY_DIM5_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
LOGICAL(KIND=JPLM), POINTER :: HST (:,:,:,:,:), DEV (:,:,:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif
#ifdef _OPENACC

#endif


END SUBROUTINE





  INTEGER (KIND=JPIM) FUNCTION FIELD_5LM_GET_LAST_CONTIGUOUS_DIMENSION (PTR, AFTER) RESULT (JDIM)
LOGICAL(KIND=JPLM), POINTER :: PTR (:,:,:,:,:)
INTEGER (KIND=JPIM) :: AFTER











END FUNCTION FIELD_5LM_GET_LAST_CONTIGUOUS_DIMENSION


END MODULE FIELD_5LM_DATA_MODULE
