
MODULE FIELD_1RB_UTIL_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_1RB
  MODULE PROCEDURE LOAD_FIELD_1RB_PTR
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_1RB
  MODULE PROCEDURE SAVE_FIELD_1RB_PTR
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_1RB
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_1RB
  MODULE PROCEDURE COPY_FIELD_1RB_PTR
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_1RB
  MODULE PROCEDURE WIPE_FIELD_1RB_PTR
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_1RB
  MODULE PROCEDURE HOST_FIELD_1RB_PTR
END INTERFACE

INTERFACE CRC64
  MODULE PROCEDURE CRC64_FIELD_1RB
END INTERFACE


CONTAINS

INTEGER*8 FUNCTION CRC64_FIELD_1RB (YD)
CLASS (FIELD_1RB), POINTER :: YD






END FUNCTION

SUBROUTINE LOAD_FIELD_1RB (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RB), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1RB (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RB), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_1RB (CDMESS, YD, YO)
USE FIELD_ABORT_MODULE
CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_1RB), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_1RB (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RB), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1RB (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RB) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1RB (SELF)
CLASS (FIELD_1RB), POINTER :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_1RB_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RB_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1RB_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RB_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_1RB_PTR (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RB_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1RB_PTR (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RB_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1RB_PTR (SELF)
CLASS (FIELD_1RB_PTR) :: SELF

END SUBROUTINE 


END MODULE
