
MODULE FIELD_3RB_DATA_MODULE


USE FIELD_CONSTANTS_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


PUBLIC :: FIELD_3RB_COPY
PUBLIC :: FIELD_3RB_COPY_FUNC
PUBLIC :: FIELD_3RB_COPY_INTF

ABSTRACT INTERFACE
  SUBROUTINE FIELD_3RB_COPY_INTF (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
    IMPORT :: JPIM, JPRB
    REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
  END SUBROUTINE
END INTERFACE

CONTAINS


  FUNCTION FIELD_3RB_COPY_FUNC (HST, DEV) RESULT (FUNC)
USE FIELD_ABORT_MODULE
PROCEDURE (FIELD_3RB_COPY_INTF), POINTER :: FUNC
REAL(KIND=JPRB), POINTER, OPTIONAL :: HST (:,:,:), DEV (:,:,:)




END FUNCTION

  SUBROUTINE FIELD_3RB_COPY (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE



END SUBROUTINE

  SUBROUTINE FIELD_3RB_COPY_DIM0_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_3RB_COPY_DIM1_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_3RB_COPY_DIM2_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif

END SUBROUTINE

  SUBROUTINE FIELD_3RB_COPY_DIM3_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
USE OPENACC
#endif
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
REAL(KIND=JPRB), POINTER :: HST (:,:,:), DEV (:,:,:)
LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE


#ifdef _OPENACC

#endif
#ifdef _OPENACC

#endif


END SUBROUTINE





  INTEGER (KIND=JPIM) FUNCTION FIELD_3RB_GET_LAST_CONTIGUOUS_DIMENSION (PTR, AFTER) RESULT (JDIM)
REAL(KIND=JPRB), POINTER :: PTR (:,:,:)
INTEGER (KIND=JPIM) :: AFTER









END FUNCTION FIELD_3RB_GET_LAST_CONTIGUOUS_DIMENSION


END MODULE FIELD_3RB_DATA_MODULE
