
MODULE FIELD_4RB_GANG_MODULE

USE FIELD_BASIC_MODULE
USE FIELD_CONSTANTS_MODULE
USE DEV_ALLOC_MODULE




USE FIELD_4RB_MODULE
USE FIELD_3RB_MODULE

USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


TYPE, EXTENDS (FIELD_3RB_WRAPPER) :: FIELD_3RB_WRAPPER_HELPER
  CLASS (FIELD_BASIC), POINTER :: PARENT => NULL ()
CONTAINS
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_3RB_DELETE_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_3RB_CREATE_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: SET_DEVICE_DIRTY => FIELD_3RB_SET_DEVICE_DIRTY_DATA_WRAPPER_HELPER
  PROCEDURE :: GET_DEVICE_DATA => FIELD_3RB_GET_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: GET_HOST_DATA => FIELD_3RB_GET_HOST_DATA_WRAPPER_HELPER
END TYPE

TYPE FIELD_3RB_WRAPPER_HELPER_PTR
  CLASS (FIELD_3RB_WRAPPER_HELPER), POINTER :: PTR => NULL ()
END TYPE


TYPE, EXTENDS (FIELD_4RB_WRAPPER) :: FIELD_4RB_GANG_WRAPPER
  TYPE (FIELD_3RB_WRAPPER_HELPER_PTR), POINTER :: CHILDREN (:) => NULL ()
CONTAINS
  PROCEDURE :: INIT => FIELD_4RB_GANG_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_4RB_GANG_WRAPPER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RB_GANG_WRAPPER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RB_GANG_WRAPPER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_4RB_GANG_WRAPPER_SET_STATUS
END TYPE FIELD_4RB_GANG_WRAPPER

PUBLIC :: FIELD_4RB_GANG_WRAPPER


TYPE, EXTENDS (FIELD_4RB_OWNER) :: FIELD_4RB_GANG_OWNER
  TYPE (FIELD_3RB_WRAPPER_HELPER_PTR), POINTER :: CHILDREN (:) => NULL ()
CONTAINS
  PROCEDURE :: INIT => FIELD_4RB_GANG_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_4RB_GANG_OWNER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RB_GANG_OWNER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RB_GANG_OWNER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_4RB_GANG_OWNER_SET_STATUS
END TYPE FIELD_4RB_GANG_OWNER

PUBLIC :: FIELD_4RB_GANG_OWNER


CONTAINS

  SUBROUTINE FIELD_3RB_CREATE_DEVICE_DATA_WRAPPER_HELPER (SELF)
CLASS(FIELD_3RB_WRAPPER_HELPER) :: SELF

END SUBROUTINE

  SUBROUTINE FIELD_3RB_DELETE_DEVICE_DATA_WRAPPER_HELPER (SELF)
CLASS(FIELD_3RB_WRAPPER_HELPER) :: SELF

END SUBROUTINE

  SUBROUTINE FIELD_3RB_SET_DEVICE_DIRTY_DATA_WRAPPER_HELPER (SELF)
CLASS (FIELD_3RB_WRAPPER_HELPER) :: SELF

END SUBROUTINE 

  SUBROUTINE FIELD_3RB_GET_HOST_DATA_WRAPPER_HELPER (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_3RB_WRAPPER_HELPER) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
REAL(KIND=JPRB), POINTER,         INTENT(INOUT) :: PTR(:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE



END SUBROUTINE 

  SUBROUTINE FIELD_3RB_GET_DEVICE_DATA_WRAPPER_HELPER (SELF, MODE, PTR, QUEUE)
CLASS(FIELD_3RB_WRAPPER_HELPER) :: SELF
INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
REAL(KIND=JPRB), POINTER,         INTENT(INOUT) :: PTR(:,:,:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE



END SUBROUTINE 


  SUBROUTINE FIELD_4RB_GANG_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL)
CLASS(FIELD_4RB_GANG_WRAPPER) :: SELF
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:,:)
LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL












END SUBROUTINE FIELD_4RB_GANG_WRAPPER_INIT

  SUBROUTINE FIELD_4RB_GANG_OWNER_INIT(SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR)
CLASS(FIELD_4RB_GANG_OWNER) :: SELF
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR












END SUBROUTINE FIELD_4RB_GANG_OWNER_INIT

  SUBROUTINE FIELD_4RB_GANG_WRAPPER_FINAL(SELF)
CLASS(FIELD_4RB_GANG_WRAPPER) :: SELF







END SUBROUTINE FIELD_4RB_GANG_WRAPPER_FINAL

  SUBROUTINE FIELD_4RB_GANG_WRAPPER_DELETE_DEVICE_DATA(SELF)

CLASS(FIELD_4RB_GANG_WRAPPER) :: SELF


END SUBROUTINE FIELD_4RB_GANG_WRAPPER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4RB_GANG_WRAPPER_CREATE_DEVICE_DATA (SELF)
CLASS(FIELD_4RB_GANG_WRAPPER) :: SELF



END SUBROUTINE

  SUBROUTINE FIELD_4RB_GANG_WRAPPER_SET_STATUS (SELF, KSTATUS)
CLASS(FIELD_4RB_GANG_WRAPPER) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS



END SUBROUTINE

  SUBROUTINE FIELD_4RB_GANG_OWNER_FINAL(SELF)
CLASS(FIELD_4RB_GANG_OWNER) :: SELF







END SUBROUTINE FIELD_4RB_GANG_OWNER_FINAL

  SUBROUTINE FIELD_4RB_GANG_OWNER_DELETE_DEVICE_DATA(SELF)

CLASS(FIELD_4RB_GANG_OWNER) :: SELF


END SUBROUTINE FIELD_4RB_GANG_OWNER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4RB_GANG_OWNER_CREATE_DEVICE_DATA (SELF)
CLASS(FIELD_4RB_GANG_OWNER) :: SELF



END SUBROUTINE

  SUBROUTINE FIELD_4RB_GANG_OWNER_SET_STATUS (SELF, KSTATUS)
CLASS(FIELD_4RB_GANG_OWNER) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS



END SUBROUTINE



END MODULE FIELD_4RB_GANG_MODULE
