


MODULE FIELD_REGISTRY_MOD

USE PARKIND1, ONLY : JPIM, JPRB, JPRD

USE FIELD_MODULE
USE GEOMETRY_MOD, ONLY: GEOMETRY
USE VARIABLE_MODULE
USE FIELD_FACTORY_MODULE
USE GEOMETRY_MOD, ONLY: GEOMETRY
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE SURFACE_VARIABLES_MOD, ONLY: SURFACE_VARIABLES
USE YOMGMV, ONLY: TGMV
USE YOM_YGFL, ONLY: TYPE_GFL_COMP, TYPE_GFLD
USE YOMGFL, ONLY: TGFL
USE SURFACE_FIELDS_MIX, ONLY: TSURF, TYPE_SURF_MTL_2D, TYPE_SURF_MTL_3D, TYPE_SURF_GEN
USE EC_PHYS_FIELDS_MOD, ONLY: TEC_PHYS_FIELDS
USE MODEL_PHYSICS_RADIATION_MOD, ONLY : MODEL_PHYSICS_RADIATION_TYPE

IMPLICIT NONE

TYPE :: FIELD_REGISTRY
  TYPE(GEOMETRY), POINTER :: GEOM => NULL()
  INTEGER(KIND=JPIM) :: NPROMA, NBLOCKS

CONTAINS
  PROCEDURE :: INIT => FIELD_REGISTRY_INIT
  PROCEDURE :: FINAL => FIELD_REGISTRY_FINAL

  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_2D_GMV, FIELD_REGISTRY_CREATE_VARIABLE_3RB_GMV
  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_GFL, FIELD_REGISTRY_CREATE_VARIABLE_ARRAY_GFL

  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_2RB
  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_WRAP_3RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_3RB
  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_WRAP_4RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_4RB

  PROCEDURE :: FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RD

  GENERIC   :: CREATE_VARIABLE => &
   & FIELD_REGISTRY_CREATE_VARIABLE_2D_GMV, FIELD_REGISTRY_CREATE_VARIABLE_3RB_GMV, &
   & FIELD_REGISTRY_CREATE_VARIABLE_GFL, FIELD_REGISTRY_CREATE_VARIABLE_ARRAY_GFL, &
   & FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_2RB, &
   & FIELD_REGISTRY_CREATE_VARIABLE_WRAP_3RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_3RB, &
   & FIELD_REGISTRY_CREATE_VARIABLE_WRAP_4RB, FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_4RB

  PROCEDURE :: CREATE_SURFACE_VARIABLE_2RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_2RB
  PROCEDURE :: CREATE_SURFACE_VARIABLE_ARRAY_2RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_2RB
  PROCEDURE :: CREATE_SURFACE_VARIABLE_ARRAY2_2RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_2RB
  PROCEDURE :: CREATE_SURFACE_VARIABLE_3RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_3RB
  PROCEDURE :: CREATE_SURFACE_VARIABLE_ARRAY_3RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_3RB
  PROCEDURE :: CREATE_SURFACE_VARIABLE_ARRAY2_3RB => FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_3RB
  PROCEDURE :: REGISTER_GEOMETRY => FIELD_REGISTRY_REGISTER_GEOMETRY
  PROCEDURE :: REGISTER_GMV_FIELDS => FIELD_REGISTRY_REGISTER_GMV_FIELDS
  PROCEDURE :: REGISTER_GFL_FIELDS => FIELD_REGISTRY_REGISTER_GFL_FIELDS
  PROCEDURE :: REGISTER_SURFACE_FIELDS => FIELD_REGISTRY_REGISTER_SURFACE_FIELDS
  PROCEDURE :: REGISTER_EC_PHYS_FIELDS => FIELD_REGISTRY_REGISTER_EC_PHYS_FIELDS
  PROCEDURE :: REGISTER_PHYSICS_RADIATION_FIELDS => FIELD_REGISTRY_REGISTER_PHYSICS_RADIATION_FIELDS

END TYPE FIELD_REGISTRY

CONTAINS

! FUNCTION CREATE_FIELD_EMPTY_2D(SHAPE) RESULT(FIELD_PTR)
!   ! Create an empty 2D field object with NULL data pointers
!   TYPE(FIELD_2D), POINTER :: FIELD_PTR
!   INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: SHAPE(1)

!   ALLOCATE(FIELD_PTR)
!   FIELD_PTR = FIELD_2D_EMPTY(SHAPE=SHAPE)
! END FUNCTION CREATE_FIELD_EMPTY_2D

! FUNCTION CREATE_FIELD_EMPTY_3D(SHAPE) RESULT(FIELD_PTR)
!   ! Create an empty 3D field object with NULL data pointers
!   TYPE(FIELD_3D), POINTER :: FIELD_PTR
!   INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: SHAPE(2)

!   ALLOCATE(FIELD_PTR)
!   FIELD_PTR = FIELD_3D_EMPTY(SHAPE=SHAPE)
! END FUNCTION CREATE_FIELD_EMPTY_3D

! FUNCTION CREATE_FIELD_EMPTY_4D(SHAPE) RESULT(FIELD_PTR)
!   ! Create an empty 4D field object with NULL data pointers
!   TYPE(FIELD_4D), POINTER :: FIELD_PTR
!   INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: SHAPE(3)

!   ALLOCATE(FIELD_PTR)
!   FIELD_PTR = FIELD_4D_EMPTY(SHAPE=SHAPE)
! END FUNCTION CREATE_FIELD_EMPTY_4D


  SUBROUTINE FIELD_REGISTRY_INIT(SELF, GEOM)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(GEOMETRY), TARGET, INTENT(IN) :: GEOM



END SUBROUTINE FIELD_REGISTRY_INIT

  SUBROUTINE FIELD_REGISTRY_FINAL(SELF)

CLASS(FIELD_REGISTRY) :: SELF

END SUBROUTINE FIELD_REGISTRY_FINAL


  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RB(SELF, NAME, DATA) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_2RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:)


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RD(SELF, NAME, DATA) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_2RD) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRD), TARGET, INTENT(IN) :: DATA(:,:)


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_2RD

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_3RB(SELF, NAME, DATA) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_3RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:)


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_3RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_4RB(SELF, NAME, DATA) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_4RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:,:)


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_4RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_2RB(SELF, NAME, DATA, IDX) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_2RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: IDX


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_2RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_3RB(SELF, NAME, DATA, IDX) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_3RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: IDX


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_3RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_4RB(SELF, NAME, DATA, IDX) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_4RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: DATA(:,:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: IDX


END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_WRAP_PACKED_4RB

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_2D_GMV(SELF, NAME, GMV, GMVT1, PT0, PT1, PT9, PPH9, PDL, PDM, &
&                                             PDL9, PDM9, PPC_PH, PERSISTENT) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_2RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: GMV(:,:,:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: GMVT1(:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: PT0, PT1, PT9, PPH9, PDL, PDM, PDL9, PDM9, PPC_PH
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT























END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_2D_GMV

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_3RB_GMV(SELF, NAME, GMV, GMVT1, PT0, PT1, PT9, PPH9, PDL, PDM, &
&                                             PDL9, PDM9, PPC_PH, PERSISTENT) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_3RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
REAL(KIND=JPRB), TARGET, INTENT(IN) :: GMV(:,:,:,:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: GMVT1(:,:,:,:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: PT0, PT1, PT9, PPH9, PDL, PDM, PDL9, PDM9, PPC_PH
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT























END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_3RB_GMV

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_GFL(SELF, NAME, YDCOMP, GFL, PERSISTENT) RESULT(VARIABLE)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_3RB) :: VARIABLE
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(TYPE_GFL_COMP), INTENT(IN) :: YDCOMP
TYPE(TGFL), TARGET, INTENT(INOUT) :: GFL
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT












END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_GFL

  FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_ARRAY_GFL(SELF, NAME, YDCOMP, GFL, PERSISTENT) RESULT(VARIABLES)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(VARIABLE_3RB), ALLOCATABLE :: VARIABLES(:)
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(TYPE_GFL_COMP), POINTER, INTENT(IN) :: YDCOMP(:)
TYPE(TGFL), TARGET, INTENT(INOUT) :: GFL
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT




END FUNCTION FIELD_REGISTRY_CREATE_VARIABLE_ARRAY_GFL

  SUBROUTINE FIELD_REGISTRY_REGISTER_GEOMETRY(SELF, VARIABLES, GEOM)




CLASS(FIELD_REGISTRY) :: SELF
TYPE(FIELD_VARIABLES), POINTER, INTENT(INOUT) :: VARIABLES
TYPE(GEOMETRY), INTENT(IN) :: GEOM




































END SUBROUTINE FIELD_REGISTRY_REGISTER_GEOMETRY

  SUBROUTINE FIELD_REGISTRY_REGISTER_GMV_FIELDS(SELF, VARIABLES, GMV)




CLASS(FIELD_REGISTRY) :: SELF
TYPE(FIELD_VARIABLES), POINTER, INTENT(INOUT) :: VARIABLES
TYPE(TGMV), INTENT(INOUT) :: GMV  


END SUBROUTINE FIELD_REGISTRY_REGISTER_GMV_FIELDS

  SUBROUTINE FIELD_REGISTRY_REGISTER_GFL_FIELDS(SELF, VARIABLES, GFL_ARRAY, GFL_META, YDMODEL)
USE TYPE_MODEL, ONLY : MODEL




CLASS(FIELD_REGISTRY) :: SELF
TYPE(FIELD_VARIABLES), POINTER, INTENT(INOUT) :: VARIABLES
TYPE(TGFL), INTENT(INOUT) :: GFL_ARRAY  
TYPE(TYPE_GFLD), INTENT(INOUT) :: GFL_META   
TYPE (MODEL), INTENT(IN) :: YDMODEL




















































































































































































































































END SUBROUTINE FIELD_REGISTRY_REGISTER_GFL_FIELDS

  SUBROUTINE FIELD_REGISTRY_REGISTER_EC_PHYS_FIELDS(SELF, VARIABLES, FIELDS)




CLASS(FIELD_REGISTRY) :: SELF
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: VARIABLES
TYPE(TEC_PHYS_FIELDS), INTENT(INOUT) :: FIELDS
 
 
 
 
  
END SUBROUTINE FIELD_REGISTRY_REGISTER_EC_PHYS_FIELDS

  SUBROUTINE FIELD_REGISTRY_REGISTER_PHYSICS_RADIATION_FIELDS(SELF, VARIABLES, PHYS_RADI)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: VARIABLES
TYPE(MODEL_PHYSICS_RADIATION_TYPE), TARGET, INTENT(IN) :: PHYS_RADI























END SUBROUTINE FIELD_REGISTRY_REGISTER_PHYSICS_RADIATION_FIELDS







  !----   Utility wrapper routines for surface variables   ----!

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_2RB(SELF, NAME, VARIABLE, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_2RB), INTENT(INOUT) :: VARIABLE
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:)
TYPE(TYPE_SURF_MTL_2D), INTENT(IN) :: META
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_2RB

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_2RB(SELF, NAME, VARIABLES, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_2RB), ALLOCATABLE, INTENT(INOUT) :: VARIABLES(:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:)
TYPE(TYPE_SURF_MTL_2D), INTENT(IN) :: META(:)
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT




END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_2RB

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_2RB(SELF, NAME, VARIABLES, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_2RB), ALLOCATABLE, INTENT(INOUT) :: VARIABLES(:,:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:)
TYPE(TYPE_SURF_MTL_2D), INTENT(IN) :: META(:,:)
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT




END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_2RB

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_3RB(SELF, NAME, VARIABLE, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_3RB), INTENT(INOUT) :: VARIABLE
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:,:)
TYPE(TYPE_SURF_MTL_3D), INTENT(IN) :: META
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_3RB

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_3RB(SELF, NAME, VARIABLES, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_3RB), ALLOCATABLE, INTENT(INOUT) :: VARIABLES(:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:,:)
TYPE(TYPE_SURF_MTL_3D), INTENT(IN) :: META(:)
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT




END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY_3RB

  SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_3RB(SELF, NAME, VARIABLES, ARRAY, META, DESCR, ACTIVE, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
CHARACTER(LEN=*), INTENT(IN) :: NAME
TYPE(VARIABLE_3RB), ALLOCATABLE, INTENT(INOUT) :: VARIABLES(:,:)
REAL(KIND=JPRB), TARGET, INTENT(IN) :: ARRAY(:,:,:,:)
TYPE(TYPE_SURF_MTL_3D), INTENT(IN) :: META(:,:)
TYPE(TYPE_SURF_GEN), INTENT(IN) :: DESCR
LOGICAL, INTENT(IN) :: ACTIVE
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT




END SUBROUTINE FIELD_REGISTRY_CREATE_SURFACE_VARIABLE_ARRAY2_3RB

  SUBROUTINE FIELD_REGISTRY_REGISTER_SURFACE_FIELDS(SELF, SURFVARS, YDSURF, PERSISTENT)

CLASS(FIELD_REGISTRY) :: SELF
TYPE(SURFACE_VARIABLES), POINTER, INTENT(INOUT) :: SURFVARS
TYPE(TSURF), TARGET, INTENT(INOUT) :: YDSURF
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
































END SUBROUTINE FIELD_REGISTRY_REGISTER_SURFACE_FIELDS

END MODULE FIELD_REGISTRY_MOD

