
MODULE FIELD_1RB_SHUFFLE_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE



INTERFACE PAIR_GATHER_DEVICE_DATA_RDONLY
END INTERFACE PAIR_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: PAIR_GATHER_DEVICE_DATA_RDONLY


INTERFACE PAIR_GATHER_DEVICE_DATA_RDWR
END INTERFACE PAIR_GATHER_DEVICE_DATA_RDWR

PUBLIC :: PAIR_GATHER_DEVICE_DATA_RDWR


INTERFACE PAIR_GATHER_HOST_DATA_RDONLY
END INTERFACE PAIR_GATHER_HOST_DATA_RDONLY

PUBLIC :: PAIR_GATHER_HOST_DATA_RDONLY


INTERFACE PAIR_GATHER_HOST_DATA_RDWR
END INTERFACE PAIR_GATHER_HOST_DATA_RDWR

PUBLIC :: PAIR_GATHER_HOST_DATA_RDWR


INTERFACE PAIR_SCATTER_DATA
END INTERFACE PAIR_SCATTER_DATA

PUBLIC :: PAIR_SCATTER_DATA


INTEGER (KIND=JPIM), PARAMETER :: NRDWR = 0, NRDONLY = 1, NHOST = 2, NDEVICE = 3
INTEGER (KIND=JPIM), PARAMETER :: NLONDIM = 1, NBLKDIM = 2

CONTAINS



END MODULE FIELD_1RB_SHUFFLE_MODULE
