
! Copyright 2011 ECMWF
!
! This software was developed at ECMWF for evaluation
! and may be used for academic and research purposes only.
! The software is provided as is without any warranty.
!
! This software can be used, copied and modified but not
! redistributed or sold. This notice must be reproduced
! on each copy made.
!

!> Handle state for the IFS model

MODULE FIELDS_MOD

USE PARKIND1,               ONLY : JPRB, JPIM
USE YOMLUN,                 ONLY : NULOUT, NULNAM
USE FIELDS_BASE_MOD,        ONLY : FIELDS_BASE, SPLIT_SPEC_GP
USE GEOMETRY_MOD,           ONLY : GEOMETRY,GEOMETRY_SAME
USE VARIABLES_MOD,          ONLY : VARIABLES, VARIABLES_CLONE ! , HAS_MODEL_FIELDS
USE TYPE_MODEL,             ONLY : MODEL
USE YOMGFL,                 ONLY : TGFL
USE YOMGMV,                 ONLY : TGMV
USE SURFACE_FIELDS_MIX,     ONLY : TSURF
USE EC_PHYS_FIELDS_MOD,     ONLY : TEC_PHYS_FIELDS
USE SPECTRAL_FIELDS_MOD,    ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE FIELD_CONTAINER_GP_MOD, ONLY : FIELD_CONTAINER_GP
USE FIELD_VARIABLES_MOD,    ONLY : FIELD_VARIABLES
USE SURFACE_VARIABLES_MOD,  ONLY : SURFACE_VARIABLES
USE FIELD_REGISTRY_MOD,     ONLY : FIELD_REGISTRY
USE YOMCFU,                 ONLY : TCFU
USE YOMXFU,                 ONLY : TXFU
USE YOMMCUF,                ONLY : TMCUF
USE FULLPOS,                ONLY : TFPOS
!
USE YEMLBC_FIELDS,          ONLY : TELBC_FIELDS

USE YOMCT0,                 ONLY : LECMWF

IMPLICIT NONE
PRIVATE

TYPE, PUBLIC,EXTENDS(FIELDS_BASE) :: FIELDS
  TYPE(TGMV)                   :: YRGMV
  TYPE(TGFL)                   :: YRGFL
  TYPE(TSURF)                  :: YRSURF
  TYPE(SPECTRAL_FIELD)         :: YRSPEC
  TYPE(TEC_PHYS_FIELDS)        :: YEC_PHYS_FIELDS
  TYPE(FIELD_CONTAINER_GP)     :: FIELD_T0
  TYPE(FIELD_CONTAINER_GP)     :: FIELD_T1
  TYPE(FIELD_CONTAINER_GP)     :: FIELD_T9
  TYPE(FIELD_CONTAINER_GP)     :: FIELD_PC
  TYPE(FIELD_CONTAINER_GP)     :: FIELD_PT
  REAL(KIND=JPRB), ALLOCATABLE :: YRGFLT5Q(:,:,:)

  !! physics related diagnostics
  TYPE(TCFU)              :: YRCFU !! cumulated flux activation
  TYPE(TXFU)              :: YRXFU !! instantaneous flux activation
  !! moved here from model_lam_coupling_mod.F90
  TYPE(TELBC_FIELDS), POINTER :: YRELBC_FIELDS=>NULL()
! Fullpos
  TYPE(TFPOS),ALLOCATABLE :: YFPOS
  !! Monitoring the Coupling-Update Frequency CUF
  TYPE(TMCUF)             :: YMCUF !! CUF

  ! Field registry for new object-based field management
  TYPE(FIELD_REGISTRY) :: REGISTRY

  ! Storage object hierarchy for core state and surface fields
  ! Note, these are large auto-generated derived types, so we
  ! attach them via pointers to avoid the nested type becoming
  ! too big for compilers to handle!
  TYPE(FIELD_VARIABLES), POINTER :: VARIABLES => NULL()
  TYPE(SURFACE_VARIABLES), POINTER :: SURFVARS => NULL()

CONTAINS

FINAL :: FIELDS_FINAL

END TYPE FIELDS

PUBLIC :: FIELDS_CREATE, FIELDS_DELETE, FIELDS_ZEROS,FIELDS_SET_MODEL,&
 & FIELDS_COPY, FIELDS_ADD, FIELDS_SUB, FIELDS_MUL, FIELDS_AXPY,&
 & FIELDS_DOT_PROD, FIELDS_SCHUR_PROD, FIELDS_ADD_INCR, FIELDS_DIFF_INCR,&
 & FIELDS_RANDOM, FIELDS_CHANGE_RESOL, FIELDS_GPNORM,FIELDS_CONTAIN,&
 & FIELDS_FORCE_WITH, FIELDS_STORE_GFL_Q, FIELDS_LIMIT_Q, FIELDS_LIMIT_GO3

! ------------------------------------------------------------------------------

CONTAINS

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_CREATE(SELF, GEOM, YDMODEL, VARS, YDCFUPP, YDXFUPP, KPPVCLIX, KPPEDR)
USE PARKIND1           , ONLY : JPRB, JPIM
USE TYPE_MODEL         , ONLY : MODEL
USE YOMMP0             , ONLY : LOUTPUT
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE SPECTRAL_FIELDS_MOD, ONLY : ALLOCATE_SPEC
USE YOMCFU             , ONLY : TCFU_KEYS
USE YOMXFU             , ONLY : TXFU_KEYS
IMPLICIT NONE

TYPE(FIELDS)   ,         INTENT(INOUT) :: SELF
TYPE(GEOMETRY) , TARGET, INTENT(IN)    :: GEOM
TYPE(MODEL)    , TARGET, INTENT(INOUT) :: YDMODEL
TYPE(VARIABLES),         INTENT(IN)    :: VARS
TYPE(TCFU_KEYS),OPTIONAL,INTENT(IN)    :: YDCFUPP
TYPE(TXFU_KEYS),OPTIONAL,INTENT(IN)    :: YDXFUPP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KPPVCLIX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KPPEDR

INTEGER(KIND=JPIM), ALLOCATABLE :: IGRIB(:)
LOGICAL,SAVE :: LLFIRST=.TRUE.
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

INTEGER(KIND=JPIM) :: IUNIT,IOS
LOGICAL :: LL_OPEN, LL_NAMOPEN

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CREATE',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CREATE',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_CREATE

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_DELETE(SELF)

!     21-Jun-2022 R. El Khatib bugfix : add missing nullifications %VARIABLES and %SURFVARS
!     08-Aug-2023 R. El Khatib bugfix : add missing deallocation of TYPE_[CX]FU

USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE SURFACE_FIELDS_MIX , ONLY : DEALLO_SURF
USE SPECTRAL_FIELDS_MOD, ONLY: DEALLOCATE_SPEC
IMPLICIT NONE

TYPE(FIELDS), INTENT(INOUT) :: SELF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DELETE',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DELETE',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_DELETE

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_ZEROS(SELF)
USE PARKIND1          , ONLY : JPRB
USE YOMHOOK           , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL            , ONLY : ZERO_YOMGFL
USE YOMGMV            , ONLY : ZERO_YOMGMV
USE SURFACE_FIELDS_MIX, ONLY : ZERO_SURF
USE YOMMCUF           , ONLY : ZERO_MCUF
IMPLICIT NONE

TYPE(FIELDS), INTENT(INOUT) :: SELF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ZEROS',0,ZHOOK_HANDLE)

CALL ZERO_YOMGMV(SELF%YRGMV)
CALL ZERO_YOMGFL(SELF%YRGFL)
CALL ZERO_SURF(SELF%YRSURF)
CALL ZERO_MCUF(SELF%YMCUF)
SELF%YRSPEC = 0.0_JPRB
CALL SELF%YEC_PHYS_FIELDS%ZERO()

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ZEROS',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_ZEROS

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_COPY(SELF,RHS)
USE PARKIND1          , ONLY : JPRB
USE YOMHOOK           , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL            , ONLY : COPY_YOMGFL
USE YOMGMV            , ONLY : COPY_YOMGMV
USE SURFACE_FIELDS_MIX, ONLY : COPY_SURF
USE TYPE_FLUXES       , ONLY : COPY_FLUX
USE YOMMCUF           , ONLY : COPY_MCUF
USE YOMCT0            , ONLY : LECMWF

IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
TYPE(FIELDS)    , INTENT(IN)    :: RHS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_COPY',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_COPY'

CALL COPY_YOMGMV(SELF%YRGMV,RHS%YRGMV)
CALL COPY_YOMGFL(SELF%YRGFL,RHS%YRGFL)
CALL COPY_SURF(SELF%YRSURF,RHS%YRSURF)
CALL COPY_FLUX(SELF%YRCFU%CFUBUF_B,RHS%YRCFU%CFUBUF_B)
CALL COPY_FLUX(SELF%YRXFU%XFUBUF_B,RHS%YRXFU%XFUBUF_B)
CALL COPY_MCUF(SELF%YMCUF,RHS%YMCUF)
!SELF%YRSPEC = RHS%YRSPEC
! Copy arrays to be safe
SELF%YRSPEC%SP2D = RHS%YRSPEC%SP2D
SELF%YRSPEC%SP3D = RHS%YRSPEC%SP3D

! Copy the model-related pointers as well
SELF%YRGFL%YGFL => RHS%YRGFL%YGFL
SELF%STATE_MODEL => RHS%STATE_MODEL

IF ((SELF%STATE_MODEL%YRML_PHY_EC%YREPHY%LEPHYS).OR.(.NOT. LECMWF .AND. SELF%STATE_MODEL%YRML_PHY_EC%YREPHY%LEMWAVE)) &
  & CALL SELF%YEC_PHYS_FIELDS%COPY(RHS%YEC_PHYS_FIELDS)

!IF ((SELF%STATE_MODEL%YRML_PHY_EC%YREPHY%LEPHYS) .OR. & 
!   & (.NOT. LECMWF .AND. YDMODEL%YRML_PHY_EC%YREPHY%LEMWAVE)) CALL SELF%YEC_PHYS_FIELDS%COPY(RHS%YEC_PHYS_FIELDS)
!
IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_COPY',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_COPY

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_SET_MODEL(SELF,YDMODEL)
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE
TYPE(FIELDS),         INTENT(INOUT) :: SELF
TYPE(MODEL) , TARGET, INTENT(IN)    :: YDMODEL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!! point the YGFL pointer in self%yrgfl to that in the model passed in
IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SET_MODEL',0,ZHOOK_HANDLE)
SELF%YRGFL%YGFL => YDMODEL%YRML_GCONF%YGFL
!! point the model pointer in self to the model passed in
SELF%STATE_MODEL => YDMODEL
IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SET_MODEL',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_SET_MODEL

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_ADD(SELF,RHS)
USE PARKIND1, ONLY : JPRB
USE YOMGFL,   ONLY : AXPBY_YOMGFL
USE YOMGMV,   ONLY : AXPBY_YOMGMV
USE SURFACE_FIELDS_MIX, ONLY : ADD_SURF
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
TYPE(FIELDS)    , INTENT(IN)    :: RHS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ADD',0,ZHOOK_HANDLE)

WRITE(NULOUT,*) 'CALLING FIELDS_ADD'

CALL AXPBY_YOMGMV(SELF%YRGMV,1.0_JPRB,RHS%YRGMV,1.0_JPRB)
CALL AXPBY_YOMGFL(SELF%YRGFL,1.0_JPRB,RHS%YRGFL,1.0_JPRB)
CALL ADD_SURF(SELF%YRSURF,RHS%YRSURF)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ADD',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_ADD

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_SUB(SELF,RHS)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL  , ONLY : AXPBY_YOMGFL,DIFF_YOMGFL
USE YOMGMV  , ONLY : AXPBY_YOMGMV,DIFF_YOMGMV
USE SURFACE_FIELDS_MIX, ONLY : AXPBY_SURF
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
TYPE(FIELDS)    , INTENT(IN)    :: RHS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SUB',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_SUB'

!!CALL AXPBY_YOMGMV(SELF%YRGMV,1.0_JPRB,RHS%YRGMV,-1.0_JPRB)
!!CALL AXPBY_YOMGFL(SELF%YRGFL,1.0_JPRB,RHS%YRGFL,-1.0_JPRB)

!! slightly cheaper than calling axpby
CALL DIFF_YOMGMV(SELF%YRGMV,RHS%YRGMV)
CALL DIFF_YOMGFL(SELF%YRGFL,RHS%YRGFL)
CALL AXPBY_SURF(SELF%YRSURF,1.0_JPRB,RHS%YRSURF,-1.0_JPRB)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SUB',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_SUB

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_MUL(SELF,PZ)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL,   ONLY : MUL_YOMGFL
USE YOMGMV,   ONLY : MUL_YOMGMV
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
REAL(KIND=JPRB) , INTENT(IN)    :: PZ
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_MUL',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_MUL'

CALL MUL_YOMGMV(SELF%YRGMV,PZ)
CALL MUL_YOMGFL(SELF%YRGFL,PZ)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_MUL',1,ZHOOK_HANDLE)
END SUBROUTINE FIELDS_MUL

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_AXPY(SELF,PZ,RHS)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL,   ONLY : AXPBY_YOMGFL
USE YOMGMV,   ONLY : AXPBY_YOMGMV
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
REAL(KIND=JPRB) , INTENT(IN)    :: PZ
TYPE(FIELDS)    , INTENT(IN)    :: RHS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_AXPY',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_AXPY'

CALL AXPBY_YOMGMV(SELF%YRGMV,1.0_JPRB,RHS%YRGMV,PZ)
CALL AXPBY_YOMGFL(SELF%YRGFL,1.0_JPRB,RHS%YRGFL,PZ)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_AXPY',1,ZHOOK_HANDLE)
END SUBROUTINE FIELDS_AXPY

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_DOT_PROD(FLD1,FLD2,PPROD)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL,   ONLY : DOT_PROD_YOMGFL
USE YOMGMV,   ONLY : DOT_PROD_YOMGMV
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(IN)    :: FLD1, FLD2
REAL(KIND=JPRB) , INTENT(OUT)   :: PPROD

REAL(KIND=JPRB) :: ZTMP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DOT_PROD',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_DOT_PROD'

IF (.NOT. ASSOCIATED(FLD1%GEOM,FLD2%GEOM)) THEN
  CALL ABOR1("FIELDS_MOD:FIELDS_DOT_PRODUCT Different geometries")
ENDIF

PPROD = 0.0_JPRB
CALL DOT_PROD_YOMGMV(FLD1%GEOM,FLD1%YRGMV,FLD2%YRGMV,ZTMP)
PPROD = PPROD + ZTMP
CALL DOT_PROD_YOMGFL(FLD1%GEOM,FLD1%YRGFL,FLD2%YRGFL,ZTMP)
PPROD = PPROD + ZTMP

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DOT_PROD',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_DOT_PROD

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_SCHUR_PROD(FLD1, FLD2)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

TYPE(FIELDS), INTENT(INOUT) :: FLD1
TYPE(FIELDS), INTENT(IN)    :: FLD2

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SCHUR_PROD',0,ZHOOK_HANDLE)

CALL ABOR1("FIELDS_MOD: Schur product not implemented")
!CALL SCHUR_PROD_YOMGMV(FLD1%YRGMV,FLD2%YRGMV)
!CALL SCHUR_PROD_YOMGFL(FLD1%YRGFL,FLD2%YRGFL)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_SCHUR_PROD',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_SCHUR_PROD

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_ADD_INCR(SELF,RHS)
USE PARKIND1, ONLY : JPRB
USE YOMGFL,   ONLY : AXPBY_YOMGFL
USE YOMGMV,   ONLY : AXPBY_YOMGMV
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
TYPE(FIELDS)    , INTENT(IN)    :: RHS
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ADD_INCR',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_ADD_INCR'

!CALL FIELDS_GPNORM(SELF,'FIELDS_ADD_INCR: First Guess')
!CALL FIELDS_GPNORM(RHS,'FIELDS_ADD_INCR: Increment')

! Currently identical to fields_add
CALL AXPBY_YOMGMV(SELF%YRGMV,1.0_JPRB,RHS%YRGMV,1.0_JPRB)
CALL AXPBY_YOMGFL(SELF%YRGFL,1.0_JPRB,RHS%YRGFL,1.0_JPRB)

!CALL FIELDS_GPNORM(SELF,'FIELDS_ADD_INCR: Analysis')

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_ADD_INCR',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_ADD_INCR

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_DIFF_INCR(LHS,X1,X2)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: LHS
TYPE(FIELDS)    , INTENT(IN)    :: X1
TYPE(FIELDS)    , INTENT(IN)    :: X2
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DIFF_INCR',0,ZHOOK_HANDLE)
WRITE(NULOUT,*) 'CALLING FIELDS_DIFF_INCR'

! Currently identical to a 3-argument fields_sub
CALL FIELDS_COPY(LHS,X1)
CALL FIELDS_SUB(LHS,X2)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_DIFF_INCR',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_DIFF_INCR

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_RANDOM(SELF)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMGFL,   ONLY : RANDOM_YOMGFL
USE YOMGMV,   ONLY : RANDOM_YOMGMV
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_RANDOM',0,ZHOOK_HANDLE)

CALL RANDOM_YOMGMV(SELF%YRGMV)
CALL RANDOM_YOMGFL(SELF%YRGFL)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_RANDOM',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_RANDOM

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_CHANGE_RESOL(SELF,RHS)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT3,  ONLY : NSTEP
USE FIELD_CONTAINER_OPER_MOD
USE FIELD_DEFINITIONS, ONLY : FID
IMPLICIT NONE

TYPE(FIELDS)    , INTENT(INOUT) :: SELF
TYPE(FIELDS)    , INTENT(INOUT) :: RHS

LOGICAL :: LLSAME_RESOL
INTEGER, PARAMETER :: NINTERPSURF = 0 ! Nearest neighbour interpolation
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_SPEC(:),IACTIVE(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CHANGE_RESOL',0,ZHOOK_HANDLE)
LLSAME_RESOL = GEOMETRY_SAME(SELF%GEOM,RHS%GEOM)
WRITE(NULOUT,*) 'FIELDS_CHANGE_RESOL CALLED ', LLSAME_RESOL,SELF%GEOM%YRGEM%NGPTOTG,RHS%GEOM%YRGEM%NGPTOTG,NSTEP
CALL FLUSH(NULOUT)

!  Single level surface fields (stored as 2d fields in the field container)
! are interpolated using nearest neighbour method as for some of these fields 
! this is the only sensible approach available. When changing resolution 
! ALL the surface fields are interpolated.

SELF%YRSPEC = RHS%YRSPEC ! Assignement does also truncation/zero-filling
IF(LLSAME_RESOL) THEN
  CALL SELF%FIELD%FIELD_COPY(RHS%FIELD)
ELSE
  ALLOCATE(IFIDS_SPEC(4))
  IFIDS_SPEC=(/FID%U,FID%V,FID%T,FID%SP/)
  IF (SELF%GEOM%YRDIM%NSMAX < RHS%GEOM%YRDIM%NSMAX) THEN
    CALL FIELD_CONTAINER_INTERP(RHS%GEOM,SELF%GEOM,RHS%FIELD,SELF%FIELD, &
      &                         KFIDS_SPEC=IFIDS_SPEC,PSPSP=RHS%YRSPEC%SP, &
      &                         KINTERPSURF=NINTERPSURF)
  ELSE
   CALL FIELD_CONTAINER_INTERP(RHS%GEOM,SELF%GEOM,RHS%FIELD,SELF%FIELD, &
      &                        KFIDS_SPEC=IFIDS_SPEC, &
      &                        KINTERPSURF=NINTERPSURF)
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CHANGE_RESOL',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_CHANGE_RESOL
! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_FORCE_WITH(SELF,RHS,KFIDS)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0,  ONLY : NINTERPTRAJ, LECMWF
USE YOMCT3,  ONLY : NSTEP
USE FIELD_CONTAINER_OPER_MOD
USE FIELD_DEFINITIONS, ONLY : FID
IMPLICIT NONE

TYPE(FIELDS)      , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: RHS
INTEGER(KIND=JPIM), INTENT(IN)    :: KFIDS(:)

LOGICAL :: LLSAME_RESOL
INTEGER(KIND=JPIM),ALLOCATABLE :: IFIDS_GP(:),IFIDS_SPEC(:),IACTIVE(:),IFIDS_CLIM(:),IFIDS_SNOW(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_FORCE_WITH',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_FORCE_WITH',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_FORCE_WITH

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_GPNORM(SELF,CDGREP)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

TYPE(FIELDS)    , INTENT(IN)    :: SELF
CHARACTER(LEN=*), INTENT(IN)    :: CDGREP

REAL(KIND=JPRB) :: ZSPNORMS(3,1), ZGMVNORMS(3,SELF%GEOM%YRDIMV%NFLEVG), ZGFLNORMS(3,SELF%GEOM%YRDIMV%NFLEVG)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_GPNORM',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_GPNORM',1,ZHOOK_HANDLE)
END SUBROUTINE FIELDS_GPNORM

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_CONTAIN(SELF,YDGEOMETRY,YDMODEL)
USE PARKIND1, ONLY : JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK
USE TYPE_MODEL, ONLY : MODEL
USE YOMMP0   , ONLY : NPRINTLEV
USE FIELD_DEFINITIONS_BASE, ONLY : JP_T0, JP_T9, JP_T1, JP_PC, JP_PT
USE FIELD_DEFINITIONS, ONLY : MAIN_FIELD_METADATA
IMPLICIT NONE
TYPE(FIELDS), TARGET, INTENT(INOUT) :: SELF
TYPE(GEOMETRY),       INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL)         , INTENT(IN)    :: YDMODEL
INTEGER(KIND=JPIM),ALLOCATABLE :: IACTIVE(:)
INTEGER(KIND=JPIM) :: JID
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CONTAIN',0,ZHOOK_HANDLE)

ASSOCIATE(FIELD_T1=>SELF%FIELD_T1,FIELD_T0=>SELF%FIELD_T0,FIELD_T9=>SELF%FIELD_T9,FIELD_PC=>SELF%FIELD_PC,FIELD_PT=>SELF%FIELD_PT,&
 & YDGFL=>SELF%YRGFL,YDGMV=>SELF%YRGMV, YDSURF=>SELF%YRSURF,YDGEM=>YDGEOMETRY%YRGEM,YDDIMV=>YDGEOMETRY%YRDIMV,&
 & YDDIM=>YDGEOMETRY%YRDIM,YGFL=>SELF%YRGFL%YGFL,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY,YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY)
ASSOCIATE(NGPTOT=>YDGEM%NGPTOT,NFLEVG=>YDDIMV%NFLEVG,NPROMA=>YDDIM%NPROMA,LEPHYS=>YDEPHY%LEPHYS,LMPHYS=>YDPHY%LMPHYS,&
 & NCHEM_FLXO=>YGFL%NCHEM_FLXO,NCHEM_DV=>YGFL%NCHEM_DV,NEMIS2D=>YGFL%NEMIS2D, NEMIS2DAUX=>YGFL%NEMIS2DAUX, &
 & NCHEM_WDFLX=>YGFL%NCHEM_WDFLX,NCHEM_DDFLX=>YGFL%NCHEM_DDFLX, &
 & NGFL_EXT=>YGFL%NGFL_EXT,NGFL_EZDIAG=>YGFL%NGFL_EZDIAG)


CALL FIELD_T1%FIELD_CREATE(MAIN_FIELD_METADATA,  NGPTOT, &
 & (/ NFLEVG,NFLEVG+1,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_OMD%NLEVS,NCHEM_FLXO,NCHEM_WDFLX,NCHEM_DDFLX,NCHEM_DV,NEMIS2D,NEMIS2DAUX/), &
 & NPROMA, KATTACH=JP_T1, &
 & YDGMV=YDGMV,YDGFL=YDGFL,YDSURF=YDSURF,LD_ATTACH_GFL_NPROMA_FIXED=.TRUE.)

CALL FIELD_T0%FIELD_CREATE(MAIN_FIELD_METADATA,  NGPTOT, &
 & (/ NFLEVG,NFLEVG+1,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_OMD%NLEVS,NCHEM_FLXO,NCHEM_WDFLX,NCHEM_DDFLX,NCHEM_DV,NEMIS2D,NEMIS2DAUX/), &
 & NPROMA, KATTACH=JP_T0, &
 & YDGMV=YDGMV,YDGFL=YDGFL,YDSURF=YDSURF,LD_ATTACH_GFL_NPROMA_FIXED=.TRUE.,LDHDERS=.TRUE.,KDIM3S=(/NGFL_EXT,NGFL_EZDIAG/))

CALL FIELD_T9%FIELD_CREATE(MAIN_FIELD_METADATA,  NGPTOT, &
 & (/ NFLEVG,NFLEVG+1,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_OMD%NLEVS,NCHEM_FLXO,NCHEM_WDFLX,NCHEM_DDFLX,NCHEM_DV,NEMIS2D,NEMIS2DAUX/), &
 & NPROMA, KATTACH=JP_T9, &
 & YDGMV=YDGMV,YDGFL=YDGFL,YDSURF=YDSURF,LD_ATTACH_GFL_NPROMA_FIXED=.TRUE., LDHDERS=.TRUE.)

IF(YDMODEL%YRML_DYN%YRDYNA%LPC_FULL .AND. .NOT. YDMODEL%YRML_DYN%YRDYNA%LTWOTL) THEN
  CALL FIELD_PC%FIELD_CREATE(MAIN_FIELD_METADATA,  NGPTOT, &
   & (/ NFLEVG,NFLEVG+1,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_OMD%NLEVS,NCHEM_FLXO,NCHEM_WDFLX,NCHEM_DDFLX,NCHEM_DV,NEMIS2D,NEMIS2DAUX/), &
   & NPROMA, KATTACH=JP_PC, &
   & YDGMV=YDGMV,YDGFL=YDGFL,YDSURF=YDSURF,LD_ATTACH_GFL_NPROMA_FIXED=.TRUE.,LDHDERS=.FALSE.)
ENDIF
IF(YDMODEL%YRML_DYN%YRDYNA%LPC_FULL.AND.YDMODEL%YRML_DYN%YRDYNA%LSLAG.AND.(LEPHYS.OR.LMPHYS)) THEN
  CALL FIELD_PT%FIELD_CREATE(MAIN_FIELD_METADATA,  NGPTOT, &
  & (/ NFLEVG,NFLEVG+1,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_OMD%NLEVS,NCHEM_FLXO,NCHEM_WDFLX,NCHEM_DDFLX,NCHEM_DV,NEMIS2D,NEMIS2DAUX/), &
  & NPROMA, KATTACH=JP_PT, &
  & YDGMV=YDGMV,YDGFL=YDGFL,YDSURF=YDSURF,LD_ATTACH_GFL_NPROMA_FIXED=.TRUE., LDHDERS=.FALSE.)
ENDIF

CALL FIELD_T0%GET_ACTIVE_FIELDS(IACTIVE)
IF (NPRINTLEV > 1) THEN
  DO JID=1,SIZE(IACTIVE)
    WRITE(NULOUT,*) 'ACTIVE FIELD ',JID,IACTIVE(JID)
  ENDDO
ENDIF

SELF%FIELD => SELF%FIELD_T0

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FIELDS_MOD:FIELDS_CONTAIN',1,ZHOOK_HANDLE)

END SUBROUTINE FIELDS_CONTAIN

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_STORE_GFL_Q(SELF)
IMPLICIT NONE
TYPE(FIELDS), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: JGFL,JSTGLO,ICEND,IBL

ASSOCIATE(YDDIM=>SELF%GEOM%YRDIM,&
 & YDDIMV=>SELF%GEOM%YRDIMV, &
 & YDGEM=>SELF%GEOM%YRGEM, &
 & YDGFL=>SELF%YRGFL, &
 & YGFL=>SELF%STATE_MODEL%YRML_GCONF%YGFL )
ASSOCIATE(YQ=>YGFL%YQ, &
 & GFL=>YDGFL%GFL, &
 & NGPBLKS=>YDDIM%NGPBLKS, &
 & NPROMA=>YDDIM%NPROMA, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NGPTOT=>YDGEM%NGPTOT)
!
IF (ALLOCATED(SELF%YRGFLT5Q)) DEALLOCATE(SELF%YRGFLT5Q)
ALLOCATE(SELF%YRGFLT5Q(NPROMA,NFLEVG,NGPBLKS))

! Store the first guess q field
DO JSTGLO=1,NGPTOT,NPROMA
  ICEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
  IBL=(JSTGLO-1)/NPROMA+1
  SELF%YRGFLT5Q(1:ICEND,1:NFLEVG,IBL)=GFL(1:ICEND,1:NFLEVG,YQ%MP,IBL)
ENDDO

END ASSOCIATE
END ASSOCIATE

END SUBROUTINE FIELDS_STORE_GFL_Q

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_LIMIT_Q(SELF)
IMPLICIT NONE
TYPE(FIELDS), INTENT(INOUT) :: SELF


END SUBROUTINE FIELDS_LIMIT_Q

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_LIMIT_GO3(SELF)
IMPLICIT NONE
TYPE(FIELDS), INTENT(INOUT) :: SELF
INTEGER(KIND=JPIM) :: JGFL, JSTGLO, ICEND, IBL

ASSOCIATE(YDDIM=>SELF%GEOM%YRDIM, &
 &        YDDIMV=>SELF%GEOM%YRDIMV, &
 &        YDGEM=>SELF%GEOM%YRGEM, &
 &        YDGFL=>SELF%YRGFL, &
 &        YGFL=>SELF%STATE_MODEL%YRML_GCONF%YGFL)
ASSOCIATE(NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, &
 &        NFLEVG=>YDDIMV%NFLEVG, NGPTOT=>YDGEM%NGPTOT, &
 &        GFL=>YDGFL%GFL, &
 &        NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP)
!
! Zero GEMS ozone (GO3) increments in the top model levels

DO JGFL=1,NUMFLDS
  IF(YCOMP(JGFL)%LGP .AND. YCOMP(JGFL)%IGRBCODE == 210203) THEN
    WRITE(NULOUT,*) ' FIELDS:FIELDS_LIMIT_GO3: CALLED'
    DO JSTGLO=1,NGPTOT,NPROMA
      ICEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
      IBL=(JSTGLO-1)/NPROMA+1
      IF (NFLEVG < 137 ) THEN
        GFL(1:ICEND,1:5,YCOMP(JGFL)%MP,IBL)= 0.0_JPRB
      ELSE
        GFL(1:ICEND,1:15,YCOMP(JGFL)%MP,IBL)= 0.0_JPRB
      ENDIF
    ENDDO
  ENDIF
ENDDO

END ASSOCIATE
END ASSOCIATE

END SUBROUTINE FIELDS_LIMIT_GO3

! ------------------------------------------------------------------------------

SUBROUTINE FIELDS_FINAL(THIS)
  TYPE(FIELDS) :: THIS
  ! If we don't add this, we may get a internal compiler error
END SUBROUTINE FIELDS_FINAL

! ------------------------------------------------------------------------------

END MODULE FIELDS_MOD
