
MODULE FIELD_ARRAY_MODULE


USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

TYPE FIELD_2RM_ARRAY
  CLASS (FIELD_2RM), POINTER :: F_P => NULL ()
  REAL(KIND=JPRM), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_2RM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2RM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2RM_ARRAY
END TYPE

PUBLIC :: FIELD_2RM_ARRAY

TYPE FIELD_3RM_ARRAY
  CLASS (FIELD_3RM), POINTER :: F_P => NULL ()
  REAL(KIND=JPRM), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_3RM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_3RM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_3RM_ARRAY
END TYPE

PUBLIC :: FIELD_3RM_ARRAY

TYPE FIELD_4RM_ARRAY
  CLASS (FIELD_4RM), POINTER :: F_P => NULL ()
  REAL(KIND=JPRM), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_4RM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_4RM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_4RM_ARRAY
END TYPE

PUBLIC :: FIELD_4RM_ARRAY

TYPE FIELD_5RM_ARRAY
  CLASS (FIELD_5RM), POINTER :: F_P => NULL ()
  REAL(KIND=JPRM), POINTER :: P (:,:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_5RM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_5RM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_5RM_ARRAY
END TYPE

PUBLIC :: FIELD_5RM_ARRAY

TYPE FIELD_2RB_ARRAY
  CLASS (FIELD_2RB), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_2RB_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2RB_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2RB_ARRAY
END TYPE

PUBLIC :: FIELD_2RB_ARRAY

TYPE FIELD_3RB_ARRAY
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_3RB_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_3RB_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_3RB_ARRAY
END TYPE

PUBLIC :: FIELD_3RB_ARRAY

TYPE FIELD_4RB_ARRAY
  CLASS (FIELD_4RB), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_4RB_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_4RB_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_4RB_ARRAY
END TYPE

PUBLIC :: FIELD_4RB_ARRAY

TYPE FIELD_5RB_ARRAY
  CLASS (FIELD_5RB), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:,:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_5RB_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_5RB_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_5RB_ARRAY
END TYPE

PUBLIC :: FIELD_5RB_ARRAY

TYPE FIELD_2RD_ARRAY
  CLASS (FIELD_2RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_2RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2RD_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2RD_ARRAY
END TYPE

PUBLIC :: FIELD_2RD_ARRAY

TYPE FIELD_3RD_ARRAY
  CLASS (FIELD_3RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_3RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_3RD_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_3RD_ARRAY
END TYPE

PUBLIC :: FIELD_3RD_ARRAY

TYPE FIELD_4RD_ARRAY
  CLASS (FIELD_4RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_4RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_4RD_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_4RD_ARRAY
END TYPE

PUBLIC :: FIELD_4RD_ARRAY

TYPE FIELD_5RD_ARRAY
  CLASS (FIELD_5RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER :: P (:,:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_5RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_5RD_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_5RD_ARRAY
END TYPE

PUBLIC :: FIELD_5RD_ARRAY

TYPE FIELD_2IM_ARRAY
  CLASS (FIELD_2IM), POINTER :: F_P => NULL ()
  INTEGER(KIND=JPIM), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_2IM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2IM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2IM_ARRAY
END TYPE

PUBLIC :: FIELD_2IM_ARRAY

TYPE FIELD_3IM_ARRAY
  CLASS (FIELD_3IM), POINTER :: F_P => NULL ()
  INTEGER(KIND=JPIM), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_3IM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_3IM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_3IM_ARRAY
END TYPE

PUBLIC :: FIELD_3IM_ARRAY

TYPE FIELD_4IM_ARRAY
  CLASS (FIELD_4IM), POINTER :: F_P => NULL ()
  INTEGER(KIND=JPIM), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_4IM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_4IM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_4IM_ARRAY
END TYPE

PUBLIC :: FIELD_4IM_ARRAY

TYPE FIELD_5IM_ARRAY
  CLASS (FIELD_5IM), POINTER :: F_P => NULL ()
  INTEGER(KIND=JPIM), POINTER :: P (:,:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_5IM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_5IM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_5IM_ARRAY
END TYPE

PUBLIC :: FIELD_5IM_ARRAY

TYPE FIELD_2LM_ARRAY
  CLASS (FIELD_2LM), POINTER :: F_P => NULL ()
  LOGICAL(KIND=JPLM), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_2LM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2LM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2LM_ARRAY
END TYPE

PUBLIC :: FIELD_2LM_ARRAY

TYPE FIELD_3LM_ARRAY
  CLASS (FIELD_3LM), POINTER :: F_P => NULL ()
  LOGICAL(KIND=JPLM), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_3LM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_3LM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_3LM_ARRAY
END TYPE

PUBLIC :: FIELD_3LM_ARRAY

TYPE FIELD_4LM_ARRAY
  CLASS (FIELD_4LM), POINTER :: F_P => NULL ()
  LOGICAL(KIND=JPLM), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_4LM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_4LM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_4LM_ARRAY
END TYPE

PUBLIC :: FIELD_4LM_ARRAY

TYPE FIELD_5LM_ARRAY
  CLASS (FIELD_5LM), POINTER :: F_P => NULL ()
  LOGICAL(KIND=JPLM), POINTER :: P (:,:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_FIELD_5LM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_5LM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_5LM_ARRAY
END TYPE

PUBLIC :: FIELD_5LM_ARRAY


CONTAINS

SUBROUTINE INIT_FIELD_2RM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_2RM_ARRAY) :: SELF
REAL(KIND=JPRM), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2RM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2RM_ARRAY (SELF)
CLASS (FIELD_2RM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_3RM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_3RM_ARRAY) :: SELF
REAL(KIND=JPRM), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_3RM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_3RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_3RM_ARRAY (SELF)
CLASS (FIELD_3RM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_4RM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_4RM_ARRAY) :: SELF
REAL(KIND=JPRM), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_4RM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_4RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_4RM_ARRAY (SELF)
CLASS (FIELD_4RM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_5RM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_5RM_ARRAY) :: SELF
REAL(KIND=JPRM), INTENT (IN), TARGET :: P (:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_5RM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_5RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_5RM_ARRAY (SELF)
CLASS (FIELD_5RM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_2RB_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_2RB_ARRAY) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2RB_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2RB_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2RB_ARRAY (SELF)
CLASS (FIELD_2RB_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_3RB_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_3RB_ARRAY) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_3RB_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_3RB_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_3RB_ARRAY (SELF)
CLASS (FIELD_3RB_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_4RB_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_4RB_ARRAY) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_4RB_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_4RB_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_4RB_ARRAY (SELF)
CLASS (FIELD_4RB_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_5RB_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_5RB_ARRAY) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_5RB_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_5RB_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_5RB_ARRAY (SELF)
CLASS (FIELD_5RB_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_2RD_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_2RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2RD_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2RD_ARRAY (SELF)
CLASS (FIELD_2RD_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_3RD_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_3RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_3RD_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_3RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_3RD_ARRAY (SELF)
CLASS (FIELD_3RD_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_4RD_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_4RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_4RD_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_4RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_4RD_ARRAY (SELF)
CLASS (FIELD_4RD_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_5RD_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_5RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_5RD_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_5RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_5RD_ARRAY (SELF)
CLASS (FIELD_5RD_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_2IM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_2IM_ARRAY) :: SELF
INTEGER(KIND=JPIM), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2IM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2IM_ARRAY (SELF)
CLASS (FIELD_2IM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_3IM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_3IM_ARRAY) :: SELF
INTEGER(KIND=JPIM), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_3IM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_3IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_3IM_ARRAY (SELF)
CLASS (FIELD_3IM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_4IM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_4IM_ARRAY) :: SELF
INTEGER(KIND=JPIM), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_4IM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_4IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_4IM_ARRAY (SELF)
CLASS (FIELD_4IM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_5IM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_5IM_ARRAY) :: SELF
INTEGER(KIND=JPIM), INTENT (IN), TARGET :: P (:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_5IM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_5IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_5IM_ARRAY (SELF)
CLASS (FIELD_5IM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_2LM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_2LM_ARRAY) :: SELF
LOGICAL(KIND=JPLM), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2LM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2LM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2LM_ARRAY (SELF)
CLASS (FIELD_2LM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_3LM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_3LM_ARRAY) :: SELF
LOGICAL(KIND=JPLM), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_3LM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_3LM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_3LM_ARRAY (SELF)
CLASS (FIELD_3LM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_4LM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_4LM_ARRAY) :: SELF
LOGICAL(KIND=JPLM), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_4LM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_4LM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_4LM_ARRAY (SELF)
CLASS (FIELD_4LM_ARRAY) :: SELF

END SUBROUTINE

SUBROUTINE INIT_FIELD_5LM_ARRAY (SELF, P, LBOUNDS)
CLASS (FIELD_5LM_ARRAY) :: SELF
LOGICAL(KIND=JPLM), INTENT (IN), TARGET :: P (:,:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (5)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_5LM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_5LM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_5LM_ARRAY (SELF)
CLASS (FIELD_5LM_ARRAY) :: SELF

END SUBROUTINE


END MODULE
