
MODULE FIELD_2IM_UTIL_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_2IM
  MODULE PROCEDURE LOAD_FIELD_2IM_PTR
  MODULE PROCEDURE LOAD_FIELD_2IM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_2IM
  MODULE PROCEDURE SAVE_FIELD_2IM_PTR
  MODULE PROCEDURE SAVE_FIELD_2IM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_2IM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_2IM
  MODULE PROCEDURE COPY_FIELD_2IM_PTR
  MODULE PROCEDURE COPY_FIELD_2IM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_2IM
  MODULE PROCEDURE WIPE_FIELD_2IM_PTR
  MODULE PROCEDURE WIPE_FIELD_2IM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_2IM
  MODULE PROCEDURE HOST_FIELD_2IM_PTR
  MODULE PROCEDURE HOST_FIELD_2IM_VIEW
END INTERFACE

INTERFACE CRC64
  MODULE PROCEDURE CRC64_FIELD_2IM
END INTERFACE


CONTAINS

INTEGER*8 FUNCTION CRC64_FIELD_2IM (YD)
CLASS (FIELD_2IM), POINTER :: YD






END FUNCTION

SUBROUTINE LOAD_FIELD_2IM (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2IM (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_2IM (CDMESS, YD, YO)
USE FIELD_ABORT_MODULE
CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_2IM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_2IM (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_2IM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2IM (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_2IM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_2IM (SELF)
CLASS (FIELD_2IM), POINTER :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_2IM_VIEW (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM_VIEW) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2IM_VIEW (KLUN, YD)
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM_VIEW) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_2IM_VIEW (SELF, LDCREATED)
CLASS (FIELD_2IM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2IM_VIEW (SELF, LDDELETED)
CLASS (FIELD_2IM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_2IM_VIEW (SELF)
CLASS (FIELD_2IM_VIEW) :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_2IM_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2IM_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2IM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_2IM_PTR (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_2IM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2IM_PTR (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_2IM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_2IM_PTR (SELF)
CLASS (FIELD_2IM_PTR) :: SELF

END SUBROUTINE 


END MODULE
