
MODULE FIELD_1RD_UTIL_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_1RD
  MODULE PROCEDURE LOAD_FIELD_1RD_PTR
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_1RD
  MODULE PROCEDURE SAVE_FIELD_1RD_PTR
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_1RD
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_1RD
  MODULE PROCEDURE COPY_FIELD_1RD_PTR
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_1RD
  MODULE PROCEDURE WIPE_FIELD_1RD_PTR
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_1RD
  MODULE PROCEDURE HOST_FIELD_1RD_PTR
END INTERFACE

INTERFACE CRC64
  MODULE PROCEDURE CRC64_FIELD_1RD
END INTERFACE


CONTAINS

INTEGER*8 FUNCTION CRC64_FIELD_1RD (YD)
CLASS (FIELD_1RD), POINTER :: YD






END FUNCTION

SUBROUTINE LOAD_FIELD_1RD (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RD), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1RD (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RD), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_1RD (CDMESS, YD, YO)
USE FIELD_ABORT_MODULE
CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_1RD), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_1RD (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RD), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1RD (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RD) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1RD (SELF)
CLASS (FIELD_1RD), POINTER :: SELF

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_1RD_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RD_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1RD_PTR (KLUN, YD)
USE FIELD_ABORT_MODULE
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1RD_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_1RD_PTR (SELF, LDCREATED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RD_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1RD_PTR (SELF, LDDELETED)
USE FIELD_ABORT_MODULE
CLASS (FIELD_1RD_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1RD_PTR (SELF)
CLASS (FIELD_1RD_PTR) :: SELF

END SUBROUTINE 


END MODULE
