
MODULE FIELD_5RD_SHUFFLE_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE



INTERFACE PAIR_GATHER_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDONLY
END INTERFACE PAIR_GATHER_DEVICE_DATA_RDONLY

PUBLIC :: PAIR_GATHER_DEVICE_DATA_RDONLY


INTERFACE PAIR_GATHER_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDWR
END INTERFACE PAIR_GATHER_DEVICE_DATA_RDWR

PUBLIC :: PAIR_GATHER_DEVICE_DATA_RDWR


INTERFACE PAIR_GATHER_HOST_DATA_RDONLY
  MODULE PROCEDURE :: PAIR_FIELD_5RD_GATHER_HOST_DATA_RDONLY
END INTERFACE PAIR_GATHER_HOST_DATA_RDONLY

PUBLIC :: PAIR_GATHER_HOST_DATA_RDONLY


INTERFACE PAIR_GATHER_HOST_DATA_RDWR
  MODULE PROCEDURE :: PAIR_FIELD_5RD_GATHER_HOST_DATA_RDWR
END INTERFACE PAIR_GATHER_HOST_DATA_RDWR

PUBLIC :: PAIR_GATHER_HOST_DATA_RDWR


INTERFACE PAIR_SCATTER_DATA
  MODULE PROCEDURE :: PAIR_FIELD_5RD_SCATTER_DATA
END INTERFACE PAIR_SCATTER_DATA

PUBLIC :: PAIR_SCATTER_DATA

TYPE FIELD_5RD_SHUFFLE_PAIR
  INTEGER (KIND=JPIM) :: IMODE = -1
  INTEGER (KIND=JPIM) :: IWHAT = -1
  CLASS (FIELD_5RD), POINTER :: YLSCAT => NULL ()
  CLASS (FIELD_5RD), POINTER :: YLGATH => NULL ()
  TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER :: NEXT => NULL ()
END TYPE FIELD_5RD_SHUFFLE_PAIR

PUBLIC :: FIELD_5RD_SHUFFLE_PAIR


INTEGER (KIND=JPIM), PARAMETER :: NRDWR = 0, NRDONLY = 1, NHOST = 2, NDEVICE = 3
INTEGER (KIND=JPIM), PARAMETER :: NLONDIM = 1, NBLKDIM = 2

CONTAINS



FUNCTION PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDONLY (YDPAIR, LDNULL, LDFULL, KLON, KGPBLKS, YDFINDS, YLF) RESULT (PTR)
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER              :: YDPAIR
LOGICAL,                                   INTENT (IN) :: LDNULL, LDFULL
INTEGER (KIND=JPIM),                       INTENT (IN) :: KLON, KGPBLKS
CLASS (FIELD_3IM),                POINTER              :: YDFINDS
CLASS (FIELD_5RD),              POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:), ZTRG(:,:,:,:,:), ZTRS(:,:,:,:,:)








END FUNCTION PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDONLY


FUNCTION PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDWR (YDPAIR, LDNULL, LDFULL, KLON, KGPBLKS, YDFINDS, YLF) RESULT (PTR)
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER              :: YDPAIR
LOGICAL,                                   INTENT (IN) :: LDNULL, LDFULL
INTEGER (KIND=JPIM),                       INTENT (IN) :: KLON, KGPBLKS
CLASS (FIELD_3IM),                POINTER              :: YDFINDS
CLASS (FIELD_5RD),              POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:), ZTRG(:,:,:,:,:), ZTRS(:,:,:,:,:)








END FUNCTION PAIR_FIELD_5RD_GATHER_DEVICE_DATA_RDWR


FUNCTION PAIR_FIELD_5RD_GATHER_HOST_DATA_RDONLY (YDPAIR, LDNULL, LDFULL, KLON, KGPBLKS, YDFINDS, YLF) RESULT (PTR)
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER              :: YDPAIR
LOGICAL,                                   INTENT (IN) :: LDNULL, LDFULL
INTEGER (KIND=JPIM),                       INTENT (IN) :: KLON, KGPBLKS
CLASS (FIELD_3IM),                POINTER              :: YDFINDS
CLASS (FIELD_5RD),              POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:), ZTRG(:,:,:,:,:), ZTRS(:,:,:,:,:)








END FUNCTION PAIR_FIELD_5RD_GATHER_HOST_DATA_RDONLY


FUNCTION PAIR_FIELD_5RD_GATHER_HOST_DATA_RDWR (YDPAIR, LDNULL, LDFULL, KLON, KGPBLKS, YDFINDS, YLF) RESULT (PTR)
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER              :: YDPAIR
LOGICAL,                                   INTENT (IN) :: LDNULL, LDFULL
INTEGER (KIND=JPIM),                       INTENT (IN) :: KLON, KGPBLKS
CLASS (FIELD_3IM),                POINTER              :: YDFINDS
CLASS (FIELD_5RD),              POINTER, INTENT (IN) :: YLF
REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:), ZTRG(:,:,:,:,:), ZTRS(:,:,:,:,:)








END FUNCTION PAIR_FIELD_5RD_GATHER_HOST_DATA_RDWR



SUBROUTINE PAIR_FIELD_5RD_SCATTER_DATA (YDPAIR, YDFINDS)
TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER              :: YDPAIR
CLASS (FIELD_3IM),                POINTER              :: YDFINDS







END SUBROUTINE PAIR_FIELD_5RD_SCATTER_DATA


END MODULE FIELD_5RD_SHUFFLE_MODULE
