
MODULE FIELD_SHUFFLE_TYPE_MODULE


USE FIELD_MODULE
USE FIELD_ACCESS_MODULE
USE FIELD_FACTORY_MODULE
USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM

USE FIELD_2RM_SHUFFLE_MODULE
USE FIELD_3RM_SHUFFLE_MODULE
USE FIELD_4RM_SHUFFLE_MODULE
USE FIELD_5RM_SHUFFLE_MODULE
USE FIELD_2RB_SHUFFLE_MODULE
USE FIELD_3RB_SHUFFLE_MODULE
USE FIELD_4RB_SHUFFLE_MODULE
USE FIELD_5RB_SHUFFLE_MODULE
USE FIELD_2RD_SHUFFLE_MODULE
USE FIELD_3RD_SHUFFLE_MODULE
USE FIELD_4RD_SHUFFLE_MODULE
USE FIELD_5RD_SHUFFLE_MODULE
USE FIELD_2IM_SHUFFLE_MODULE
USE FIELD_3IM_SHUFFLE_MODULE
USE FIELD_4IM_SHUFFLE_MODULE
USE FIELD_5IM_SHUFFLE_MODULE
USE FIELD_2LM_SHUFFLE_MODULE
USE FIELD_3LM_SHUFFLE_MODULE
USE FIELD_4LM_SHUFFLE_MODULE
USE FIELD_5LM_SHUFFLE_MODULE

IMPLICIT NONE

PRIVATE

TYPE FIELD_SHUFFLE
  INTEGER (KIND=JPIM) :: KGPBLKS_G = -1, KLON_G = -1, KGPTOT_G = -1
  INTEGER (KIND=JPIM) :: KGPBLKS_S = -1, KLON_S = -1, KGPTOT_S = -1
  INTEGER (KIND=JPIM) :: KGPBLKS   = -1, KLON   = -1, KGPTOT   = -1 ! alias for KGPBLKS, KLON, KGPTOT
  LOGICAL :: LFULL = .FALSE.  ! No need to gather/scatter, all columns are OK, return pointers based on original fields
  LOGICAL :: LNULL = .FALSE.  ! No need to gather/scatter, all columns are KO, return pointers on empty arrays
  CLASS (FIELD_3IM), POINTER :: YLFINDS => NULL ()
  TYPE (FIELD_2RM_SHUFFLE_PAIR), POINTER :: FIELD_2RM_LIST => NULL ()
  TYPE (FIELD_3RM_SHUFFLE_PAIR), POINTER :: FIELD_3RM_LIST => NULL ()
  TYPE (FIELD_4RM_SHUFFLE_PAIR), POINTER :: FIELD_4RM_LIST => NULL ()
  TYPE (FIELD_5RM_SHUFFLE_PAIR), POINTER :: FIELD_5RM_LIST => NULL ()
  TYPE (FIELD_2RB_SHUFFLE_PAIR), POINTER :: FIELD_2RB_LIST => NULL ()
  TYPE (FIELD_3RB_SHUFFLE_PAIR), POINTER :: FIELD_3RB_LIST => NULL ()
  TYPE (FIELD_4RB_SHUFFLE_PAIR), POINTER :: FIELD_4RB_LIST => NULL ()
  TYPE (FIELD_5RB_SHUFFLE_PAIR), POINTER :: FIELD_5RB_LIST => NULL ()
  TYPE (FIELD_2RD_SHUFFLE_PAIR), POINTER :: FIELD_2RD_LIST => NULL ()
  TYPE (FIELD_3RD_SHUFFLE_PAIR), POINTER :: FIELD_3RD_LIST => NULL ()
  TYPE (FIELD_4RD_SHUFFLE_PAIR), POINTER :: FIELD_4RD_LIST => NULL ()
  TYPE (FIELD_5RD_SHUFFLE_PAIR), POINTER :: FIELD_5RD_LIST => NULL ()
  TYPE (FIELD_2IM_SHUFFLE_PAIR), POINTER :: FIELD_2IM_LIST => NULL ()
  TYPE (FIELD_3IM_SHUFFLE_PAIR), POINTER :: FIELD_3IM_LIST => NULL ()
  TYPE (FIELD_4IM_SHUFFLE_PAIR), POINTER :: FIELD_4IM_LIST => NULL ()
  TYPE (FIELD_5IM_SHUFFLE_PAIR), POINTER :: FIELD_5IM_LIST => NULL ()
  TYPE (FIELD_2LM_SHUFFLE_PAIR), POINTER :: FIELD_2LM_LIST => NULL ()
  TYPE (FIELD_3LM_SHUFFLE_PAIR), POINTER :: FIELD_3LM_LIST => NULL ()
  TYPE (FIELD_4LM_SHUFFLE_PAIR), POINTER :: FIELD_4LM_LIST => NULL ()
  TYPE (FIELD_5LM_SHUFFLE_PAIR), POINTER :: FIELD_5LM_LIST => NULL ()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_SHUFFLE
  PROCEDURE :: INIT_FIELD_SHUFFLE
  PROCEDURE :: SCATTER => SCATTER_FIELD_SHUFFLE
END TYPE FIELD_SHUFFLE

PUBLIC :: FIELD_SHUFFLE

INTEGER (KIND=JPIM), PARAMETER :: NLONDIM = 1, NBLKDIM = 2

CONTAINS

SUBROUTINE INIT_FIELD_SHUFFLE (SELF, KGPTOT, KLON_S, KLON_G)
USE FIELD_ABORT_MODULE
CLASS (FIELD_SHUFFLE) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KGPTOT
INTEGER (KIND=JPIM), INTENT (IN) :: KLON_S, KLON_G


















END SUBROUTINE

SUBROUTINE SCATTER_FIELD_SHUFFLE (SELF)
CLASS (FIELD_SHUFFLE) :: SELF































END SUBROUTINE

END MODULE FIELD_SHUFFLE_TYPE_MODULE
