MODULE GRIB_API_INTERFACE

!define GRIB_API_TRACE

!**** Interface to GRIB_API

!     Purpose.
!     --------
!     Fortran 90 Interface to calling GRIB API

!     Author.
!     -------
!        M.Hamrud     ECMWF

!     Modifications.
!     --------------
!        Original: 2005-11-15
!      F. Vana  05-Mar-2015  Support for single precision

!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPRD, JPIM, JPIB, JPRM
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

INTERFACE IGRIB_GET_VALUE
MODULE PROCEDURE &
 & IGRIB_GET_INT, IGRIB_GET_REAL4, IGRIB_GET_REAL8,IGRIB_GET_CHAR,&
 & IGRIB_GET_INT_ARRAY, IGRIB_GET_REAL4_ARRAY, IGRIB_GET_REAL8_ARRAY, &
 & IGRIB_GET_INT8
END INTERFACE
INTERFACE IGRIB_SET_VALUE
MODULE PROCEDURE &
 & IGRIB_SET_INT, IGRIB_SET_REAL4, IGRIB_SET_REAL8,IGRIB_SET_CHAR,&
 & IGRIB_SET_INT_ARRAY, IGRIB_SET_REAL4_ARRAY, IGRIB_SET_REAL8_ARRAY, &
 & IGRIB_SET_INT8, IGRIB_SET_INT8_ARRAY
END INTERFACE
INTERFACE IGRIB_READ_BYTES
MODULE PROCEDURE &
 & IGRIB_READ_BYTES_INT, IGRIB_READ_BYTES_REAL4, IGRIB_READ_BYTES_REAL8, IGRIB_READ_BYTES_CHAR
END INTERFACE
INTERFACE IGRIB_WRITE_BYTES
MODULE PROCEDURE &
 & IGRIB_WRITE_BYTES_INT, IGRIB_WRITE_BYTES_REAL4, IGRIB_WRITE_BYTES_REAL8, IGRIB_WRITE_BYTES_CHAR
END INTERFACE

PUBLIC IGRIB_GET_VALUE, IGRIB_SET_VALUE, IGRIB_OPEN_FILE, IGRIB_CLOSE_FILE,&
 & IGRIB_RELEASE, JPGRIB_SUCCESS, JPGRIB_END_OF_FILE, JPGRIB_BUFFER_TOO_SMALL, &
 & IGRIB_GET_MESSAGE_SIZE, IGRIB_NEW_FROM_MESSAGE, IGRIB_NEW_FROM_FILE, &
 & IGRIB_NEW_FROM_SAMPLES, IGRIB_CLONE ,IGRIB_GET_MESSAGE, IGRIB_READ_FROM_FILE, &
 & IGRIB_READ_BYTES, IGRIB_WRITE_BYTES, IGRIB_WRITE, IGRIB_IS_DEFINED, IGRIB_ERROR_MESSAGE

INTEGER, PARAMETER :: JPGRIB_SUCCESS=0
INTEGER, PARAMETER :: JPGRIB_END_OF_FILE=0
INTEGER, PARAMETER :: JPGRIB_BUFFER_TOO_SMALL=0

PRIVATE
#ifdef GRIB_API_1
INTEGER, PARAMETER, PUBLIC :: JPKSIZE_T=JPIM
#else
INTEGER, PARAMETER, PUBLIC :: JPKSIZE_T=4
#endif

LOGICAL, PUBLIC :: LGRIB_API_TRACE = .FALSE.

CONTAINS

SUBROUTINE IGRIB_GET_INT8(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIB),INTENT(OUT) :: KVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_INT8

SUBROUTINE IGRIB_GET_INT(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIM),INTENT(OUT) :: KVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_INT

SUBROUTINE IGRIB_GET_REAL4(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRM)   ,INTENT(OUT) :: PVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_REAL4

SUBROUTINE IGRIB_GET_REAL8(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRD)   ,INTENT(OUT) :: PVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_REAL8

SUBROUTINE IGRIB_GET_CHAR(KHANDLE,CDKEY,CDVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
CHARACTER(LEN=*)  ,INTENT(OUT) :: CDVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_CHAR

SUBROUTINE IGRIB_GET_INT_ARRAY(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIM),INTENT(OUT) :: KVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_INT_ARRAY

SUBROUTINE IGRIB_GET_REAL4_ARRAY(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRM)   ,INTENT(OUT) :: PVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_REAL4_ARRAY

SUBROUTINE IGRIB_GET_REAL8_ARRAY(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRD)   ,INTENT(OUT) :: PVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_GET_REAL8_ARRAY
!====================================================================
SUBROUTINE IGRIB_SET_INT8(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIB),INTENT(IN) :: KVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET



#ifdef GRIB_API_TRACE

#endif



END SUBROUTINE IGRIB_SET_INT8

SUBROUTINE IGRIB_SET_INT(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIM),INTENT(IN) :: KVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET



#ifdef GRIB_API_TRACE

#endif



END SUBROUTINE IGRIB_SET_INT

SUBROUTINE IGRIB_SET_REAL4(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRM)   ,INTENT(IN) :: PVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_SET_REAL4

SUBROUTINE IGRIB_SET_REAL8(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRD)   ,INTENT(IN) :: PVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET


#ifdef GRIB_API_TRACE

#endif




END SUBROUTINE IGRIB_SET_REAL8

SUBROUTINE IGRIB_SET_CHAR(KHANDLE,CDKEY,CDVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
CHARACTER(LEN=*)  ,INTENT(IN) :: CDVAL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET



#ifdef GRIB_API_TRACE

#endif



END SUBROUTINE IGRIB_SET_CHAR

SUBROUTINE IGRIB_SET_INT8_ARRAY(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIB),INTENT(IN) :: KVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET




#ifdef GRIB_API_TRACE

#endif



END SUBROUTINE IGRIB_SET_INT8_ARRAY

SUBROUTINE IGRIB_SET_INT_ARRAY(KHANDLE,CDKEY,KVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
INTEGER(KIND=JPIM),INTENT(IN) :: KVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET




#ifdef GRIB_API_TRACE

#endif



END SUBROUTINE IGRIB_SET_INT_ARRAY

SUBROUTINE IGRIB_SET_REAL4_ARRAY(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRM)   ,INTENT(IN) :: PVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_SET_REAL4_ARRAY

SUBROUTINE IGRIB_SET_REAL8_ARRAY(KHANDLE,CDKEY,PVAL,KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE
CHARACTER(LEN=*)  ,INTENT(IN) :: CDKEY
REAL(KIND=JPRD)   ,INTENT(IN) :: PVAL(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET



#ifdef GRIB_API_TRACE

#endif




END SUBROUTINE IGRIB_SET_REAL8_ARRAY

SUBROUTINE IGRIB_OPEN_FILE(KFILE,CDPATH,CDMODE)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KFILE
CHARACTER(LEN=*)  ,INTENT(IN)   :: CDPATH
CHARACTER(LEN=1)  ,INTENT(IN)   :: CDMODE






END SUBROUTINE IGRIB_OPEN_FILE

SUBROUTINE IGRIB_CLOSE_FILE(KFILE)
INTEGER(KIND=JPIM),INTENT(IN)  :: KFILE






END SUBROUTINE IGRIB_CLOSE_FILE

SUBROUTINE IGRIB_READ_FROM_FILE(KFILE,KBUF,KBYTES,KRET)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
INTEGER(KIND=JPIM),INTENT(OUT)   :: KBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_READ_FROM_FILE

SUBROUTINE IGRIB_READ_BYTES_INT(KFILE,KBUF,KBYTES,KRET)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
INTEGER(KIND=JPIM),INTENT(OUT)   :: KBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES
INTEGER(KIND=JPIM),INTENT(OUT)   :: KRET







END SUBROUTINE IGRIB_READ_BYTES_INT

SUBROUTINE IGRIB_READ_BYTES_REAL4(KFILE,PBUF,KBYTES,KRET)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
REAL(KIND=JPRM)   ,INTENT(OUT)   :: PBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES
INTEGER(KIND=JPIM),INTENT(OUT)   :: KRET







END SUBROUTINE IGRIB_READ_BYTES_REAL4

SUBROUTINE IGRIB_READ_BYTES_REAL8(KFILE,PBUF,KBYTES,KRET)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
REAL(KIND=JPRD)   ,INTENT(OUT)   :: PBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES
INTEGER(KIND=JPIM),INTENT(OUT)   :: KRET







END SUBROUTINE IGRIB_READ_BYTES_REAL8

SUBROUTINE IGRIB_READ_BYTES_CHAR(KFILE,CDBUF,KBYTES,KRET)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
CHARACTER(LEN=1)  ,INTENT(OUT)   :: CDBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES
INTEGER(KIND=JPIM),INTENT(OUT)   :: KRET







END SUBROUTINE IGRIB_READ_BYTES_CHAR


SUBROUTINE IGRIB_WRITE_BYTES_INT(KFILE,KBUF,KBYTES)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
INTEGER(KIND=JPIM),INTENT(IN)    :: KBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES






END SUBROUTINE IGRIB_WRITE_BYTES_INT

SUBROUTINE IGRIB_WRITE_BYTES_REAL4(KFILE,PBUF,KBYTES)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
REAL(KIND=JPRM)   ,INTENT(IN)    :: PBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES






END SUBROUTINE IGRIB_WRITE_BYTES_REAL4

SUBROUTINE IGRIB_WRITE_BYTES_REAL8(KFILE,PBUF,KBYTES)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
REAL(KIND=JPRD)   ,INTENT(IN)    :: PBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES






END SUBROUTINE IGRIB_WRITE_BYTES_REAL8

SUBROUTINE IGRIB_WRITE_BYTES_CHAR(KFILE,CDBUF,KBYTES)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFILE
CHARACTER(LEN=1)  ,INTENT(IN)    :: CDBUF(:)
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KBYTES






END SUBROUTINE IGRIB_WRITE_BYTES_CHAR

SUBROUTINE IGRIB_NEW_FROM_FILE(KFILE,KHANDLE,KRET)
INTEGER(KIND=JPIM),INTENT(IN)  :: KFILE
INTEGER(KIND=JPIM),INTENT(OUT) :: KHANDLE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_NEW_FROM_FILE

SUBROUTINE IGRIB_WRITE(KFILE,KHANDLE,KRET)
INTEGER(KIND=JPIM),INTENT(IN)  :: KFILE
INTEGER(KIND=JPIM),INTENT(IN)  :: KHANDLE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_WRITE

SUBROUTINE IGRIB_NEW_FROM_MESSAGE(KHANDLE,KBUF)
INTEGER(KIND=JPIM),INTENT(OUT) :: KHANDLE
INTEGER(KIND=JPIM),INTENT(IN)  :: KBUF(:)






END SUBROUTINE IGRIB_NEW_FROM_MESSAGE

SUBROUTINE IGRIB_RELEASE(KHANDLE)
INTEGER(KIND=JPIM),INTENT(IN) :: KHANDLE






END SUBROUTINE IGRIB_RELEASE

SUBROUTINE IGRIB_GET_MESSAGE_SIZE(KHANDLE,KBYTES)
INTEGER(KIND=JPIM),INTENT(IN)  :: KHANDLE
INTEGER(KIND=JPKSIZE_T),INTENT(OUT) :: KBYTES








END SUBROUTINE IGRIB_GET_MESSAGE_SIZE

SUBROUTINE IGRIB_GET_MESSAGE(KHANDLE,KGRIB)
INTEGER(KIND=JPIM),INTENT(IN)  :: KHANDLE
INTEGER(KIND=JPIM),INTENT(OUT) :: KGRIB(:)

















END SUBROUTINE IGRIB_GET_MESSAGE

SUBROUTINE IGRIB_NEW_FROM_SAMPLES(KHANDLE,CDNAME,KRET)
INTEGER(KIND=JPIM),INTENT(OUT) :: KHANDLE
CHARACTER(LEN=*),INTENT(IN) :: CDNAME
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRET






END SUBROUTINE IGRIB_NEW_FROM_SAMPLES

SUBROUTINE IGRIB_CLONE(KHANDLE1,KHANDLE2)
INTEGER(KIND=JPIM),INTENT(IN)  :: KHANDLE1
INTEGER(KIND=JPIM),INTENT(OUT) :: KHANDLE2






END SUBROUTINE IGRIB_CLONE

SUBROUTINE IGRIB_IS_DEFINED(KHANDLE, CDKEY, LDDEFINED, KRET)
INTEGER(KIND=JPIM),           INTENT(IN)  :: KHANDLE
CHARACTER(LEN=*),             INTENT(IN)  :: CDKEY
LOGICAL,                      INTENT(OUT) :: LDDEFINED
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: KRET



#ifdef FAGRIB2

#else
#endif


END SUBROUTINE IGRIB_IS_DEFINED

SUBROUTINE IGRIB_ERROR_MESSAGE(KRET)
INTEGER(KIND=JPIM),INTENT(IN) :: KRET





END SUBROUTINE IGRIB_ERROR_MESSAGE

END MODULE GRIB_API_INTERFACE

