
MODULE HOST_ALLOC_MODULE


USE PARKIND1, ONLY : JPRM, JPRB, JPRD, JPIM, JPLM
USE ISO_C_BINDING

IMPLICIT NONE

PRIVATE

INTERFACE HOST_ALLOC
  MODULE PROCEDURE FIELD_1RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5RM_HOST_ALLOC
  MODULE PROCEDURE FIELD_1RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_2RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_3RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_4RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_5RD_HOST_ALLOC
  MODULE PROCEDURE FIELD_1IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5IM_HOST_ALLOC
  MODULE PROCEDURE FIELD_1LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_2LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_3LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_4LM_HOST_ALLOC
  MODULE PROCEDURE FIELD_5LM_HOST_ALLOC
END INTERFACE HOST_ALLOC

INTERFACE HOST_DEALLOC
  MODULE PROCEDURE FIELD_1RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5RM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5RD_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5IM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_1LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_2LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_3LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_4LM_HOST_DEALLOC
  MODULE PROCEDURE FIELD_5LM_HOST_DEALLOC
END INTERFACE HOST_DEALLOC

INTERFACE
  SUBROUTINE C_MALLOC (SIZ, PTR) BIND (C, NAME='c_malloc')
    IMPORT :: C_PTR, C_SIZE_T
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZ
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE C_MALLOC
  SUBROUTINE C_FREE (PTR) BIND (C, NAME='c_free')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE C_FREE
END INTERFACE

PUBLIC :: HOST_ALLOC
PUBLIC :: HOST_DEALLOC

CONTAINS

SUBROUTINE FIELD_1RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
LOGICAL, INTENT(IN) :: PINNED









END SUBROUTINE FIELD_1RM_HOST_ALLOC

SUBROUTINE FIELD_1RM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_1RM_HOST_DEALLOC

SUBROUTINE FIELD_2RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
LOGICAL, INTENT(IN) :: PINNED











END SUBROUTINE FIELD_2RM_HOST_ALLOC

SUBROUTINE FIELD_2RM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_2RM_HOST_DEALLOC

SUBROUTINE FIELD_3RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
LOGICAL, INTENT(IN) :: PINNED













END SUBROUTINE FIELD_3RM_HOST_ALLOC

SUBROUTINE FIELD_3RM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_3RM_HOST_DEALLOC

SUBROUTINE FIELD_4RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, INTENT(IN) :: PINNED















END SUBROUTINE FIELD_4RM_HOST_ALLOC

SUBROUTINE FIELD_4RM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_4RM_HOST_DEALLOC

SUBROUTINE FIELD_5RM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
LOGICAL, INTENT(IN) :: PINNED

















END SUBROUTINE FIELD_5RM_HOST_ALLOC

SUBROUTINE FIELD_5RM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_5RM_HOST_DEALLOC

SUBROUTINE FIELD_1RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
LOGICAL, INTENT(IN) :: PINNED









END SUBROUTINE FIELD_1RD_HOST_ALLOC

SUBROUTINE FIELD_1RD_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_1RD_HOST_DEALLOC

SUBROUTINE FIELD_2RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
LOGICAL, INTENT(IN) :: PINNED











END SUBROUTINE FIELD_2RD_HOST_ALLOC

SUBROUTINE FIELD_2RD_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_2RD_HOST_DEALLOC

SUBROUTINE FIELD_3RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
LOGICAL, INTENT(IN) :: PINNED













END SUBROUTINE FIELD_3RD_HOST_ALLOC

SUBROUTINE FIELD_3RD_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_3RD_HOST_DEALLOC

SUBROUTINE FIELD_4RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, INTENT(IN) :: PINNED















END SUBROUTINE FIELD_4RD_HOST_ALLOC

SUBROUTINE FIELD_4RD_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_4RD_HOST_DEALLOC

SUBROUTINE FIELD_5RD_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
LOGICAL, INTENT(IN) :: PINNED

















END SUBROUTINE FIELD_5RD_HOST_ALLOC

SUBROUTINE FIELD_5RD_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
REAL(KIND=JPRD), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_5RD_HOST_DEALLOC

SUBROUTINE FIELD_1IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
LOGICAL, INTENT(IN) :: PINNED









END SUBROUTINE FIELD_1IM_HOST_ALLOC

SUBROUTINE FIELD_1IM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_1IM_HOST_DEALLOC

SUBROUTINE FIELD_2IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
LOGICAL, INTENT(IN) :: PINNED











END SUBROUTINE FIELD_2IM_HOST_ALLOC

SUBROUTINE FIELD_2IM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_2IM_HOST_DEALLOC

SUBROUTINE FIELD_3IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
LOGICAL, INTENT(IN) :: PINNED













END SUBROUTINE FIELD_3IM_HOST_ALLOC

SUBROUTINE FIELD_3IM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_3IM_HOST_DEALLOC

SUBROUTINE FIELD_4IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, INTENT(IN) :: PINNED















END SUBROUTINE FIELD_4IM_HOST_ALLOC

SUBROUTINE FIELD_4IM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_4IM_HOST_DEALLOC

SUBROUTINE FIELD_5IM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
LOGICAL, INTENT(IN) :: PINNED

















END SUBROUTINE FIELD_5IM_HOST_ALLOC

SUBROUTINE FIELD_5IM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
INTEGER(KIND=JPIM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_5IM_HOST_DEALLOC

SUBROUTINE FIELD_1LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(1)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
LOGICAL, INTENT(IN) :: PINNED









END SUBROUTINE FIELD_1LM_HOST_ALLOC

SUBROUTINE FIELD_1LM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_1LM_HOST_DEALLOC

SUBROUTINE FIELD_2LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(2)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(2)
LOGICAL, INTENT(IN) :: PINNED











END SUBROUTINE FIELD_2LM_HOST_ALLOC

SUBROUTINE FIELD_2LM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_2LM_HOST_DEALLOC

SUBROUTINE FIELD_3LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(3)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(3)
LOGICAL, INTENT(IN) :: PINNED













END SUBROUTINE FIELD_3LM_HOST_ALLOC

SUBROUTINE FIELD_3LM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_3LM_HOST_DEALLOC

SUBROUTINE FIELD_4LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(4)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
LOGICAL, INTENT(IN) :: PINNED















END SUBROUTINE FIELD_4LM_HOST_ALLOC

SUBROUTINE FIELD_4LM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_4LM_HOST_DEALLOC

SUBROUTINE FIELD_5LM_HOST_ALLOC (HST, LBOUNDS, UBOUNDS, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(OUT) :: HST(:,:,:,:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: LBOUNDS(5)
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
LOGICAL, INTENT(IN) :: PINNED

















END SUBROUTINE FIELD_5LM_HOST_ALLOC

SUBROUTINE FIELD_5LM_HOST_DEALLOC(HST, PINNED)
USE FIELD_ABORT_MODULE
LOGICAL(KIND=JPLM), POINTER, INTENT(INOUT) :: HST(:,:,:,:,:)
LOGICAL, INTENT (IN) :: PINNED




END SUBROUTINE FIELD_5LM_HOST_DEALLOC


END MODULE HOST_ALLOC_MODULE
