!#ifdef RS6K
!@PROCESS NOCHECK
!#endif
MODULE IOSTREAM_MIX

!     Purpose.
!     --------

!      IOSTREAM_MIX contains data and routines for the generalized IO package

!     Author.
!     -------
!     Mats Hamrud(ECMWF)

!     Modifications.
!     --------------
!     Original : 2005-12-01
!     M Fisher : 2007-08-06 Raw I/O of character strings
!     S Martinez 24-June-2009 : SX9 compiler workaround : re-write some loops
!         in a more robust way ; especially avoiding fully implicit
!         synthax array (thanks to E.Sevault).
!     R. El Khatib 03-Jul-2009 Add missing NULLIFY statements
!     E. Sevault 09-Jul-2009 Securize workaround above.
!     E. Holm  : 2009-12-18 Correct raw format character write in io_put
!     H.Varella : 2010-04-20 Fix the writing out of characters in raw file format
!     M Leutbecher 2011-03-21 Updates for LINTERP=T 
!     E. Holm  : 2012-02-17 Insert igrib_release in close_iorequest and grib_decode
!     M. Fisher   7-March-2012 Use DEALLOCATE_IF_ASSOCIATED
!     F. Vana  05-Mar-2015  Support for single precision
!     S. Saarinen : 2016-10-19 : Added missing IGRIB_RELEASE to OpenMP region
!     P. de Rosnay: 2017 12: added YDR%CLEVTYPE in INTER_GP arguments for SEKF-EDA
!     S. Massart: 2019 12: Fix for  YDR%LDISTRIBUTE = .FALSE. and  YDR%LINTERP = .TRUE. 
!-------------------------------------------------------------------------

USE PARKIND1      , ONLY : JPRD, JPIM, JPIB, JPRB
USE PARDIM        , ONLY : JPMXGL
USE FDBSUBS_MOD   , ONLY : IWRITEFDBSUBS, IFLUSHFDBSUBS
USE YOMCT0        , ONLY : LECMWF
USE YOMHOOK       , ONLY : LHOOK, DR_HOOK, JPHOOK
USE GRIB_HANDLES_MOD, ONLY : TYPE_GRIB_HANDLES
USE YOM_GRIB_CODES
USE GRIB_UTILS_MOD
USE GRIB_API_INTERFACE
USE DEALLOCATE_IF_ALLOCATED_MOD, ONLY : DEALLOCATE_IF_ALLOCATED

IMPLICIT NONE
SAVE

!     -------------------------------------------------------------------------
PRIVATE
PUBLIC TYPE_IOSTREAM,TYPE_IOREQUEST,&
 & TYPE_3D_MDL_FLDS, TYPE_2D_MDL_FLDS, TYPE_SPECTRAL_FLD_DEF,&
 & TYPE_GRIDPOINT_FLD_DEF,&
 & SETUP_IOSTREAM,SETUP_IOREQUEST,IO_PUT,IO_GET,&
 & CLOSE_IOSTREAM,CLOSE_IOREQUEST,Y_IOSTREAM_FDB,IO_INQUIRE,IOSTREAM_STATS,&
 & FLUSH_IOSTREAM,INQUIRE_GRIB,INI_IOSTREAM,&
 & YGBH

TYPE(TYPE_GRIB_HANDLES) :: YGBH
REAL(KIND=JPRB), PARAMETER, PUBLIC :: RMDI=HUGE(RMDI)

INTEGER(KIND=JPIM),PARAMETER :: JPNONDEF = -99
INTEGER(KIND=JPIB),PARAMETER :: JPMAXGRID = 2_JPIB * INT(JPMXGL,JPIB) * INT(JPMXGL,JPIB)
INTEGER(KIND=JPIM),PARAMETER :: JPMAXCHUNK = 8192

INTEGER(KIND=JPIM),PARAMETER :: JPFDB=1
INTEGER(KIND=JPIM),PARAMETER :: JPCIO=2
INTEGER(KIND=JPIM),PARAMETER :: JPFTN=3

TYPE TYPE_IOSTREAM

INTEGER(KIND=JPIM) :: IOTYPE   = 0
INTEGER(KIND=JPIM) :: IFILE_HANDLE  = JPNONDEF
INTEGER(KIND=JPIM) :: IOMASTER = JPNONDEF
CHARACTER(LEN=1)   :: CMODE    = 'r'
CHARACTER(LEN=120) :: CPATH
LOGICAL            :: LEOF
INTEGER(KIND=JPIM) :: NRECS
INTEGER(KIND=JPIB) :: NBYTES 
LOGICAL            :: LIOPROC
LOGICAL            :: LIOPROCHLP
LOGICAL            :: LIOUSEHELP
LOGICAL            :: LIONOHELP
LOGICAL            :: LNVALS
INTEGER(KIND=JPIM),ALLOCATABLE :: IOPROCS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IOPROCSHLP(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NUMHLP(:)
INTEGER(KIND=JPIM) :: NUMIOPROCS
INTEGER(KIND=JPIM) :: MIOPROCHLP
INTEGER(KIND=JPIM) :: NUMIOPROCSHLP
INTEGER(KIND=JPIM) :: NVALS
REAL(KIND=JPRD)    :: WALLCLOCK
REAL(KIND=JPRD)    :: TOTWALL
LOGICAL            :: SERIAL

END TYPE TYPE_IOSTREAM


INTEGER(KIND=JPIM),PARAMETER :: JPRAW=1
INTEGER(KIND=JPIM),PARAMETER :: JPSPEC=2
INTEGER(KIND=JPIM),PARAMETER :: JPGP=3

TYPE TYPE_3D_MDL_FLDS
INTEGER(KIND=JPIM) :: NUMFLDS
INTEGER(KIND=JPIM) :: NLEVS
INTEGER(KIND=JPIM),ALLOCATABLE :: ILEVS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IGRIBCODE(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IBSET(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: ILOCLEV(:)
END TYPE TYPE_3D_MDL_FLDS

TYPE TYPE_2D_MDL_FLDS
INTEGER(KIND=JPIM) :: NUMFLDS
INTEGER(KIND=JPIM),ALLOCATABLE :: IGRIBCODE(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: ILEVS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IBSET(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: ILOCFLD(:)
END TYPE TYPE_2D_MDL_FLDS

TYPE TYPE_SPECTRAL_FLD_DEF
INTEGER(KIND=JPIM) :: ISMAX
INTEGER(KIND=JPIM) :: ISPEC2G
INTEGER(KIND=JPIM) :: ISPEC2
INTEGER(KIND=JPIM) :: IMAXSPEC2G
END TYPE TYPE_SPECTRAL_FLD_DEF

TYPE TYPE_GRIDPOINT_FLD_DEF
INTEGER(KIND=JPIM) :: IGPTOTG
INTEGER(KIND=JPIM) :: IGPTOT
INTEGER(KIND=JPIM) :: NPROMA
END TYPE TYPE_GRIDPOINT_FLD_DEF

TYPE TYPE_IOREQUEST
INTEGER(KIND=JPIM) :: IDATA_TYPE = JPNONDEF  ! Type of data
LOGICAL            :: LGRIB    = .FALSE.     ! Data GRIB coded
LOGICAL            :: LRANDOM_ORDER          ! Data read in random order
LOGICAL            :: LFPDIST                ! Data in FullPos distribution
LOGICAL            :: LINTERP                ! Fields to be interpolatad
LOGICAL            :: LDISTRIBUTE            ! Fields distributed
LOGICAL            :: LDISTHEADER            ! Header data distributed
LOGICAL            :: LGEOPRESET             ! Use geography from imported GRIB header
LOGICAL            :: LREADALL               ! Read all of file even of all fields found
LOGICAL            :: LINQUIRE               ! Use inquire mode
LOGICAL            :: LATLONG                ! Grid-point data in lat/long grid
LOGICAL            :: LINTONLY               ! Interogate only mode (disable checks)
INTEGER(KIND=JPIM) :: NTYPE_INTERP           ! Type of interpolation
INTEGER(KIND=JPIM) :: NRESOL                 ! Resolution identifier
CHARACTER(LEN=3)   :: CLEVTYPE = 'SFC'       ! Level type
TYPE(TYPE_3D_MDL_FLDS) :: YMDL_3D
TYPE(TYPE_2D_MDL_FLDS) :: YMDL_2D
TYPE(TYPE_SPECTRAL_FLD_DEF) :: YSPF
TYPE(TYPE_GRIDPOINT_FLD_DEF) :: YGPF
!TYPE(GRIB_HEADER) :: YGRBH
INTEGER(KIND=JPIM) :: ILEV
INTEGER(KIND=JPIM) :: IGRBCODE
INTEGER(KIND=JPIM),ALLOCATABLE :: ILEVS(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IGRBCODES(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IHAVEFLD(:)
CHARACTER(LEN=32)  :: CREPRT
INTEGER(KIND=JPIM) :: IRESOLI
INTEGER(KIND=JPIM) :: NCHUNKSIZE
INTEGER(KIND=JPIM) :: IFIELDS_IO
INTEGER(KIND=JPIM) :: IGRIB_HANDLE
INTEGER(KIND=JPIM) :: IGRIB_HANDLE2
INTEGER(KIND=JPIM),ALLOCATABLE :: IGRIB_OMP_HANDLE(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IGRIB_OMP_HANDLE2(:)
INTEGER(KIND=JPIM) :: IVALUES
INTEGER(KIND=JPIM) :: IFIELDS_HAVE
REAL(KIND=JPRB)    :: TSTEP ! For grib_coding
INTEGER(KIND=JPIM) :: IOCOMM ! MPI communicator for IO processes
END TYPE TYPE_IOREQUEST

TYPE TYPE_INT_VARS
INTEGER(KIND=JPIM) :: NUNDEF
INTEGER(KIND=JPIM) :: NULERR
INTEGER(KIND=JPIM) :: NULOUT
INTEGER(KIND=JPIM) :: MYPROC
INTEGER(KIND=JPIM) :: NPROC
INTEGER(KIND=JPIB) :: IMAXGRID
INTEGER(KIND=JPIB) :: IMAXSPEC2G
REAL(KIND=JPRB)    :: RPI
REAL(KIND=JPRB)    :: SIPR
INTEGER(KIND=JPIM) :: NREALEN  ! size of INTEGER(JPIM) in bytes
INTEGER(KIND=JPIM) :: NINTLEN  ! size of REAL(JPRB)    in bytes
INTEGER(KIND=JPIM),ALLOCATABLE :: NBSETLEV(:)
INTEGER(KIND=JPIM) :: NBSETSP
INTEGER(KIND=JPIM) :: NFLEVG
INTEGER(KIND=JPIM) :: NSMAX
INTEGER(KIND=JPIM) :: NDGLG
INTEGER(KIND=JPIM),ALLOCATABLE :: NLOENG(:)
REAL(KIND=JPRB),ALLOCATABLE :: VAH(:)
REAL(KIND=JPRB),ALLOCATABLE :: VBH(:)
REAL(KIND=JPRB),ALLOCATABLE :: RLATIG(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NUMPROCFP(:)
INTEGER(KIND=JPIM) :: NFPRGPL
INTEGER(KIND=JPIM) :: NFPRGPG
INTEGER(KIND=JPIM) :: NFPRGPLX
INTEGER(KIND=JPIM),ALLOCATABLE :: NFPMAX(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: MSATID(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: MSERIES(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: MINST(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: MCHAN(:)
REAL(KIND=JPRB), ALLOCATABLE :: RCWN(:)
LOGICAL            :: LIFS_INTERNAL
END TYPE TYPE_INT_VARS

TYPE(TYPE_IOSTREAM) :: Y_IOSTREAM_FDB
TYPE(TYPE_INT_VARS) :: YIOS

LOGICAL            :: LPACK_INIT=.FALSE.
INTEGER(KIND=JPIM) :: NIOSTREAMC = 0
INTEGER(KIND=JPIM) :: NOPENIOSTREAMS = 0
INTEGER(KIND=JPIM) :: NOPENEDIOSTREAMS = 0
REAL(KIND=JPRD)    :: TOTAL_WALLCLOCK = 0.0_JPRD
REAL(KIND=JPRD)    :: WALLCLOCK_OUT = 0.0_JPRD
REAL(KIND=JPRD)    :: TOTWALL_OUT = 0.0_JPRD
INTEGER(KIND=JPIM) :: NRECS_OUT = 0_JPIM
INTEGER(KIND=JPIB) :: NBYTES_OUT = 0_JPIB
REAL(KIND=JPRD)    :: WALLCLOCK_IN = 0.0_JPRD
REAL(KIND=JPRD)    :: TOTWALL_IN = 0.0_JPRD
INTEGER(KIND=JPIM) :: NRECS_IN = 0_JPIM
INTEGER(KIND=JPIB) :: NBYTES_IN = 0_JPIB
INTEGER(KIND=JPIM),ALLOCATABLE,TARGET :: NGRIBD(:)
INTEGER(KIND=JPIM),ALLOCATABLE        :: NGRIBMSG(:)
INTEGER(KIND=JPIM),ALLOCATABLE,TARGET :: NGSTA(:)
LOGICAL,ALLOCATABLE :: LGRIBDONE(:)

CONTAINS
!======================================================================
SUBROUTINE INI_IOSTREAM(KULOUT,KBSETLEV,KBSETSP,KFLEVG,KSMAX,KDGLG,PVAH,PVBH,KLOENG,&
& PLATIG,KNUMPROCFP,KFPRGPL,KFPRGPG,KFPRGPLX,KFPMAX,KSATID,KSERIES,KINST,KCHAN,PCWN,&
& LDIFS_INTERNAL)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KULOUT
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KBSETLEV(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KBSETSP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KFLEVG
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KSMAX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KDGLG
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PVAH(:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PVBH(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KLOENG(:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PLATIG(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KNUMPROCFP(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KFPRGPL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KFPRGPG
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KFPRGPLX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KFPMAX(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KSATID(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KSERIES(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KINST(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KCHAN(:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)  :: PCWN(:)
LOGICAL           ,OPTIONAL,INTENT(IN)  :: LDIFS_INTERNAL
























END SUBROUTINE INI_IOSTREAM
!======================================================================
SUBROUTINE SETUP_IOSTREAM(YD,CDTYPE,CDPATH,CDMODE,KIOMASTER,&
& KIOPROCS,LDNOHELP,KNVALS,LSERIAL)














IMPLICIT NONE
TYPE(TYPE_IOSTREAM)        ,INTENT(INOUT) :: YD
CHARACTER(LEN=*)           ,INTENT(IN)    :: CDTYPE
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(IN)    :: CDPATH
CHARACTER(LEN=1)  ,OPTIONAL,INTENT(IN)    :: CDMODE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KIOMASTER
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KIOPROCS(:)
LOGICAL           ,OPTIONAL,INTENT(IN)    :: LDNOHELP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KNVALS
LOGICAL           ,OPTIONAL,INTENT(IN)    :: LSERIAL
















































END SUBROUTINE SETUP_IOSTREAM
!=============================================================
SUBROUTINE CLOSE_IOSTREAM(YD)






IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT) :: YD































END SUBROUTINE CLOSE_IOSTREAM

!=============================================================

SUBROUTINE FLUSH_IOSTREAM(YD)






IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT) :: YD






END SUBROUTINE FLUSH_IOSTREAM
!=============================================================
SUBROUTINE IOSTREAM_STATS
IMPLICIT NONE
























END SUBROUTINE IOSTREAM_STATS
!=============================================================
SUBROUTINE SETUP_IOREQUEST(YDR,CDTYPE,KGRIB3D,KLEVS3D,KGRIB2D,KLEVS2D,KBSET2D,KBSET3D,&
& LDGRIB,KPROMA,KGPTOTG,KRESOL,CDLEVTYPE,LDFPDIST,LDINTERP,KTYPE_INTERP,LDISTRIBUTE,&
& LDISTHEADER,KGRIB_HANDLE,KGRIB_HANDLE2,LDREADALL,LDLATLONG,LDINTONLY,KSMAX,KMAXSPEC2G,&
& LDRANDOM_ORDER,KCHUNKSIZE,PTSTEP)




























IMPLICIT NONE
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
CHARACTER(LEN=*)           ,INTENT(IN) :: CDTYPE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGRIB3D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLEVS3D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGRIB2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLEVS2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KBSET2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KBSET3D(:)
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDGRIB
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDFPDIST
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDINTERP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KTYPE_INTERP
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDISTRIBUTE
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDISTHEADER
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDREADALL
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDLATLONG
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDINTONLY
LOGICAL           ,OPTIONAL,INTENT(IN) :: LDRANDOM_ORDER
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGPTOTG
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KMAXSPEC2G
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(IN) :: CDLEVTYPE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGRIB_HANDLE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGRIB_HANDLE2
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KCHUNKSIZE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KRESOL
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN) :: PTSTEP

















































END SUBROUTINE SETUP_IOREQUEST

!=============================================================
SUBROUTINE CLOSE_IOREQUEST(YDR)
USE DEALLOCATE_IF_ALLOCATED_MOD, ONLY : DEALLOCATE_IF_ALLOCATED
IMPLICIT NONE






TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR


















END SUBROUTINE CLOSE_IOREQUEST

!=================================================================

SUBROUTINE IO_PUT(YD,YDR,PR1,PR2,PR3,PR4,KR1,KR2,KR3,KR4,CDR,&
& KFLDPROC2D,KLEVPROC3D)
















IMPLICIT NONE
TYPE(TYPE_IOSTREAM) ,INTENT(INOUT)     :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT)     :: YDR
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN) :: PR1(:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN) :: PR2(:,:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN) :: PR3(:,:,:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN) :: PR4(:,:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR1(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR2(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR3(:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR4(:,:,:,:)
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(IN) :: CDR
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFLDPROC2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLEVPROC3D(:)




















END SUBROUTINE IO_PUT
!=============================================================
SUBROUTINE IO_INQUIRE(YD,YDR,LDREAD,&
& KPARAMS,KNLEVS,KNVARS,KSMAX,KNVALS,KLATS,KLONS,PLATS,&
& KDATE,KTIME,KSTEP,KFLEV,PVALH,PVBH,PA,PB,KPTS,KLEVS,&
& KSVCOMP,KRITZ1,KRITZ2,KNUMB,KGRIB_HANDLE,KMINUTES,KNDICATOR,KSTART)























IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT)  :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
LOGICAL,OPTIONAL,INTENT(IN) :: LDREAD
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KPARAMS(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNLEVS(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNVARS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSMAX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNVALS

INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLATS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLONS(:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PLATS(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KDATE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KTIME
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSTEP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KFLEV
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSVCOMP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRITZ1
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRITZ2
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNUMB
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PVALH(0:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PVBH (0:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PA(:,:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PB(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KPTS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLEVS(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KGRIB_HANDLE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KMINUTES
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNDICATOR
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSTART





























END SUBROUTINE IO_INQUIRE
!=================================================================
SUBROUTINE SPEC_OUT(YD,YDR,PSPEC2,PSPEC3,KFLD2,KLEV,KFLD3)












IMPLICIT NONE
TYPE(TYPE_IOSTREAM) , INTENT(INOUT) :: YD
TYPE(TYPE_IOREQUEST), INTENT(INOUT) :: YDR
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PSPEC2(:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PSPEC3(:,:,:)
INTEGER(KIND=JPIM)  , INTENT(IN)    :: KFLD2,KLEV,KFLD3


















END SUBROUTINE SPEC_OUT
!=================================================================
SUBROUTINE GRID_OUT(YD,YDR,PGRID2,PGRID3,KFLD2,KLEV,KFLD3,KFLDPROC2D)












IMPLICIT NONE
TYPE(TYPE_IOSTREAM) , INTENT(INOUT)       :: YD
TYPE(TYPE_IOREQUEST), INTENT(INOUT)       :: YDR
REAL(KIND=JPRB)     , OPTIONAL,INTENT(IN) :: PGRID2(:,:,:)
REAL(KIND=JPRB)     , OPTIONAL,INTENT(IN) :: PGRID3(:,:,:,:)
INTEGER(KIND=JPIM)  , INTENT(IN)          :: KFLD2,KLEV,KFLD3
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KFLDPROC2D(:)



















END SUBROUTINE GRID_OUT
!=================================================================
SUBROUTINE IO_GET(YD,YDR,PR1,PR2,PR3,PR4,KR1,KR2,KR3,KR4,CDR,&
& LDMISSING_2D,LDMISSING_3D,KFLDPROC2D,KLEVPROC3D)


















IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT) :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PR1(:)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PR2(:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PR3(:,:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PR4(:,:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(INOUT) :: KR1(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(INOUT) :: KR2(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(INOUT) :: KR3(:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(INOUT) :: KR4(:,:,:,:)
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(INOUT) :: CDR
LOGICAL,OPTIONAL,INTENT(OUT) :: LDMISSING_2D(:)
LOGICAL,OPTIONAL,INTENT(OUT) :: LDMISSING_3D(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFLDPROC2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLEVPROC3D(:)















END SUBROUTINE IO_GET
!=================================================================
SUBROUTINE SPEC_IN(YD,YDR,PSPEC2,PSPEC3,KFLD2,KLEV,KFLD3,&
& LDMISSING_2D,LDMISSING_3D,KFLDPROC2D,KLEVPROC3D)














IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT) :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PSPEC2(:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PSPEC3(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD2,KLEV,KFLD3
LOGICAL,OPTIONAL,INTENT(OUT) :: LDMISSING_2D(:)
LOGICAL,OPTIONAL,INTENT(OUT) :: LDMISSING_3D(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFLDPROC2D(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLEVPROC3D(:)

















END SUBROUTINE SPEC_IN
!=================================================================
SUBROUTINE GRID_IN(YD,YDR,PGRID2,PGRID3,KFLD2,KLEV,KFLD3,&
&LDMISSING_2D,LDMISSING_3D,KFLDPROC2D)















IMPLICIT NONE
TYPE(TYPE_IOSTREAM) ,INTENT(INOUT) :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PGRID2(:,:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PGRID3(:,:,:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD2,KLEV,KFLD3
LOGICAL,OPTIONAL,INTENT(OUT)  :: LDMISSING_2D(:)
LOGICAL,OPTIONAL,INTENT(OUT)  :: LDMISSING_3D(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFLDPROC2D(:)


















END SUBROUTINE GRID_IN
!=============================================================
SUBROUTINE WRITE_RECORD(YD,YDR,KFIELDS,PREC,KREC,PREC1,KREC1,CDREC,&
& KALLFLDS,KIOFLDS,KHAVEFLDS)











IMPLICIT NONE
TYPE(TYPE_IOSTREAM) , INTENT(INOUT)       :: YD
TYPE(TYPE_IOREQUEST), INTENT(INOUT)       :: YDR
INTEGER(KIND=JPIM)  , INTENT(IN)          :: KFIELDS
REAL(KIND=JPRB)     , OPTIONAL,INTENT(IN) :: PREC(:,:)
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KREC(:,:)
REAL(KIND=JPRB)     , OPTIONAL,INTENT(IN) :: PREC1(:)
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KREC1(:)
CHARACTER(LEN=*)    , OPTIONAL,INTENT(IN) :: CDREC
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KALLFLDS
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KIOFLDS(:)
INTEGER(KIND=JPIM)  , OPTIONAL,INTENT(IN) :: KHAVEFLDS(:)

























END SUBROUTINE WRITE_RECORD
!=============================================================
SUBROUTINE READ_RECORD(YD,YDR,KFIELDS,PREC,KREC,PREC1,KREC1,CDREC)











IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(INOUT) :: YD
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT)    :: PREC(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KREC(:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT)    :: PREC1(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KREC1(:)
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(OUT) :: CDREC







































END SUBROUTINE READ_RECORD

!=============================================================
SUBROUTINE GRIB_ENCODE(YDR,PREC,KFIELDS)







IMPLICIT NONE
TYPE(TYPE_IOREQUEST), INTENT(INOUT) :: YDR
REAL(KIND=JPRB)     , INTENT(IN)    :: PREC(:,:)
INTEGER(KIND=JPIM)  , INTENT(IN)    :: KFIELDS




























END SUBROUTINE GRIB_ENCODE
!============================================================= 
SUBROUTINE GRIB_DECODE(YDR,PREC)







IMPLICIT NONE
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
REAL(KIND=JPRB),INTENT(OUT) :: PREC(:,:)











END SUBROUTINE GRIB_DECODE
!============================================================= 
SUBROUTINE GRIB_CHECKS(YDR)






IMPLICIT NONE
TYPE(TYPE_IOREQUEST),INTENT(IN) :: YDR





END SUBROUTINE GRIB_CHECKS
!============================================================= 
SUBROUTINE ALLO_IGRIB(YDR,KFIELDS,KLENGRB)






IMPLICIT NONE
TYPE(TYPE_IOREQUEST),INTENT(INOUT) :: YDR
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KLENGRB






END SUBROUTINE ALLO_IGRIB
!=============================================================
SUBROUTINE GET_PUT_ARGS(YDR,LDPR,KPRD,LDKR,KKRD,&
&PR1,PR2,PR3,PR4,KR1,KR2,KR3,KR4)


















IMPLICIT NONE
TYPE(TYPE_IOREQUEST),INTENT(IN) :: YDR
LOGICAL,INTENT(OUT) :: LDPR(4)
INTEGER(KIND=JPIM),INTENT(OUT) :: KPRD(4,4)
LOGICAL,INTENT(OUT) :: LDKR(4)
INTEGER(KIND=JPIM),INTENT(OUT) :: KKRD(4,4)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PR1(:)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PR2(:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PR3(:,:,:)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PR4(:,:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR1(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR2(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR3(:,:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KR4(:,:,:,:)



















END SUBROUTINE GET_PUT_ARGS
!=============================================================
SUBROUTINE ASSIGN_IOPROC(YD,KIOPROC,KMYCOUNT,KFLDPROC)








IMPLICIT NONE
TYPE(TYPE_IOSTREAM),INTENT(IN) :: YD
INTEGER(KIND=JPIM),INTENT(OUT) :: KIOPROC(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KMYCOUNT
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KFLDPROC(:)







END SUBROUTINE ASSIGN_IOPROC
!======================================================================
FUNCTION IFIND(KVAL,KARRAY)







IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN) :: KVAL
INTEGER(KIND=JPIM),INTENT(IN) :: KARRAY(:)
INTEGER(KIND=JPIM) :: IFIND







END FUNCTION IFIND
!=================================================================
FUNCTION IFINDR(PVAL,PARRAY)







REAL(KIND=JPRB),INTENT(IN) :: PVAL
REAL(KIND=JPRB),INTENT(IN) :: PARRAY(:)
INTEGER(KIND=JPIM) :: IFINDR







END FUNCTION IFINDR

!======================================================================

FUNCTION IFIND2(KVAL1,KVAL2,KARRAY1,KARRAY2)









INTEGER(KIND=JPIM),INTENT(IN) :: KVAL1,KVAL2
INTEGER(KIND=JPIM),INTENT(IN) :: KARRAY1(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KARRAY2(:)
INTEGER(KIND=JPIM) :: IFIND2






END FUNCTION IFIND2
!======================================================================

FUNCTION IGETHLP(YD,KFLD)






TYPE(TYPE_IOSTREAM),INTENT(IN) :: YD
INTEGER(KIND=JPIM),INTENT(IN)  :: KFLD
INTEGER(KIND=JPIM) :: IGETHLP,INUM





END FUNCTION IGETHLP
!======================================================================

FUNCTION IGETPROCHLP(YD,KFLD,KPROC)






TYPE(TYPE_IOSTREAM),INTENT(IN) :: YD
INTEGER(KIND=JPIM),INTENT(IN)  :: KFLD
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)  :: KPROC
INTEGER(KIND=JPIM) :: INUM,IGETPROCHLP




END FUNCTION IGETPROCHLP
!============================================================= 
SUBROUTINE GATH_GRID_FP(PGPG,KFGATHG,KTO,PGP)










IMPLICIT NONE
REAL(KIND=JPRB)    , INTENT(OUT) :: PGPG(:,:)
INTEGER(KIND=JPIM) , INTENT(IN)  :: KFGATHG
INTEGER(KIND=JPIM) , INTENT(IN)  :: KTO(:)
REAL(KIND=JPRB)    , INTENT(IN)  :: PGP(:,:,:)

































END SUBROUTINE GATH_GRID_FP
!======================================================================
SUBROUTINE INQUIRE_GRIB(KGRIB_HANDLE,KPARAM,KLEV,KSMAX,KNVALS,&
& CDREPRT,KLATS,KLONS,PLATS,&
& KDATE,KTIME,KSTEP,KFLEV,PVALH,PVBH,PA,PB,KPTS,&
& KSVCOMP,KRITZ1,KRITZ2,KNUMB,KMINUTES,KNDICATOR,KSTART)




















IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIB_HANDLE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KPARAM
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLEV
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSMAX
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNVALS
CHARACTER(LEN=*)  ,OPTIONAL,INTENT(OUT) :: CDREPRT
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLATS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KLONS(:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PLATS(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KPTS
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KDATE
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KTIME
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSTEP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KFLEV
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSVCOMP
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRITZ1
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KRITZ2
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNUMB
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PVALH(0:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PVBH (0:)
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PA
REAL   (KIND=JPRB),OPTIONAL,INTENT(OUT) :: PB
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KMINUTES
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KNDICATOR
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KSTART

































END SUBROUTINE INQUIRE_GRIB
!======================================================================
SUBROUTINE COPYGP_GLOB2LOC(PGLOB,PLOC,KPROMA,KPTS)









IMPLICIT NONE
REAL(KIND=JPRB),INTENT(IN)     :: PGLOB(:,:)
REAL(KIND=JPRB),INTENT(OUT)    :: PLOC(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN)  :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)  :: KPTS












END SUBROUTINE COPYGP_GLOB2LOC
!======================================================================
SUBROUTINE COPYGP_LOC2GLOB(PGLOB,PLOC,KPROMA,KPTS)









IMPLICIT NONE
REAL(KIND=JPRB),INTENT(OUT)  :: PGLOB(:,:)
REAL(KIND=JPRB),INTENT(IN)   :: PLOC(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN)  :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)  :: KPTS












END SUBROUTINE COPYGP_LOC2GLOB
!=============================================================
SUBROUTINE GRIB_UPDATE_MESSAGE(KGRIB_HANDLE,KGRIBCD,KLEV,CDREPR,CDLTYPE,PDATA,&
& KSMAX,LDGRAD,KTOP,KBOT,KGRIB_LEN,KGRIB)
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KGRIB_HANDLE
INTEGER(KIND=JPIM),INTENT(IN)    :: KGRIBCD
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
CHARACTER         ,INTENT(IN)    :: CDREPR*(*)
CHARACTER         ,INTENT(IN)    :: CDLTYPE*(*)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDATA(:)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAX
LOGICAL           ,INTENT(IN)    :: LDGRAD
INTEGER(KIND=JPIM),INTENT(IN)    :: KTOP
INTEGER(KIND=JPIM),INTENT(IN)    :: KBOT
INTEGER(KIND=JPKSIZE_T),INTENT(INOUT) :: KGRIB_LEN
INTEGER(KIND=JPIM),INTENT(OUT)   :: KGRIB(:)





















END SUBROUTINE GRIB_UPDATE_MESSAGE
 !=============================================================
END MODULE IOSTREAM_MIX

