
MODULE MF_PHYS_BASE_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE
USE FIELD_MODULE
IMPLICIT NONE


TYPE MF_PHYS_STATE_GSP_SG_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: F (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: F (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_F => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: A (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_A => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_R => NULL ()
END TYPE MF_PHYS_STATE_GSP_SG_TYPE

TYPE MF_PHYS_STATE_GSP_RR_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_FC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: W (:) => NULL ()
!>REAL (KIND=JPRB)                      :: W (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_W => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: IC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_IC => NULL ()
END TYPE MF_PHYS_STATE_GSP_RR_TYPE

TYPE MF_PHYS_STATE_GSP_SB_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: Q (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_Q => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: TL (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_TL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_T => NULL ()
END TYPE MF_PHYS_STATE_GSP_SB_TYPE


TYPE MF_PHYS_BASE_STATE_TYPE
  TYPE (CPG_DYN_TYPE) :: YCPG_DYN    
!>TYPE (CPG_DYN_TYPE) :: YCPG_DYN
  TYPE (CPG_PHY_TYPE) :: YCPG_PHY    
!>TYPE (CPG_PHY_TYPE) :: YCPG_PHY    
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1EXT  (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1CHEM (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1NOGW (:,:)   => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P2NOGW (:,:)   => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1LIMA (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P1AERO (:,:,:) => NULL ()
  
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVV (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: CVV (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_CVV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIV (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: DIV (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_DIV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB1 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB1 (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_EFB1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB2 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB2 (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_EFB2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB3 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB3 (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_EFB3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: G (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_G => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: H (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: H (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_H => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: I (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: I (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_I => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: L (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: L (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_L => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IMF (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: IMF (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_IMF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LMF (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: LMF (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LMF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: AMF (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: AMF (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_AMF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: O3 (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: O3 (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_O3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: Q (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_Q => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_R => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: S (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: S (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_S => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SRC (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: SRC (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_SRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TKE (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: TKE (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TKE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: U (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_U => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: V (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_V => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VOR (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: VOR (NPROMA,1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_VOR => NULL ()

  TYPE (MF_PHYS_STATE_GSP_SG_TYPE) :: YGSP_SG
  TYPE (MF_PHYS_STATE_GSP_RR_TYPE) :: YGSP_RR
  TYPE (MF_PHYS_STATE_GSP_SB_TYPE) :: YGSP_SB

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_BASE_STATE_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW

END TYPE MF_PHYS_BASE_STATE_TYPE

CONTAINS


SUBROUTINE MF_PHYS_BASE_STATE_TYPE_INIT (SELF, YDCPG_DYN0, YDCPG_DYN9, YDCPG_PHY0, &
&YDCPG_PHY9, YDVARS, YDMF_PHYS_SURF, YDMODEL, PGFL)
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE SC2PRG_MOD         , ONLY : SC2PRG
USE TYPE_MODEL         , ONLY : MODEL
CLASS (MF_PHYS_BASE_STATE_TYPE)        :: SELF
TYPE (MF_PHYS_SURF_TYPE),INTENT(IN)    :: YDMF_PHYS_SURF
TYPE (CPG_DYN_TYPE),    INTENT (IN)    :: YDCPG_DYN0, YDCPG_DYN9
TYPE (CPG_PHY_TYPE),    INTENT (IN)    :: YDCPG_PHY0, YDCPG_PHY9
TYPE (FIELD_VARIABLES), INTENT (IN)    :: YDVARS
TYPE(MODEL),            INTENT (IN)    :: YDMODEL
REAL (KIND=JPRB), TARGET, OPTIONAL :: PGFL (:,:,:)




















END SUBROUTINE MF_PHYS_BASE_STATE_TYPE_INIT

SUBROUTINE MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)
CLASS (MF_PHYS_BASE_STATE_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX


































END SUBROUTINE MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW

END MODULE MF_PHYS_BASE_STATE_TYPE_MOD
