MODULE YOE_TILE_PROP

USE PARKIND1  ,ONLY : JPRB

IMPLICIT NONE

PRIVATE 

!       ----------------------------------------------------------------
!PSEUDO HISTORICAL TESSEL QUANTITIES (INSTANTANEOUS) FOR EACH TILE

!     M.Hamrud      E.C.M.W.F.    20 Apr 2005
!     Moved out these arrays from GPPBUF     
!       ----------------------------------------------------------------

TYPE,PUBLIC :: TETILEPROP
  REAL(KIND=JPRB),ALLOCATABLE :: RUSTRTI(:,:,:) ! E-W  SURFACE STRESS 
  REAL(KIND=JPRB),ALLOCATABLE :: RVSTRTI(:,:,:) ! N-S  SURFACE STRESS 
  REAL(KIND=JPRB),ALLOCATABLE :: RAHFSTI(:,:,:) ! SURFACE SENSIBLE HEAT FLUX
  REAL(KIND=JPRB),ALLOCATABLE :: REVAPTI(:,:,:) ! EVAPORATION 
  REAL(KIND=JPRB),ALLOCATABLE :: RTSKTI (:,:,:) ! SKIN TEMPERATURE 
  CONTAINS
  PROCEDURE :: CREATE
  PROCEDURE :: ZERO
  PROCEDURE :: COPY
END TYPE TETILEPROP
CONTAINS
!============================================================================
SUBROUTINE CREATE(SELF,YDGEOMETRY,YDDPHY)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDPHY  , ONLY : TDPHY
IMPLICIT NONE
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDPHY)       ,INTENT(INOUT):: YDDPHY
CLASS(TETILEPROP) :: SELF

ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM)
ASSOCIATE(NPROMA=>YDDIM%NPROMA, NTILES=>YDDPHY%NTILES, &
 & NGPBLKS=>YDDIM%NGPBLKS)
ALLOCATE(SELF%RUSTRTI(NPROMA,NTILES,NGPBLKS))
ALLOCATE(SELF%RVSTRTI(NPROMA,NTILES,NGPBLKS))
ALLOCATE(SELF%RAHFSTI(NPROMA,NTILES,NGPBLKS))
ALLOCATE(SELF%REVAPTI(NPROMA,NTILES,NGPBLKS))
ALLOCATE(SELF%RTSKTI (NPROMA,NTILES,NGPBLKS))

SELF%RUSTRTI(:,:,:) = 0.0_JPRB
SELF%RVSTRTI(:,:,:) = 0.0_JPRB
SELF%RAHFSTI(:,:,:) = 0.0_JPRB
SELF%REVAPTI(:,:,:) = 0.0_JPRB
SELF%RTSKTI (:,:,:) = 0.0_JPRB

END ASSOCIATE
END ASSOCIATE

END SUBROUTINE CREATE
!============================================================================

SUBROUTINE ZERO(SELF)
CLASS(TETILEPROP) :: SELF
IF(ALLOCATED(SELF%RUSTRTI)) SELF%RUSTRTI=0.0_JPRB
IF(ALLOCATED(SELF%RVSTRTI)) SELF%RVSTRTI=0.0_JPRB
IF(ALLOCATED(SELF%RAHFSTI)) SELF%RAHFSTI=0.0_JPRB
IF(ALLOCATED(SELF%REVAPTI)) SELF%REVAPTI=0.0_JPRB
IF(ALLOCATED(SELF%RTSKTI)) SELF%RTSKTI=0.0_JPRB
END SUBROUTINE ZERO
!============================================================================
SUBROUTINE COPY(SELF,RHS)
CLASS(TETILEPROP) :: SELF
CLASS(TETILEPROP) :: RHS
!---------------------------------------------------------------------------
IF(ALLOCATED(SELF%RUSTRTI).AND.ALLOCATED(RHS%RUSTRTI)) THEN
  IF (ALL(SHAPE(SELF%RUSTRTI) == SHAPE(RHS%RUSTRTI))) THEN
    SELF%RUSTRTI=RHS%RUSTRTI
  ELSE
    CALL ABOR1("YOE_TILE_PROP:COPY - DIFFERNT SHAPES")
  ENDIF
ELSE
  CALL ABOR1("YOE_TILE_PROP:COPY - UNALLOCATED ARRAY")
ENDIF
!---------------------------------------------------------------------------
IF(ALLOCATED(SELF%RVSTRTI).AND.ALLOCATED(RHS%RVSTRTI)) THEN
  IF (ALL(SHAPE(SELF%RVSTRTI) == SHAPE(RHS%RVSTRTI))) THEN
    SELF%RVSTRTI=RHS%RVSTRTI
  ELSE
    CALL ABOR1("YOE_TILE_PROP:COPY - DIFFERNT SHAPES")
  ENDIF
ELSE
  CALL ABOR1("YOE_TILE_PROP:COPY - UNALLOCATED ARRAY")
ENDIF

IF(ALLOCATED(SELF%RAHFSTI).AND.ALLOCATED(RHS%RAHFSTI)) THEN
  IF (ALL(SHAPE(SELF%RAHFSTI) == SHAPE(RHS%RAHFSTI))) THEN
    SELF%RAHFSTI=RHS%RAHFSTI
  ELSE
    CALL ABOR1("YOE_TILE_PROP:COPY - DIFFERNT SHAPES")
  ENDIF
ELSE
  CALL ABOR1("YOE_TILE_PROP:COPY - UNALLOCATED ARRAY")
ENDIF

IF(ALLOCATED(SELF%REVAPTI).AND.ALLOCATED(RHS%REVAPTI)) THEN
  IF (ALL(SHAPE(SELF%REVAPTI) == SHAPE(RHS%REVAPTI))) THEN
    SELF%REVAPTI=RHS%REVAPTI
  ELSE
    CALL ABOR1("YOE_TILE_PROP:COPY - DIFFERNT SHAPES")
  ENDIF
ELSE
  CALL ABOR1("YOE_TILE_PROP:COPY - UNALLOCATED ARRAY")
ENDIF

IF(ALLOCATED(SELF%RTSKTI).AND.ALLOCATED(RHS%RTSKTI)) THEN
  IF (ALL(SHAPE(SELF%RTSKTI) == SHAPE(RHS%RTSKTI))) THEN
    SELF%RTSKTI=RHS%RTSKTI
  ELSE
    CALL ABOR1("YOE_TILE_PROP:COPY - DIFFERNT SHAPES")
  ENDIF
ELSE
  CALL ABOR1("YOE_TILE_PROP:COPY - UNALLOCATED ARRAY")
ENDIF

END SUBROUTINE COPY

END MODULE YOE_TILE_PROP
