MODULE YOEAERC

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

!     ------------------------------------------------------------------
!*    ** *YOEAERC* - TEGEN/GISS AEROSOL CLIMATOLOGY
!     ------------------------------------------------------------------

INTEGER(KIND=JPIM), PARAMETER :: NFDECSO4DIM=185 , NLDECSO4DIM=210
INTEGER(KIND=JPIM), PARAMETER :: ISHIST=1850, IEHIST=2100, INLAT=24


TYPE :: TEAERC_TEGEN
REAL(KIND=JPRB) :: REPAER = -HUGE(1._JPRB)
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERBC => NULL(), RAEROR => NULL(), RAERSD => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERSS => NULL(), RAERSU => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:,:,:) :: RAERV  => NULL()
REAL(KIND=JPRB), POINTER, DIMENSION(:)     :: RLATV  => NULL()
REAL(KIND=JPRB) :: RTAEBC(72,46), RTAEOR(72,46), RTAESD(72,46)
REAL(KIND=JPRB) :: RTAESS(72,46), RTAESU(72,46), RTAEVO(46)
INTEGER(KIND=JPIM) :: ISYEAR=IEHIST, IEYEAR=ISHIST

LOGICAL :: IS_INITIALISED = .FALSE.

CONTAINS 

PROCEDURE :: SETUP => SETUP_TEGEN
FINAL     :: FINALIZE_TEGEN

END TYPE TEAERC_TEGEN

!! storage arrays declared as global, to save on memory / initialisation costs
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:), TARGET, PRIVATE :: RAERBC_STORAGE, RAEROR_STORAGE, RAERSD_STORAGE
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:), TARGET, PRIVATE :: RAERSS_STORAGE, RAERSU_STORAGE
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:), TARGET, PRIVATE :: RAERV_STORAGE
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:),     TARGET, PRIVATE :: RLATV_STORAGE
INTEGER(KIND=JPIM) :: SMART_TEGEN_POINTER_COPIES = 0

!     ------------------------------------------------------------------
!*                   MACC-BASED AEROSOL CLIMATOLOGY
!     ------------------------------------------------------------------

TYPE :: TEAERC_MACC
!- based on optical depth

REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:,:) :: RMACBC, RMACOR, RMACSD, RMACSS, RMACSU !! appear not to be used
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:)   :: RMAEBC, RMAEOR, RMAESD, RMAESS, RMAESU

!- based on vertically integrated mass

REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACBC1, RMACBC2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAEBC1, RMAEBC2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACOR1, RMACOR2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAEOR1, RMAEOR2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSD1, RMACSD2, RMACSD3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESD1, RMAESD2, RMAESD3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSS1, RMACSS2, RMACSS3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESS1, RMAESS2, RMAESS3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: RMACSU1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: RMAESU1

!arrays for input 3D climatology on a 3x3 deg and 60 level grid
!lon,lat,lev,month
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACBC13D => NULL(), RMACBC23D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACOR13D => NULL(), RMACOR23D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSD13D => NULL(), RMACSD23D => NULL(), RMACSD33D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSS13D => NULL(), RMACSS23D => NULL(), RMACSS33D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: RMACSU13D => NULL()
REAL(KIND=JPRB), POINTER, CONTIGUOUS, DIMENSION(:,:,:,:) :: REF_MON_AER_PRS => NULL(),REF_MON_AER_DPRS => NULL()
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAEBC13D, RMAEBC23D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAEOR13D, RMAEOR23D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESD13D, RMAESD23D, RMAESD33D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESS13D, RMAESS23D, RMAESS33D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: RMAESU13D
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:)   :: REF_AER_PRS,REF_AER_DPRS

LOGICAL :: IS_INITIALISED = .FALSE.

CONTAINS 

PROCEDURE :: SETUP => SETUP_MACC
FINAL     :: FINALIZE_MACC

END TYPE TEAERC_MACC

!! storage array declared as global, to save on memory / initialisation costs
INTEGER(KIND=JPIM), PARAMETER, PRIVATE :: NUM_MAC3D_ARRAYS=13
INTEGER(KIND=JPIM), PARAMETER, PRIVATE :: NBC1=1, NBC2=2, NOR1=3, NOR2=4, NSD1=5, NSD2=6, NSD3=7, NSS1=8, NSS2=9, NSS3=10, &
 &                                        NSU1=11, NPRS=12, NDPRS=13
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_BC1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_BC2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_OR1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_OR2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SD1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SD2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SD3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SS1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SS2
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SS3
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_SU1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_PRS
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:,:), TARGET, PRIVATE :: RMAC3D_DPRS
INTEGER(KIND=JPIM) :: SMART_MACC3D_POINTER_COPIES = 0
INTEGER(KIND=JPIM) :: SMART_MACC_POINTER_COPIES = 0

!     ----------------------------------------------------------------------------
!*    ** *YOEAERC* - HISTORICAL TROPOSPHERIC SO4 DATA (TOTAL BURDEN IN G/M^2)
!     ----------------------------------------------------------------------------

!TYPE(REGLATLON_FIELD) ::  RAERSO4  !! moved to YOMRIP, because has time-varying values
CHARACTER(LEN=260),SAVE              :: CLISTSO4,FILESO4(NFDECSO4DIM:NLDECSO4DIM)

LOGICAL              , SAVE ::  LVOLCDATA
CHARACTER (LEN = 260), SAVE ::  CVOLCDATA

!        * E.C.M.W.F. PHYSICS PACKAGE *

!     J.-J. MORCRETTE       E.C.M.W.F.      98/12/21

!  NAME     TYPE    PURPOSE
!  ----  :  ----  : ---------------------------------------------------
! -- for Tegen et al. 1997 climatology
! RAERBC : REAL   : OPTICAL THICKNESS BLACK CARBON TYPE AEROSOL
! RAEROR : REAL   : OPTICAL THICKNESS ORGANIC TYPE AEROSOL
! RAERSD : REAL   : OPTICAL THICKNESS SOIL-DUST TYPE AEROSOL
! RAERSS : REAL   : OPTICAL THICKNESS SEA-SALT TYPE AEROSOL
! RAERSU : REAL   : OPTICAL THICKNESS SULFATE-TYPE AEROSOL
! RAERV  : REAL   : VOLCANIC OPTICAL THICKNESS 
! RTAEBC : REAL   : TIME-INTERPOLATED BLACK CARBON OPTICAL THICKNESS
! RTAEOR : REAL   : TIME-INTERPOLATED ORGANIC OPTICAL THICKNESS
! RTAESD : REAL   : TIME-INTERPOLATED SOIL-DUST OPTICAL THICKNESS
! RTAESS : REAL   : TIME-INTERPOLATED SEA-SALT OPTICAL THICKNESS
! RTAESU : REAL   : TIME-INTERPOLATED SULFATE CARBON OPTICAL THICKNESS
! RLATV  : REAL   : REFERENCE LATITUDES, stored in type for convenience

! -- for MACC-derived aerosol climatology
! RMACBC : REAL   : OPTICAL THICKNESS BLACK CARBON TYPE AEROSOL
! RMACOR : REAL   : OPTICAL THICKNESS ORGANIC TYPE AEROSOL
! RMACSD : REAL   : OPTICAL THICKNESS SOIL-DUST TYPE AEROSOL
! RMACSS : REAL   : OPTICAL THICKNESS SEA-SALT TYPE AEROSOL
! RMACSU : REAL   : OPTICAL THICKNESS SULFATE-TYPE AEROSOL
! RMAEBC : REAL   : TIME-INTERPOLATED BLACK CARBON OPTICAL THICKNESS
! RMAEOR : REAL   : TIME-INTERPOLATED ORGANIC OPTICAL THICKNESS
! RMAESD : REAL   : TIME-INTERPOLATED SOIL-DUST OPTICAL THICKNESS
! RMAESS : REAL   : TIME-INTERPOLATED SEA-SALT OPTICAL THICKNESS
! RMAESU : REAL   : TIME-INTERPOLATED SULFATE CARBON OPTICAL THICKNESS

! RTAEVO : REAL   : TIME-INTERPOLATED STRATOS.VOLCANIC OPTICAL THICKNESS
! RTAESO4: REAL   : TIME-INTERPOLATED SO4 LOAD (G/M^2)

! REPAER : REAL   : SECURITY PARAMETER FOR AEROSOLS

! LVOLCDATA : LOGICAL   : .TRUE.  READ STRATOS.VOLCANIC OPTICAL THICKNESS FROM FILE
!                         .FALSE. USE HARD-CODED VALUES
! CVOLCDATA : CHARACTER : FILENAME FOR STRATOS.VOLCANIC OPTICAL THICKNESS DATA
!     ------------------------------------------------------------------

!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE SETUP_TEGEN(SELF, LCALL_SUECAEC)
USE YOMLUN, ONLY : NULOUT

CLASS(TEAERC_TEGEN), INTENT(INOUT) :: SELF
LOGICAL, INTENT(IN)                :: LCALL_SUECAEC








END SUBROUTINE SETUP_TEGEN

SUBROUTINE FINALIZE_TEGEN(SELF)
USE YOMLUN, ONLY : NULOUT

TYPE(TEAERC_TEGEN), INTENT(INOUT) :: SELF





END SUBROUTINE FINALIZE_TEGEN

!==========================================================================================

SUBROUTINE SETUP_MACC(SELF,LLAER3D)
USE YOMLUN, ONLY : NULOUT

CLASS(TEAERC_MACC), INTENT(INOUT) :: SELF
LOGICAL, INTENT(IN)               :: LLAER3D





END SUBROUTINE SETUP_MACC

SUBROUTINE FINALIZE_MACC(SELF)
USE YOMLUN, ONLY : NULOUT

TYPE(TEAERC_MACC), INTENT(INOUT) :: SELF






END SUBROUTINE FINALIZE_MACC


#ifdef RS6K
@PROCESS NOOPTIMIZE
#endif
!pgi$r opt=0 
SUBROUTINE SUECAEC(YDEAERC_TEGEN)














































USE PARKIND1     , ONLY : JPRD, JPIM, JPRB
USE YOMLUN       , ONLY : NULOUT, FOPEN
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE
TYPE(TEAERC_TEGEN), INTENT(INOUT) :: YDEAERC_TEGEN























END SUBROUTINE SUECAEC


SUBROUTINE SU_AER_CLIMATOLOGY(SELF_MACC)






















USE PARKIND1  , ONLY : JPIM, JPRB
USE EASY_NETCDF_READ_MPI,ONLY : NETCDF_FILE
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN    , ONLY : NULERR
IMPLICIT NONE


TYPE(TEAERC_MACC), INTENT(INOUT) :: SELF_MACC



































END SUBROUTINE SU_AER_CLIMATOLOGY

SUBROUTINE SU_AER_CLIMATOLOGY3D(SELF_MACC)























USE PARKIND1            , ONLY : JPIM, JPRB
USE YOMHOOK             , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN              , ONLY : NULERR, NULOUT
USE EASY_NETCDF_READ_MPI, ONLY : NETCDF_FILE
USE YOMMP0              , ONLY : MYPROC, NPROC
USE OMP_LIB
IMPLICIT NONE


TYPE(TEAERC_MACC), INTENT(INOUT) :: SELF_MACC

















































END SUBROUTINE SU_AER_CLIMATOLOGY3D

SUBROUTINE CHECK_ARRAY( ARR, NAME_STR )
USE YOMLUN, ONLY : NULOUT
USE, INTRINSIC :: IEEE_ARITHMETIC
REAL(KIND=JPRB), INTENT(IN) :: ARR(:,:,:,:)
CHARACTER(LEN=*), INTENT(IN) :: NAME_STR








END SUBROUTINE CHECK_ARRAY

END MODULE YOEAERC

