MODULE YOMDIAGVAR
! 
! Diagnostics of 4DVAR for print-out
!
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE



TYPE DIAGVAR
  INTEGER(KIND=JPIM)  :: NOBS,NCOST
  REAL(KIND=JPRB)     :: CONDNUM,JO,JB,JC,JQ,JP,JH,JCVARBC
END TYPE DIAGVAR 

TYPE(DIAGVAR) :: DIAG_4DVAR
END MODULE YOMDIAGVAR
