MODULE YOMGRIB

USE PARKIND1 , ONLY : JPIM

IMPLICIT NONE

SAVE

!     ------------------------------------------------------------------
!*    GRIB CODING DESCRIPTORS

! NLOCGRB - ECMWF LOCAL USAGE IDENTIFIER
! NTOTENS - TOTAL NUMBER OF FORCASTS IN ENSEMBLE
! NENSFNB - ENSAMBLE FORECAST NUMBER
! NWINOFF - OFFSET OF ANALYSIS FROM END OF ASSIMILATION WINDOW [HOURS]
! NWINOFF_4V  - OFFSET OF 4V,ME,EA,EF FIELDS FROM END OF ASSIMILATION WINDOW [HOURS]
! NSTREAM - EXPLICIT STREAM NUMBER (OR ZERO FOR DEFAULT STREAMS TO BE USED)
! NSYSTEM - FOR USE IN SEASONAL STREAM (DIFFERENT OPERATIONAL SYSTEMS)
! NMETHOD - FOR USE IN SEASONAL STREAM (DIFFERENT ENSEMBLES)
! NREFERENCE - FOR USE IN HINDCAST STREAM 
! NCONSENSUS - FOR MULTI_ANALYSIS STREAM (1 if consensus)
! NDWD    - FOR MULTI_ANALYSIS STREAM (1 if DWD analysis used)
! NMFR    - FOR MULTI_ANALYSIS STREAM
! NNCEP   - FOR MULTI_ANALYSIS STREAM
! NUKM   - FOR MULTI_ANALYSIS STREAM
! NSTEPLPP - STEP FOR PREVIOUS P.P. OF VARIABLE WITH GRIB CODE II
! NSMAXNP - SUBTRUNCTATION FOR COMPLEX PACKING OF SPECTRAL COEFF
! NBITSSH - NUMBER OF BITS FOR PACKING SPECTRAL COEFF.
! NJDIAG  - SENSITIVITY DIAGNOSTIC NUMBER (1=>J1, 2=>J2, 3=>J3, 4=>J4)
! NJDOMAI - SENSITIVITY DIAGNOSTIC MASK REGION (0=>global, 1=>europe,
!                                               2=>N.H., 3=>S.H.)
! NLEG    - current VAREPS leg number (eg 1(2) for the T399(T255) part of a T399-T255 VAREPS)
! NCYCLE     : cycle identifier
! CFCLASS    : class for use by FDB
! CTYPE      : type for use by FDB
! NBITSSHLNSP - Number of bits for GRIB encoding of LNSP (default=16)
! NBITSEXPR   - Number of bits for GRIB encoding of experimental parameters (default=-1 in which case multio is deciding)

INTEGER(KIND=JPIM),PARAMETER :: JPNUMLPP=5
INTEGER(KIND=JPIM) :: NSTEPLPP(JPNUMLPP,2)

INTEGER(KIND=JPIM), PARAMETER :: JPMAXSFLEVS=12
INTEGER(KIND=JPIM) :: NSFLEVS(JPMAXSFLEVS,3) = -1

INTEGER(KIND=JPIM) :: NLOCGRB
INTEGER(KIND=JPIM) :: NTOTENS
INTEGER(KIND=JPIM) :: NENSFNB
INTEGER(KIND=JPIM) :: NWINOFF
INTEGER(KIND=JPIM) :: NWINOFF_4V
INTEGER(KIND=JPIM) :: NSTREAM
INTEGER(KIND=JPIM) :: NSYSTEM
INTEGER(KIND=JPIM) :: NMETHOD
INTEGER(KIND=JPIM) :: NREFERENCE
INTEGER(KIND=JPIM) :: NCONSENSUS
INTEGER(KIND=JPIM) :: NDWD
INTEGER(KIND=JPIM) :: NMFR
INTEGER(KIND=JPIM) :: NNCEP
INTEGER(KIND=JPIM) :: NUKM
INTEGER(KIND=JPIM) :: NBITSSH
INTEGER(KIND=JPIM) :: NJDIAG
INTEGER(KIND=JPIM) :: NJDOMAI
INTEGER(KIND=JPIM) :: NJITER

INTEGER(KIND=JPIM) :: NLEG
INTEGER(KIND=JPIM) :: NCYCLE=-100
CHARACTER (LEN = 2) ::  CFCLASS
CHARACTER (LEN = 2) ::  CTYPE

INTEGER(KIND=JPIM) :: NBITSSHLNSP
INTEGER(KIND=JPIM) :: NBITSEXPR

!     ------------------------------------------------------------------
END MODULE YOMGRIB
