SUBROUTINE CPG_DIA_FLU_PARALLEL (YDMF_PHYS_OUT)

USE MF_PHYS_TYPE_MOD

IMPLICIT NONE

TYPE(MF_PHYS_OUT_TYPE)  ,INTENT(IN)     :: YDMF_PHYS_OUT

INTEGER (KIND=4) :: IBL

DO IBL = 1, 10
  CALL MF_PHYS_OUT_TYPE_UPDATE_VIEW (YDMF_PHYS_OUT, IBL)
  WRITE (0, *) __FILE__, ':', __LINE__, " ASSOCIATED (YDMF_PHYS_OUT%DIFCQ) = ", ASSOCIATED (YDMF_PHYS_OUT%DIFCQ)
STOP
ENDDO

END SUBROUTINE
