PROGRAM WRAP_CPG_DIA_FLU

USE MF_PHYS_TYPE_MOD        , ONLY : MF_PHYS_OUT_TYPE

IMPLICIT NONE

TYPE(MF_PHYS_OUT_TYPE)    :: YLMF_PHYS_OUT

#include "cpg_dia_flu_parallel.intfb.h"

ALLOCATE (YLMF_PHYS_OUT%F_DIFCQ)
ALLOCATE (YLMF_PHYS_OUT%F_DIFCQ%PTR (1:32,0:15,1:56))

CALL CPG_DIA_FLU_PARALLEL (YLMF_PHYS_OUT)

END PROGRAM

