SUBROUTINE SS2 (KGPTOT, YDRIP)

USE YOMRIP1, ONLY : TRIP1

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

INTEGER            ,INTENT(IN)    :: KGPTOT
TYPE(TRIP1)        ,INTENT(INOUT) :: YDRIP

REAL(KIND=JPRB) :: ZMU0 (KGPTOT)
REAL(KIND=JPRB) :: GEMU (KGPTOT), GELAM (KGPTOT)

INTEGER(KIND=JPIM) :: IENDC,JKGLO,JF,JLON,IBL,IGPTOT
CHARACTER*64 :: CLFILE

ASSOCIATE(RSIDEC=>YDRIP%RSIDEC, RCODEC=>YDRIP%RCODEC, RSIVSR=>YDRIP%RSIVSR, RCOVSR=>YDRIP%RCOVSR)

ZMU0 = 0

CLFILE = "DATA.001"
OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED')
READ (77) IGPTOT
READ (77) RCODEC
READ (77) RCOVSR
READ (77) RSIDEC
READ (77) RSIVSR
READ (77) GELAM
READ (77) GEMU
CLOSE (77)

DO JKGLO=1,KGPTOT
  ZMU0(JKGLO)=MAX ( RSIDEC*GEMU(JKGLO)&
  & -RCODEC*RCOVSR*SQRT(1.0_JPRB-GEMU(JKGLO)**2)*COS(GELAM(JKGLO))&
  & +RCODEC*RSIVSR*SQRT(1.0_JPRB-GEMU(JKGLO)**2)*SIN(GELAM(JKGLO))&
  & ,0.0_JPRB )
ENDDO

DO JKGLO = 4, 4
  WRITE (0, '(I6," ",E30.20)') JKGLO, ZMU0 (JKGLO)
ENDDO

END ASSOCIATE

END SUBROUTINE

