MODULE YOMRIP1

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8, JPRD = 8

TYPE :: TRIP1

REAL(KIND=JPRB) :: RSTATI
REAL(KIND=JPRD) :: RTIMTR 
REAL(KIND=JPRB) :: RHGMT
REAL(KIND=JPRB) :: REQTIM
REAL(KIND=JPRB) :: RSOVR
REAL(KIND=JPRB) :: RDEASO
REAL(KIND=JPRB) :: RDECLI
REAL(KIND=JPRB) :: RWSOVR
REAL(KIND=JPRB) :: RIP0
REAL(KIND=JPRB) :: RCODEC
REAL(KIND=JPRB) :: RSIDEC
REAL(KIND=JPRB) :: RCOVSR
REAL(KIND=JPRB) :: RSIVSR
REAL(KIND=JPRB) :: RCODECN
REAL(KIND=JPRB) :: RSIDECN
REAL(KIND=JPRB) :: RCOVSRN
REAL(KIND=JPRB) :: RSIVSRN
REAL(KIND=JPRB) :: RCODECF
REAL(KIND=JPRB) :: RSIDECF
REAL(KIND=JPRB) :: RCOVSRF
REAL(KIND=JPRB) :: RSIVSRF
REAL(KIND=JPRB) :: TSTEP
REAL(KIND=JPRB) :: TDT
REAL(KIND=JPRB) :: RDTSA
REAL(KIND=JPRB) :: RDTSA2
REAL(KIND=JPRB) :: RDTS62
REAL(KIND=JPRB) :: RDTS22
REAL(KIND=JPRB) :: RTDT
REAL(KIND=JPRB) :: RDECLU
REAL(KIND=JPRB) :: RTMOLT
REAL(KIND=JPRD) :: RJUSMP 
REAL(KIND=JPRB) :: RLUNDI
REAL(KIND=JPRB) :: RIP0LU
REAL(KIND=JPRB) :: RCODECLU
REAL(KIND=JPRB) :: RSIDECLU
REAL(KIND=JPRB) :: RCOVSRLU
REAL(KIND=JPRB) :: RSIVSRLU

END TYPE TRIP1

END MODULE YOMRIP1
